README.md

Clarify numbers in the performance portion of README

---

README.md
horovod/tensorflow/mpi_ops.cc
horovod/tensorflow/timeline.cc
horovod/tensorflow/timeline.h
setup.py

Horovod Timelines add ability to analyze Horovod performance with Chrome Tracing.

Horovod Timelines

---

README.md
horovod/tensorflow/mpi_message.cc
horovod/tensorflow/mpi_message.h
horovod/tensorflow/mpi_ops.cc
horovod/tensorflow/mpi_ops_test.py
horovod/tensorflow/timeline.cc
horovod/tensorflow/timeline.h
horovod/tensorflow/wire/mpi_message.fbs
horovod/tensorflow/wire/mpi_message_generated.h
setup.py

Tensor Fusion works by attempting to combine all the tensors that are ready to be reduced at given moment of time into one reduction operation.  See README for further details.

Tensor Fusion: fuse small allreduce tensor operations into larger ones for performance gain

---

setup.py

TensorFlow plugin compilation procedure has been updated as follows:
1. TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')
2. Then add -L$TF_LIB -ltensorflow_framework to your compilation command.
This change will be backward compatible - we first determine whether -ltensorflow_framework exists and if so use it in the subsequent build process.

Link with new -ltensorflow_framework if it's available

---

horovod/tensorflow/__init__.py
setup.py

Add grad=None check in DistributedOptimizer

---

README.md
docs/troubleshooting.md
examples/keras_mnist.py
examples/tensorflow_mnist.py
setup.py

Various documentation updates

---

docs/gpus.md

Update Horovod on GPU docs

---

setup.py

Add requirement for TensorFlow 1.1.0+

---

.travis.yml
setup.py

https://github.com/tensorflow/tensorflow/pull/13496 is merged which adds `tf.sysconfig.get_compile_flags()` & `tf.sysconfig.get_link_flags()`.

Add support for new tf.sysconfig.get_compile_flags() and tf.sysconfig.get_link_flags()

---

.travis.yml
README.md
examples/keras_mnist.py
examples/keras_mnist_advanced.py
examples/tensorflow_mnist.py
examples/tensorflow_word2vec.py
horovod/keras/__init__.py
horovod/keras/callbacks.py
horovod/tensorflow/__init__.py
setup.py

Introduce package horovod.keras which provides functional parity between Keras and TensorFlow.

First-class Keras support

---

docs/troubleshooting.md

Troubleshooting: add an error message that indicates outdated MPI

---

README.md

Readme updates: logo, references

---

.travis.yml
README.md
examples/keras_mnist.py
examples/keras_mnist_advanced.py
examples/tensorflow_mnist.py
examples/tensorflow_mnist_estimator.py
examples/tensorflow_word2vec.py

1. Add Estimator example.
2. Annotate parts relevant to Horovod with a comment `# Horovod: ...`
3. Make sure all examples adjust LR and number of steps.

 Add TensorFlow Estimator example, update existing examples

---

Dockerfile

Test image pushed to dockerhub rongou/horovod:latest.

Upgrade the dockerfile to tensorflow 1.5.0, cuda 9, cudnn 7, nccl 2.1.4.

---

README.md

Add reference to arXiv publication

---

Dockerfile

Update to TensorFlow 1.6.0

---

README.md
docs/benchmarks.md
docs/docker.md
docs/running.md
docs/troubleshooting.md

Add -x PATH to command line examples

---

horovod/common/operations.cc

Fix void pointer arithmetic warning

---

.travis.yml

There's regression in python*-pip package, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896998.

Fix Travis CI tests

---

Dockerfile
docs/docker.md

Build commands:
```
$ docker build . --build-arg python=2.7 -t uber/horovod:0.12.1-tf1.8.0-py2.7
$ docker build . --build-arg python=3.5 -t uber/horovod:0.12.1-tf1.8.0-py3.5
```

Make Python version configurable via docker build --build-arg

---

README.md

cc @rongou, @cheyang
Fixes #290

Add pointers to MPI Operator and Helm Chart

---

test/test_tensorflow.py

Recently TensorFlow introduced a requirement to use a consistent set of
GPUs across TensorFlow sessions.
https://github.com/tensorflow/tensorflow/issues/16753

Fix TensorFlow GPU tests

---

examples/pytorch_imagenet_resnet50.py

Converges to 76%+ Top-1 accuracy on 128 GPUs.

Add PyTorch ImageNet example

---

examples/pytorch_imagenet_resnet50.py

Corrected a typo on line 32.  Changed for for to for.

Corrected a minor typo

---

horovod/common/operations.cc

Sorting ranks which are ready for mpi and logging missing ranks

Make stalled error message more readable

---

docs/timeline.md
horovod/common/operations.cc
horovod/common/operations.h

A simple version of hierarchical allreduce (NCCL reduce, MPI allreduce between nodes, NCCL broadcast).
Some simplifications + code movements and refactoring.

Hierarchical NCCL + MPI allreduce

---

horovod/common/operations.cc
setup.py

* Include making FinalizerThread more generic using
a queue of events to wait for.

Add support for IBM PowerAI DDL gpu allreduce

---

examples/keras_imagenet_resnet50.py
examples/pytorch_imagenet_resnet50.py

Intent is to have parity with those in the PyTorch examples

Added command line args to Keras ImageNet examples

---

horovod/common/operations.cc
horovod/common/operations.h

Knob to disable stall check - HOROVOD_STALL_CHECK_DISABLE=1

---

setup.py

See https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/index.html#intergpu, #146 and #153.

Discourage mixing NCCL and MPI-GPU implementations

---

horovod/common/timeline.cc
horovod/common/timeline.h

Bugfix: Protect Timeline state from concurrent access

---

horovod/common/operations.cc

Use MPI_THREAD_SINGLE if HOROVOD_MPI_THREADS_DISABLE is set

---

MANIFEST.in
hide_nccl.lds
horovod.exp
horovod.lds
setup.py

Export only Horovod symbols

---

build-docker-images.sh

build_docker_images.sh: don't fail if nvidia/cuda does not exist yet

---

.travis.yml
README.md
examples/pytorch_mnist.py
horovod/torch/__init__.py
horovod/torch/adapter_v2.h
horovod/torch/mpi_ops.py
horovod/torch/mpi_ops_v2.cc
setup.py
test/test_torch.py

Accommodations for https://github.com/pytorch/pytorch/pull/11510
Removing PyTorch 0.3.1 backward compatibility to simplify the code.
cc @goldsborough

PyTorch 1.0 readiness updates

---

setup.py

Don't import torch if HOROVOD_WITHOUT_PYTORCH is set

---

.travis.yml

pytorch/pytorch#11995 was resolved.

Revert `future` dependency

---

horovod/common/common.cc
horovod/common/common.h
horovod/common/operations.cc
horovod/tensorflow/mpi_ops.cc
horovod/torch/adapter.cc
horovod/torch/adapter_v2.cc

Raise an error if hvd.allreduce() uses existing tensor name

---

horovod/torch/__init__.py
test/test_torch.py

Broadcast optimizer options in addition to parameter state

---

.travis.yml
horovod/torch/adapter_v2.cc
horovod/torch/mpi_ops.py
setup.py

See pytorch/pytorch#12687 & pytorch/pytorch#12504

PyTorch master compatibility, improved errors in case of .so import failure

---

horovod/common/operations.cc

Fix race on horovod_global.tensor_table

---

horovod/common/operations.cc

Move finalization logic into termination of BackgroundThread

---

horovod/common/operations.cc

Define RECORD_EVENT and WAIT_FOR_EVENTS when HAVE_CUDA is enabled

---

README.md
docs/gpus.md

Docs: note that Open MPI 3.1.3 has an issue

---

Dockerfile

Docker: Allow downgrades to make build deterministic

---

docs/gpus.md
horovod/common/mpi_message.cc
horovod/common/mpi_message.h
horovod/common/operations.cc
test/test_tensorflow.py

Enables Tensor fusion for allgather operation

Tensor fusion for allgather

---

horovod/spark/driver/mpirun_rsh.py

Verify host_hash to avoid strange errors due to old Open MPI

---

horovod/common/operations.cc

Independent tensor fusion by dtype to enable more fusion in mixed precision cases.

Mixed precision fusing

---

examples/tensorflow_mnist_eager.py
horovod/tensorflow/__init__.py

This API has not been formally released yet, so I'm making a breaking change.
cc @kuroko1t - we should align order of parameters of these two APIs

Align broadcast_variables() API with broadcast()

---

Dockerfile

Add MXNet 1.4.0 to Dockerfile

---

examples/tensorflow_mnist_eager.py

Make tensorflow_mnist_eager.py Python2-friendly

---

examples/pytorch_imagenet_resnet50.py

Bugfix PyTorch ImageNet example

---

README.md

Add PyPI download statistics

---

setup.py

When I ran horovod with MXNet mkldnn backend, I got a segmentation fault. Then, I checked the file setup.py, there are no option found to specify the backend on which MXNet was built.  So, I added the option 'MXNET_USE_MKLDNN' when building horovod from source. At the same time, we should set environment variable 'MXNET_USE_MKLDNN=1'  before installing horovod. Now, the segfault is addressed.

Address segfault when using MXNet MKLDNN backend

---

setup.py

Fix a bug in detecting MKLDNN in MXNet

Fix detecting MKLDNN in MXNet

---

horovod/common/parameter_manager.cc
horovod/common/parameter_manager.h

Fixed parameter manager to use the previously set value for Bayesian parameters when changing a free parameter to a constant

---

horovod/common/timeline.h

Added explicit include of atomic to fix issue with Intel compiler

---

docs/troubleshooting.md

Add HOROVOD_CUDA_HOME documentation

---

Dockerfile
README.md
docs/benchmarks.md
docs/docker.md
docs/running.md
docs/tensor-fusion.md
docs/timeline.md
docs/troubleshooting.md
horovod/run/run.py

Adopt horovodrun

---

horovod/run/run.py
horovod/run/util/cache.py

Fixed two typos in horovodrun PR. 
Signed-off-by: fardin <fardin@uber.com>

Fixed two typos in horovodrun PR

---

Dockerfile

Bugfix Dockerfile

---

horovod/common/ops/ddl_operations.cc

Fix typo in DDL

---

horovod/run/common/util/env.py
horovod/run/common/util/env_constants.py
horovod/run/run.py
horovod/spark/__init__.py

See https://bugzilla.redhat.com/show_bug.cgi?id=1147453 for more
details.
Fixes #948 
Fixes #950

Ignore BASH_FUNC_module() environment variable (bash bug)

---

horovod/common/operations.cc
horovod/common/ops/nccl_operations.cc
horovod/common/ops/nccl_operations.h

Horovod doesn't free NCCL communicator

add nccl comm destroy

---

docs/spark.md
examples/keras_spark_rossmann.py

Make Spark example Python3 compatible

---

examples/pytorch_mnist.py

Add broadcast_optimizer_state to pytorch_mnist.py

---

README.md

Signed-off-by: alexander.sergeev@live.com

Move FOSSA to new repository

---

.buildkite/gen-pipeline.sh

Some tests are framework-agnostic and can be run only with the latest framework version.

Add framework-agnostic tests section

---

docker-compose.test.yml

Try to unpin tf-nightly since tensorflow/tensorflow#22797 is resolved.

Unpin tf-nightly

---

docker-compose.test.yml

See tensorflow/tensorflow#27697

Pin tf-nightly due to build break

---

horovod/run/common/util/env.py
horovod/run/run.py
horovod/spark/__init__.py

Add BASH_FUNC_*() into unexportable envs

---

horovod/run/common/service/driver_service.py
horovod/run/common/service/task_service.py
horovod/run/common/util/network.py
horovod/run/common/util/settings.py
horovod/run/driver/driver_service.py
horovod/run/run.py
horovod/run/task/task_service.py
horovod/run/task_fn.py
horovod/spark/__init__.py
horovod/spark/driver/driver_service.py
horovod/spark/driver/mpirun_rsh.py
horovod/spark/task/mpirun_exec_fn.py
horovod/spark/task/task_service.py

Adds more information to the error message when hosts cannot find a common interface.

Added better error msg for interface name mismatch

---

docker-compose.test.yml

Unpin tf-nightly once tensorflow/tensorflow#27697 is resolved.

Unpin tf-nightly & pin MXNet

---

README.md

Added missing "torch." before using torch.optim module

Added missing "torch." before using torch.optim module

---

setup.py

Do not specify -mavx if AVX is not supported

---

horovod/common/operations.cc
horovod/common/ops/ddl_operations.cc
horovod/common/ops/ddl_operations.h

IBM Spectrum MPI is provided with IBM PowerAI DDL. Spectrum MPI needs to be initialized with the proper license. This PR let DDL initialize MPI when using the DDL backend.

Initialize correctly IBM Spectrum MPI provided with IBM PowerAI DDL

---

docker-compose.test.yml

tensorflow/tensorflow#28845 is resolved.

Unpin tf-nightly-gpu

---

horovod/torch/__init__.py
test/test_torch.py

Support .step(synchronize=False) for gradient clipping & NVIDIA AMP

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question.md

As part of migration to ReadTheDocs.

Fix issue templates, replace .md with .rst

---

docs/benchmarks.rst
docs/docker.rst
docs/gpus.rst
docs/running.rst
docs/spark.rst
docs/timeline.rst
docs/troubleshooting.rst

As mentioned in the comments [here](https://github.com/horovod/horovod/pull/1088), the emphasis of the titles for subsections has to be changed so that they will become links in the `index`.

Changes subtitle emphasis 

---

docs/gpus.rst
docs/index.rst
docs/mpirun.rst
docs/running.rst
docs/summary.rst
docs/summary_include.rst
docs/timeline.rst
docs/troubleshooting.rst

- Ensure consistency in heading capitalization (sentence case for sections, title case for standalone pages)
- Light copyedit
- Modify some .rst formatting

Edit Horovod docs

---

docs/mpirun.rst

The command for 1 machine/4 GPUs was the same as for 4 machines/4 GPUs. The command was changed to be the same as in the project root documentation.

Updated horovodrun command

---

README.rst
docs/summary.rst

Link to: https://github.com/sylabs/examples/tree/master/machinelearning/horovod

Add Singularity example page

---

horovod/common/operations.cc
horovod/common/ops/mlsl_operations.cc
horovod/common/ops/mlsl_operations.h

Signed-off-by: Mikhail Shiryaev <mikhail.shiryaev@intel.com>

MLSL: move mlsl_init before mpi_init, add mlsl_finalize call

---

docs/keras.rst
docs/summary.rst

Hello! I was talking to @sblotner about the next steps for the documentation, and she mentioned some pages were missing content. In this one, the idea is to give tips and describe special situations that can be useful when using `Horovod` with `Keras`. I still don't have much experience with the project, so for now I just pasted the description of `Horovod with Tensorflow` together with an example using `Keras`. If @alsrgv or someone else could give me high-level inputs of what is important to write I can improve the text accordingly. Thanks!

Update "Horovod with Keras" documentation page

---

docs/summary.rst

Fixes spacing in Horovod with Tensorflow docs page

---

Dockerfile.test.cpu
Dockerfile.test.gpu
examples/tensorflow2_keras_mnist.py
horovod/_keras/__init__.py
horovod/_keras/callbacks.py
horovod/tensorflow/__init__.py

TF-Keras support for TensorFlow 2.0

---

setup.py

Resolves [this comment](https://github.com/horovod/horovod/commit/16592837d65092202dda001d09192e39b82139c7#commitcomment-34387081)
cc @nskool

Fix g++ autodetect: ldshared

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Signed-off-by: Sihan Zeng <zsh@uber.com>

Added g++-7 in docker file for the latest tf-nighly

---

horovod/common/fusion_buffer_manager.cc
horovod/common/fusion_buffer_manager.h
horovod/common/ops/collective_operations.cc
horovod/common/ops/cuda_operations.cc

Changed CUDA operations to claim a copy of the fusion buffer shared pointer to prevent deallocation during finalization

---

README.rst

Add link to ReadTheDocs

---

horovod/_keras/__init__.py
horovod/tensorflow/__init__.py

cc @DEKHTIARJonathan 
Fixes #1315

Add *args to opt.apply_gradients()

---

.buildkite/gen-pipeline.sh
horovod/torch/__init__.py
test/test_torch.py

Resolves an issue with creating an Adam optimizer after setting default tensor type to cuda, which resulted in error "can't convert CUDA tensor to numpy".

Fix optimizer broadcast bug for Adam

---

horovod/run/gloo_run.py

Automatically set the Gloo interface from horovodrun

---

horovod/common/controller.cc
horovod/common/gloo/gloo_context.cc
horovod/common/gloo/gloo_controller.cc
horovod/common/gloo/gloo_controller.h
horovod/common/ops/gloo_operations.cc
horovod/run/common/util/safe_shell_exec.py

Updated Gloo with fixes for context size = 1, fixed issue with overlapping namespaces in local and cross context

---

Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml

Updated nightly torch install to use `--pre` per https://github.com/pytorch/vision/issues/1285

Unpined torchvision and updated nightly torch with new command form

---

horovod/common/gloo/gloo_context.cc
horovod/run/common/util/config_parser.py
horovod/run/common/util/settings.py
horovod/run/gloo_run.py
horovod/run/mpi_run.py
horovod/run/run.py
test/data/config.test.yaml
test/test_run.py

Added args for Gloo timeout and output filename to horovodrun

---

docker-compose.test.yml

See https://github.com/tensorflow/tensorflow/issues/32621

Pin TensorFlow 1.x nightlies

---

horovod/_keras/__init__.py
horovod/common/util.py
test/test_keras.py
test/test_tensorflow_keras.py

Added from_config to Keras DistributedOptimizer for compatibility with clone_and_build_model

---

docs/troubleshooting.rst

I recently got bitten by [this issue](https://github.com/horovod/horovod/issues/1123) and it would be great if it were mentioned somewhere, since it seems likely to cause issues for many people using TF 1.14 and 1.15 from PyPi.
This PR adds a section to troubleshooting.rst that mentions this issue. I would have saved a bunch of time on this had this been there. 
If you prefer to write this somewhere else or in a different manner, feel free to close the PR and do it however is best. I just figured that since I was going to complain about this being "undocumented" on the issue, the least I can do is also make a PR :)

add tf1.4 hwloc issue to troubleshooting.rst

---

Dockerfile.cpu
Dockerfile.gpu
build-docker-images.sh
docs/contributors.rst

Created separate Dockerfiles for CPU and GPU devices, bumped TensorFlow==2.0.0 and PyTorch==1.3.0

---

setup.py

Added optional env variable HOROVOD_CMAKE for setting CMake binary at install

---

docs/benchmarks.rst
docs/docker.rst

Updated docs for Dockerfiles and synthetic benchmarks

---

.buildkite/gen-pipeline.sh
docker-compose.test.yml

Unpin tests for tf-nightly switch to TensorFlow 2.0

---

Dockerfile.test.gpu
docker-compose.test.yml

See: https://github.com/tensorflow/tensorflow/commit/183c4b74a932c281b4f80dba4ab7e005dc154481

Changed nightly framework tests to use CUDA 10.1

---

horovod/common/common.h

Removed Gloo default network interface to fix running in standalone mode

---

horovod/common/util.py

Improved error reporting when Horovod in unable to check if framework support has been built

---

setup.py

See: https://github.com/pytorch/pytorch/commit/bc2e6d10fa7dc73b989ab3e22126867b50fed39c

Fixed compilation for newer versions of PyTorch requiring C++14

---

docker-compose.test.yml

See: https://github.com/tensorflow/tensorflow/issues/35138

Pin tf-nightly to 2.1.0.dev20191203

---

setup.py

Fix non-x86 build #1580 typo

---

.buildkite/gen-pipeline.sh
docker-compose.test.yml

Remove Python 3.5 tests

---

horovod/common/controller.cc
horovod/common/controller.h
horovod/common/tensor_queue.cc
horovod/common/tensor_queue.h

I verified that fusion is happening via logs for both Join and normal case.

Restore fusion functionality broken by #1571

---

horovod/spark/torch/estimator.py
horovod/spark/torch/remote.py

this diff adds seek(0) to the serialized pytorch model after training before loading it with torch.load().

Fixed pytorch model serialization bug

---

horovod/run/run.py
test/test_run.py

Fixed the bug [#1428](https://github.com/horovod/horovod/issues/1428)
cc @apeforest 
Signed-off-by: Karan Jariwala <karankjariwala@gmail.com>

Fixed hostfile bug during horovodrun command

---

Dockerfile.test.cpu
Dockerfile.test.gpu

See: https://github.com/pytorch/vision/issues/1718

Pin Pillow<7.0 to fix torchvision

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Pin torch nightly torch-1.4.0.dev20200106

---

Dockerfile.test.cpu
docs/api.rst

Added horovod.run to docs

---

horovod/common/ops/ddl_operations.cc
setup.py

Transitioning to NCCL backend for the GPU collective communication library.

Deprecate DDL backend

---

horovod/run/mpi_run.py

Added support for OpenRTE variant of Open MPI in horovodrun

---

docs/running.rst

Added requirements for horovodrun

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
docs/contributors.rst
examples/keras_mnist_advanced.py

Added single process tests to test world size == 1

---

horovod/spark/common/store.py
test/test_spark.py

Fixed issue with Estimator store paths not attaching filesystem prefix correctly

---

examples/pytorch_imagenet_resnet50.py

Signed-off-by: Prachi Gupta <pragupta@us.ibm.com>

tensorboardX: catch the exception when tensorboardX isn't installed

---

docs/requirements.txt
horovod/torch/__init__.py
test/test_torch.py

Fixed broadcast_optimizer_state to skip params that do not require grad

---

Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml

MXNet is now publishing nightly to a webpage. Update tests to the correct path.
@karan6181 @eric-haibin-lin please review.

Ping mxnet nightly to the lastest path

---

horovod/mxnet/__init__.py

@apeforest @romerojosh I don't know why this `wait_to_read` was needed. Shall we remove it?

mxnet: Remove unnecessary wait_to_read

---

Dockerfile.test.gpu
examples/pytorch_mnist.py

See https://github.com/pytorch/vision/issues/1938

Patch pytorch_mnist.py until torchvision issue gets resolved

---

horovod/run/run.py

This is difficult to test in unit tests but I have tested it manually.

Add mpi_args to horovod.run.run

---

horovod/spark/torch/estimator.py

Signed-off-by: fardin abdi <fardin@uber.com>

fixed reshaping bug in TorchModel

---

horovod/spark/common/util.py

Signed-off-by: fardin abdi <fardin@uber.com>

fixed data_type_to_str for SparseVector and DenseVector

---

horovod/run/run.py

Aligns HorovodArgs with latest set of horovodrun command line arguments
Wire through elastic arguments to horovod.run API

Run elastic through API

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
examples/keras_spark3_rossmann.py
examples/keras_spark3_rossmann.py.patch
examples/keras_spark_rossmann_estimator.py
examples/keras_spark_rossmann_run.py

This reverts commit 27c7907a8a95da6647f352c5ab12e2e1ffc3bc48.
Fix history following: https://github.community/t5/How-to-use-Git-and-GitHub/Authorship-of-merge-commits-made-by-Github-Apps-changed/td-p/48797

Revert "Run Rossmann examples in CI (#1703)"

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
examples/keras_spark3_rossmann.py
examples/keras_spark3_rossmann.py.patch
examples/keras_spark_rossmann_estimator.py
examples/keras_spark_rossmann_run.py

run Rossmann examples in CI

---

Dockerfile.gpu

Fixes #1791.
See: https://github.com/pypa/wheel/pull/314

Fixed call to get supported tags when building GPU Dockerfile

---

README.rst
docs/index.rst
docs/install.rst
docs/install_include.rst
docs/summary.rst

Added installation guide

---

horovod/common/ops/adasum/adasum.h

Add extra preprocessor guard for FMA optimization

---

horovod/tensorflow/util.py

Hi!
I think early return is better if syntax than if else syntax.
Thank you so much for creating such a wonderful project!

refactoring: early return 'if else' -> 'if'

---

README.rst
docs/install.rst
docs/keras.rst
docs/summary.rst
docs/tensorflow.rst

Updated TensorFlow docs with v1 vs v2 details

---

horovod/run/runner.py
horovod/run/util/cache.py
horovod/spark/common/estimator.py
horovod/spark/keras/bare.py
horovod/spark/keras/optimizer.py

I performed some refactoring.
Horovod is a wonderful project. Thank you.

Some Refactoring

---

test/test_spark.py

Fixed Spark tests depending on timing and timeouts:
- make tests not depend on timeout and timing
- made default value for env argument robust against modifications
- added two more tests

Fix Spark tests flakyness

---

docker-compose.test.yml

See: https://github.com/pytorch/vision/issues/2097

Pin torchvision to ensure compatibility with latest nightly PyTorch

---

setup.py
test/test_run.py

Fixes #1865 
pyupgrade helps in fixing this : https://github.com/asottile/pyupgrade/

Fix deprecation warning regarding invalid escape sequences.

---

horovod/run/util/threads.py
test/test_run.py

Fix recursion in safe_shell_exec introduced earlier

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
docker-compose.test.yml
horovod/common/ops/ccl_operations.cc
test/data/expected_buildkite_pipeline.yaml

Signed-off-by: Yana Shchyokotova <yana.shchyokotova@intel.com>
We noticed that MLSL was excluded from cpu test suit some time ago. Since oneCCL changes was based on current Horovod master branch state, this change remained unnoticed. This PR is intended to fix this.

Add oneCCL to cpu test suite

---

docs/keras.rst
docs/pytorch.rst
docs/tensorflow.rst

Added PyTorch Lightning details to PyTorch docs

---

.buildkite/gen-pipeline.sh
examples/keras_spark3_rossmann.py
examples/keras_spark3_rossmann.py.patch
examples/keras_spark_mnist.py
examples/keras_spark_rossmann_estimator.py
examples/keras_spark_rossmann_run.py
examples/pytorch_spark_mnist.py
horovod/run/common/util/safe_shell_exec.py
horovod/run/gloo_run.py
test/common.py
test/data/expected_buildkite_pipeline.yaml
test/data/run_safe_shell_exec.py
test/data/sleep.py
test/test_run.py

Modified safe_shell_exec to use multiprocess spawning instead of forking to prevent deadlocks

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml
horovod/common/util.py
test/data/expected_buildkite_pipeline.yaml

Fixed multiprocessing for Python 3.8 and added tests for newer Python versions

---

horovod/spark/common/store.py
horovod/spark/common/util.py
horovod/spark/torch/remote.py

Signed-off-by: fardin abdi <fardin@uber.com>

Added metadata cache when fit_on_parquet

---

horovod/_keras/__init__.py
horovod/keras/__init__.py
horovod/tensorflow/keras/__init__.py
test/test_tensorflow_keras.py

Fixed module resolution for tf.keras optimizers and added unit tests

---

CHANGELOG.md

The purpose of this change is to make it easier to generate release notes each version.

Added changelog to track notable user-facing changes each version

---

horovod/run/elastic/registration.py

In Elastic Horovod on Spark the `FAILURE` state can be seen before a `READY` state, because a killed Spark worker will cause a connection failure first leading to a `FAILURE` state, while the training script might still be able to send a `READY` state to the driver. The late `READY` state might arrive before or after the `registration.reset(size)`. In the latter case, the host is already blacklisted. That case is handled here as well:
```
stopping Spark worker 1
starting Spark worker 3 with 1 cores
rsh exit code None for host special-33ed73f864ae297719da2847a0fb43cb slot 0
record state: special-33ed73f864ae297719da2847a0fb43cb[0] = FAILURE
record state: special-a1ba46c36f832f5fd0ef8af250500c9f[0] = READY
all 2 workers recorded
blacklist failing host: …
```

Handle out-of-order state registration

---

.buildkite/gen-pipeline.sh
test/data/expected_buildkite_pipeline.yaml

These three tests haven't been run for 10 months.

Fixing horovodrun test in gen-pipeline.sh

---

.buildkite/gen-pipeline.sh
docker-compose.test.yml
horovod/torch/sync_batch_norm.py
test/data/expected_buildkite_pipeline.yaml

Signed-off-by: Alex Sergeev <alexander.sergeev@live.com>
Fixes Sync Batch Norm for PyTorch 1.5.0.

Fix SyncBatchNorm for 1.5.0

---

horovod/spark/common/store.py

Omit driver param for pyarrow 0.17 and above

---

horovod/run/common/util/tiny_shell_exec.py
horovod/run/js_run.py
horovod/run/mpi_run.py
test/test_run.py
test/test_spark.py

Use env to run mpirun in _get_mpi_implementation

---

horovod/torch/optimizer.py

Signed-off-by: Xavier Lin <syn.xavier.lin+git@gmail.com>
Fix decompression context in DistributedOptimizer.

Fix decompression context in DistributedOptimizer

---

.github/ISSUE_TEMPLATE/bug_report.md

Add Spark version to bug template

---

docker-compose.test.yml

Workaround to address https://github.com/keras-team/keras/issues/14129.

Pin keras to commit 7a39b6c62d43c25472b2c2476bd2a8983ae4f682

---

docker-compose.test.yml

Spark 3 has been released, use released version for testing

---

horovod/run/mpi_run.py
test/test_run.py
test/test_spark.py

Add PYTHONPATH to mpirun env

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Replaced link with LFAI hosted S3 location.
Also pins PyTorch pending #2051.

Fixed file hosting for Spark MNIST dataset

---

horovod/run/elastic/constants.py
horovod/run/elastic/driver.py
horovod/run/elastic/registration.py
horovod/run/elastic/settings.py
horovod/run/gloo_run.py
horovod/run/runner.py
horovod/spark/runner.py
test/integration/elastic_common.py
test/test_elastic_driver.py

Added reset limit for elastic mode to prevent introducing excessive variance

---

docs/adasum_user_guide.rst

Update the headings in the AdaSum guide so that the Horovod TOC renders properly
- [n/a] Did you write any tests to validate this change?  
- [n/a] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?
Fixes the navigation/TOC of https://horovod.readthedocs.io/en/stable/adasum_user_guide_include.html, which currently shows all the sub-headings of the AdaSum guides. 

Update headings in adasum_user_guide.rst

---

README.rst
docs/conda.rst
docs/conda_include.rst
docs/index.rst
docs/install.rst
docs/summary.rst

This PR adds content to the documentation which explain how to create a Conda environment with GPU support for Horovod as discussed in issue #2056.  Feedback would be appreciated!

Add conda env instructions

---

horovod/common/basics.py
horovod/common/operations.cc
horovod/torch/__init__.py
horovod/torch/mpi_ops.py
test/test_torch.py

Fixes #2011 
- Added hvd.is_initialized() method to torch extension

Added hvd.is_initialized() method to torch extension

---

horovod/torch/mpi_ops_v2.cc

During some recent development, I noticed that the existing `WaitAndClear` function used in the PyTorch implementation introduces arbitrary 1 millisecond sleeps. This sleep can occur on any call to synchronize handles for PyTorch ops, adding a lot of additional latency. This can be especially problematic in cases where Horovod ops are included during the forward/backward compute graph (for example, when using sync BN). To remedy this, this PR replaces the sleep with a `pthread_yield()` as suggested by @tgaddair.

Use pthread_yield in torch WaitAndClear function.

---

docker-compose.test.yml

Temporary fix for https://github.com/tensorflow/tensorflow/issues/41388.

Pin tf-nightly to unblock CI

---

test/test_mxnet.py
test/test_torch.py

Fixed PyTorch and MXNet tests to correctly compare tensor elements

---

examples/keras_spark_rossmann_estimator.py
horovod/keras/callbacks.py
horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/tensorflow/keras/callbacks.py
test/test_spark_keras.py

Enable keras estimator to accept modelCheckPoint callback

---

horovod/_keras/__init__.py

This PR addresses compatibility with changes in https://github.com/tensorflow/tensorflow/commit/0e529eb70debc7224b83d1b654f22324cd1a7d53:
- `_aggregate_gradients` now returns a list of `(grad, var)` tuples.
- Gradient aggregation now occurs in the `apply_gradients` method.
cc @omalleyt12 @reedwm @DEKHTIARJonathan

Fixed gradient aggregation for Keras API changes in TensorFlow 2.4.0

---

horovod/runner/__init__.py
horovod/runner/common/util/settings.py
horovod/runner/driver/driver_service.py
horovod/runner/gloo_run.py
horovod/runner/launch.py
horovod/runner/mpi_run.py
horovod/runner/util/lsf.py
horovod/runner/util/remote.py

Also consolidates SSH args into a common API.
cc @richardliaw

Added ssh_identity_file argument to horovodrun

---

horovod/runner/gloo_run.py

Fixed bug with adding SSH to the Gloo worker command

---

CHANGELOG.md
CONTRIBUTING.md
docs/ray.rst

- Changelog updates for v0.20 release
- Updated members of Technical Steering Committee
- Updated Ray documentation

Changelog and TSC updates

---

CMakeLists.txt
setup.py

Set CMake python from sys.executable in setup.py

---

examples/tensorflow2_keras_synthetic_benchmark.py

For completeness you might also want to have the tf.keras version of the synth benchmark.
This script produces the same logs as examples/tensorflow2_synthetic_benchmark.py

synthetic benchmark for tf.keras

---

examples/tensorflow2_mnist_ray.py

Remove keras requirement from Ray example

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml
setup.py
test/data/expected_buildkite_pipeline.yaml

Moves Spark dependencies to latest 2.4 and 3.0 releases (released last week).

Move Spark dependencies to latest releases

---

horovod/common/ops/nccl_operations.cc

Skip launching zero-sized send/recvs for NCCLAlltoall.

---

.github/workflows/buildkite_unit_tests_branch.yml
.github/workflows/buildkite_unit_tests_master.yml

Earlier PR #2286 did not work, this one is promising. Work towards #2287.

Always test master (part 2)

---

horovod/tensorflow/__init__.py

Fixes bug introduced in #1949. Early override of `op=Average` to `op=Sum` when using the ROCm path would lead to skipping the average in the TF IndexedSlices case here:
```       
new_values = (values / horovod_size) if op == Average else values
````
Solution is to move override into non-IndexedSlices path.

Fix allreduce averaging for TF IndexedSlices in ROCm path.

---

horovod/mxnet/cuda_util.cc

Include stdexcept to handle certain compiler / frameworks that don't include it already

---

horovod/spark/common/store.py
horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/tensorflow/keras/callbacks.py
test/test_spark.py

This issue is introduced by #2234 .
Add custom scope when loading the saved model on the worker.

Fix model loading: use custom scope

---

horovod/tensorflow/mpi_ops.cc
horovod/tensorflow/mpi_ops.py

Currently for TensorFlow, Horovod will use the op node name from TensorFlow to match up collective requests. In model parallel scenarios, it is possible that tensors will be produced from graphs that are constructed differently across workers, leading to inconsistent op names, and mismatched collectives. While there is the option to assign a custom `name` to an op, this does not fully get around this issue as the TF op node name can still include an outer name scope that is prepended to the custom name (e.g. you can get collectives named `graph1/my_custom_name` and `graph2/my_custom_name`, where the `graph*/` scope is applied by TF and currently cannot be removed by the user).
This PR introduces an optional `ignore_name_scope` option to Horovod ops in TF, which will strip the outer name …

Add option to strip outer name scope from Horovod ops in TF.

---

docs/mocks.py
docs/ray.rst
horovod/ray/runner.py
test/single/test_ray.py
test/single/test_ray_elastic.py

- [n] Did you update the docs?
Ray master recently did some refactoring.

[ray] fix for ray master (ray.services)

---

horovod/torch/cuda_util.cc
horovod/torch/ready_event.cc

Signed-off-by: Joseph C Wang <joequant@gmail.com>
- [X ] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
Fixes #2336

add stdexcept

---

.github/workflows/buildkite_unit_tests.yml

Further:
- ignores cancelled builds
- ignores timed out jobs
Completes #2333

Runs unit test workflow for pull requests from fork repositories

---

docs/benchmarks.rst

Fixed broken links of imagenet TFRecord preprocessing script and Tensorflow v1, Tensorflow v2 and PyTorch synthetic benchmarks

Fix broken links in benchmarks.rst

---

horovod/spark/common/store.py
horovod/spark/common/util.py
test/integration/test_spark.py

This PR allows `Store.create()` to create `DBFSLocalStore` when both of the following conditions are met:
* The code is running in Databricks Runtime
* The `prefix_path` matches any of the following patterns:
* `/dbfs/...`
* `file:///dbfs/...`
* `dbfs:/...`

Support Store.create("dbfs:/") mapping to DBFSLocalStore("/dbfs/...")

---

Dockerfile.test.gpu
docker-compose.test.yml

Latest tf-nightly is failing with the following:
```
Mon Oct 19 12:56:16 2020[1]<stdout>:test_tensorflow2_keras.py:225:
Mon Oct 19 12:56:16 2020[1]<stdout>:_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/horovod-0.20.3-py3.7-macosx-10.15-x86_64.egg/horovod/_keras/__init__.py:104: in apply_gradients
Mon Oct 19 12:56:16 2020[1]<stdout>:    **kwargs,
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/horovod-0.20.3-py3.7-macosx-10.15-x86_64.egg/horovod/tensorflow/gradient_aggregation_eager.py:146: in apply_gradients
Mon Oct 19 12:56:16 2020[1]<stdout>:    false_fn=non_aggregation_step,
Mon Oct 19 12:56:16 …
```

Pin tf-nightly

---

docker-compose.test.yml

See: https://github.com/keras-team/keras/pull/14256

Fixed keras nightly after Keras team deprecated original repo

---

docs/docker.rst

Added docs for running containers with different ports

---

horovod/runner/__init__.py
horovod/runner/common/util/config_parser.py
horovod/runner/common/util/safe_shell_exec.py
horovod/runner/common/util/settings.py
horovod/runner/gloo_run.py
horovod/runner/launch.py
horovod/runner/mpi_run.py
test/single/test_run.py

Fixed --log-hide-timestamp to apply to driver logs with Gloo

---

docs/spark.rst

Update docs for PR #2376

---

Dockerfile.test.cpu
Dockerfile.test.gpu
setup.py
test/parallel/test_tensorflow_keras.py

See: https://github.com/h5py/h5py/issues/1732

Pin h5py < 3 to fix incompatibility with TensorFlow model serialization

---

horovod/runner/common/util/safe_shell_exec.py
test/single/test_run.py

Fix shell unicode decode error

---

horovod/common/operations.cc
horovod/common/timeline.cc
horovod/common/timeline.h
test/parallel/test_torch.py

Signed-off-by: Vikas Kumar <vikumar@amazon.com>

fix for dynamic timeline race

---

test/single/test_ray.py

Disable flaky checks in Ray colocator test

---

horovod/spark/torch/remote.py

This change allows the Torch Model to output a named tuple which is necessary for multi-output torch models and Neuropod.

checking output type with ininstance

---

horovod/spark/torch/estimator.py
horovod/spark/torch/util.py

Torch Script Models can be used with TorchModel object 

---

horovod/spark/keras/remote.py

Signed-off-by: Fardin Abdi <fardin@uber.com>
After a recent change, `LearningRateScheduleCallback` class requires the initial learning rate to be provided at the instantiation time. This is the learning rate after being scaled according to the number of workers. This PR sets the lr inside the KerasEstimator for the callbacks of type `LearningRateScheduleCallback`.

updated inital_lr in the keras estimator

---

horovod/common/ops/nccl_operations.cc

Apply according to @romerojosh 's [suggestion](https://github.com/horovod/horovod/pull/2498#discussion_r535452791) in #2498 .

Add breaking for outer loop in NCCLAllgather

---

horovod/spark/common/params.py
horovod/spark/keras/remote.py
horovod/spark/keras/util.py
horovod/spark/torch/remote.py

- [] Did you write any tests to validate this change?  
- [] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?
This change add option to use customized val_batch_size for validation. If val_batch_size is not provided, will behave like before (using batch_size)

Add validation batch size

---

horovod/spark/keras/estimator.py
horovod/spark/torch/estimator.py

Estimator is not able to take val_batch_size which is available in the horovod.

estimator support val_batch_size

---

horovod/common/ops/gpu_operations.cc

Disable cudaGetLastError check to fix multi-container same host

---

CHANGELOG.md
horovod/ray/runner.py
test/single/test_ray.py

Executable class for Ray wasn't working properly (needed for ludwig).

[ray] fix executable cls

---

.github/workflows/buildkite_unit_tests.yml

Uses pre-built actions to avoid re-building the action for every workflow run, and to always use the identical action build.

Use pre-built actions

---

horovod/runner/__init__.py
horovod/runner/common/util/config_parser.py
horovod/runner/launch.py
test/single/data/config.test.yaml
test/single/test_run.py

Signed-off-by: Yana Shchyokotova <yana.shchyokotova@intel.com>
- [ yes ] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ no need ] Did you update the docs?
- [ no need ] Did you write any tests to validate this change?  
- [ no need ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?
There were old names like HOROVOD_CCL_BGT_AFFINITY / ccl_bgt_affinity left in the code that previously had been changed to HOROVOD_THREAD_AFFINITY

change ccl_bgt_affinity artifacts to thread_affinity

---

CHANGELOG.md
horovod/ray/runner.py
test/single/test_ray.py

[ray] update test, add blocking calls

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Reverts horovod/horovod#2530
See https://github.com/apache/incubator-mxnet/issues/19690

Revert "Pin mxnet-nightly following missing file oneapi/dnnl/dnnl_config.h"

---

CHANGELOG.md
test/single/test_ray.py

Fixes https://github.com/horovod/horovod/issues/2438

[ray] disable flaky check

---

Dockerfile.test.cpu
Dockerfile.test.gpu

This increase chances to reuse cached layers of downloaded packages and data.

Copy horovod sources later in Dockerfile

---

test/integration/test_spark_torch.py

test: add in-memory-cache-all option for spark_torch_estimator

---

CHANGELOG.md
horovod/tensorflow/keras/__init__.py

Fix Wrong default for horovod.tensorflow.keras.allreduce average

---

CHANGELOG.md
horovod/ray/runner.py
test/single/test_ray.py

Enables async execution with Ray + Pytorch Lightning + Horovod (https://github.com/ray-project/ray_lightning_accelerators)
cc @amogkam 

[ray] provide a remote execution call

---

.buildkite/gen-pipeline.sh
docker-compose.test.yml
test/single/data/expected_buildkite_pipeline.yaml

There was no released mxnet-1.7 that worked with Horovod (MKLDNN headers missing). Now there is a [new release](https://github.com/apache/incubator-mxnet/issues/19575).

Upgrade mxnet-1.7 to latest release

---

test/parallel/test_mxnet.py

Cleanup MXNet broadcast tests a bit
- `test_horovod_broadcast` accidentally missed the `test` prefix, so probably was not run
- `test_horovod_broadcast_parameters` had a misleading name `test_horovod_broadcast_grad`
- some logging counters were off

Cleanup MXNet broadcast tests a bit

---

horovod/_keras/callbacks.py

print learning rate only for 0th rank since lr is same across all ranks

Dedup Keras LearningRateWarmupCallback log after gradual learning rate warmup

---

test/parallel/test_torch.py

Remove stall in TorchTests.test_horovod_join_broadcast when running four processes (fixes #2662)

---

horovod/torch/functions.py
horovod/torch/mpi_ops.py

Update sparse torch pr

---

horovod/spark/torch/remote.py

Fixes #2680
this line
if sample_weights:
should change to
if sample_weights is not None:
otherwise it complains about
RuntimeError: bool value of Tensor with more than one value is ambiguous.

Fix bug in checking sample_weights, #2680

---

examples/elastic/tensorflow2/tensorflow2_keras_mnist_elastic.py

example: add tensorflow2/keras elastic version of mnist

---

horovod/tensorflow/mpi_ops.py
horovod/torch/mpi_ops.py
test/parallel/test_tensorflow.py
test/parallel/test_torch.py

The original code was broken because _allreduce() does Sum by default.

Fix gradients for allgather() and broadcast() (#2654).

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
examples/elastic/pytorch/pytorch_mnist_elastic.py
examples/pytorch/pytorch_mnist.py
examples/ray/basic_ray_elastic.py
examples/ray/pytorch_ray_elastic.py
test/single/data/expected_buildkite_pipeline.yaml

See https://github.com/pytorch/vision/issues/3500

Fixed PyTorch MNIST dataset

---

.buildkite/gen-pipeline.sh
.readthedocs.yaml
docs/requirements.txt
test/single/data/expected_buildkite_pipeline.yaml
test/single/test_buildkite.py

Added .readthedocs.yaml

---

horovod/torch/optimizer.py
test/parallel/test_torch.py

Fixed issue initializing DistributedOptimizer with multiple param groups

---

horovod/spark/keras/util.py

spark/keras: add missing arg shuffle for barekeras dataset

---

docs/contributors.rst

It wasn't obvious to me how to build Horovod in debug mode from setup.py. Probably a short example command line could be helpful to more people.

Docs: Explain how to achieve a debug build

---

README.rst

The link to demo is old. Let's just use the link to the MPI Operator repo that contains the examples and instructions instead.

Update link to Kubeflow MPI Operator

---

horovod/torch/optimizer.py

When use group in DistributedOptimizer of pytorch, `self._group_counts[group]` will not be reset to 0 if params in one group don't all arrive. This PR resets `self._group_counts[group]` to 0 when synchronize is called.

reset self._group_counts when synchronize

---

README.rst

Add Horovod on TonY link

---

horovod/tensorflow/gradient_aggregation.py
test/parallel/test_tensorflow.py

Fixed global_step assign_add ordering during TF gradient aggregation.  Includes a test which fails without the fix.
Fixes #2715 (issue).

Fixed global_step assign_add ordering during TF gradient aggregation

---

.buildkite/gen-pipeline.sh
Dockerfile.cpu
Dockerfile.gpu
Dockerfile.test.cpu
Dockerfile.test.gpu
test/single/data/expected_buildkite_pipeline.yaml

Build and test time can be reduced for some Spark specific cases.

Reduce spark build test time

---

horovod/common/controller.cc
horovod/common/response_cache.cc

Signed-off-by: Agoniii <815244047@qq.com>
Add response_cache for Allgather

add allgather cache

---

README.rst
docs/summary.rst

Bring README.rst and docs/summary.rst back in sync

---

docs/running.rst

Signed-off-by: Ryan <rb@determined.ai>
Fix broken links to MPI doc.

Fix doc links.

---

examples/mxnet/mxnet_imagenet_resnet50.py
examples/mxnet/mxnet_mnist.py
horovod/mxnet/__init__.py
horovod/mxnet/compression.py
test/parallel/test_mxnet.py

The previous pr https://github.com/horovod/horovod/pull/1908 is not finished, I have improved it on the basis of it

FP16 support for GPU tensors in mxnet

---

examples/pytorch/pytorch_lightning_mnist.py
examples/spark/pytorch/pytorch_lightning_spark_mnist.py
horovod/spark/lightning/estimator.py
horovod/spark/lightning/remote.py
test/integration/test_spark_lightning.py

Wire in the call back function for lightning estimator.

Add callback to lightning trainer

---

horovod/spark/torch/remote.py

TorchEstimator: fix typo

---

.github/workflows/docker.yml

Spin up multiple EC2 instances to build docker images in parallel:

Spin up multiple EC2 instances to build docker images

---

CHANGELOG.md
horovod/spark/lightning/estimator.py
horovod/spark/lightning/remote.py

Enable supplying logger to lightning trainer to enable comet integration

---

docker-compose.test.yml
horovod/tensorflow/mpi_ops.cc

Removed reference to PersistentBuffer from TensorFlow ops

---

horovod/spark/common/store.py
horovod/spark/keras/remote.py
horovod/spark/lightning/remote.py
horovod/spark/torch/remote.py
test/integration/test_spark.py

Hi @tgaddair, added storage_options parameter to fsspec branch . Tested with TorchEstimator & ADLS. Please check and let me know if something needs to be done, to take this to closure.

added storage_options to FilesystemStore

---

docs/docker.rst

Updated Docker docs for new images

---

.gitignore
examples/spark/pytorch/pytorch_lightning_spark_mnist.py
examples/spark/pytorch/pytorch_lightning_spark_mnist_legacy.py
examples/spark/pytorch/pytorch_spark_mnist.py
horovod/spark/common/util.py
horovod/spark/data_loaders/pytorch_data_loaders.py
horovod/spark/lightning/estimator.py
horovod/spark/lightning/legacy.py
horovod/spark/lightning/remote.py
test/integration/test_spark_lightning.py

fix store, and add infinite loader

---

horovod/spark/keras/estimator.py

Signed-off-by: Rich Porter <rich.porter@uber.com>

Make Keras backend env configurable

---

horovod/spark/keras/util.py

From https://www.tensorflow.org/guide/data_performance#prefetching, this
is suggested for training speed improvement.

Estimator: prefetch next batch for keras dataset

---

horovod/_keras/__init__.py

Move parent __init__ call earlier when constructing Keras DistributedOptimizer

---

examples/mxnet/mxnet_imagenet_resnet50.py
examples/mxnet/mxnet_mnist.py
horovod/mxnet/__init__.py
horovod/mxnet/compression.py
test/parallel/test_mxnet.py

Try to solve the problem mentioned in https://github.com/horovod/horovod/pull/2915
Thank you for your time on reviewing this pr.
cc @romerojosh @tgaddair

FP16 compression for MXNet

---

horovod/common/elastic.py

This is a PR from JIZHI Team & TaiJi AI platform in Tencent.
Fixes #2995 .

catch exception for state.sync in elastic horovod.

---

docs/contributors.rst

Update documentation on running tests

---

horovod/keras/__init__.py
horovod/tensorflow/keras/__init__.py

Include hvd.cross_rank for keras

---

Dockerfile.test.cpu
Dockerfile.test.gpu

See: https://github.com/pytorch/vision/issues/4146

Pin pillow!=8.3.0 for nightly torchvision

---

.github/gen-workflow-ci.py
.github/workflows/ci-fork.yaml
.github/workflows/ci.yaml

CI Fork workflow does not look at the right fork information. Further, deriving the conclusion of the triggering CI workflow was faulty.

Fix fork conditions

---

horovod/spark/data_loaders/pytorch_data_loaders.py
horovod/spark/lightning/remote.py
test/integration/test_spark_lightning.py

LightningEstimator: add support for in memory dateloader

---

Dockerfile.test.gpu

This completes #3034 as we also need to pin GPU nightly package.

Pin MXNet gpu to 2.0.0b20210620  as well

---

.github/workflows/ci-fork.yaml

- Fork CI signals failed Buildkite jobs
- Publish job should always run
- Fix not building docker images when there not tests were run
- Fix not downloading from buildkite when we skipped triggering buildkite build
- Fix triggering Buildkite build on the right branch

More Fork CI fixes

---

horovod/runner/gloo_run.py
test/integration/test_interactiverun.py

Previously, the following `train.py` script:
```python
import time
import horovod.tensorflow as hvd
if __name__ == "__main__":
hvd.init()
print('hi!', hvd.rank())
time.sleep(1)
if hvd.rank() == 2:
raise RuntimeError("worker absolutely refuses to be rank 2")
time.sleep(120)
print('exiting normally after 2 minutes')
```
when invoked like this:
```
horovodrun -np 4 -H localhost:4 python test.py
```
Would result in an output like this:
```
[0]<stdout>:hi! 0
[3]<stdout>:hi! 3
[1]<stdout>:hi! 1
[2]<stdout>:hi! 2
[2]<stderr>:Traceback (most recent call last):
[2]<stderr>:  File "/home/rb/code/horovod/meh/test.py", line 11, in <module>
[2]<stderr>:    raise RuntimeError("worker absolutely refuses to be rank 2")
[2]<stderr>:RuntimeError: worker absolutely refuses to be rank 2
Process 2 exit with …
```

launch_gloo() kills all workers if any exit non-zero.

---

horovod/mxnet/__init__.py

Adds `process_set` support to MXNet `DistributedTrainer`. Also fixes the use of `size()` rather than `process_set.size()` when setting the rescale grad argument for averaging in `DistributedOptimizer`.

Add process_set support to Gluon DistributedTrainer.

---

horovod/runner/elastic/registration.py

[ELASTIC HOROVOD]Fix the problem that _record_state called when _action is running(#3014).

---

README.rst
docs/concepts.rst
docs/index.rst
docs/process_set.rst
docs/process_set_include.rst
docs/summary.rst

This mentions the `hvd.alltoall` op and this adds some basic documentation for the process set features introduced in #2839 and its follow-up PRs.
Probably this could use some proofreading and editing!

Add some documentation for Alltoall and Process Sets

---

CHANGELOG.md
docs/spark.rst
horovod/spark/data_loaders/pytorch_data_loaders.py
horovod/spark/lightning/datamodule.py
horovod/spark/lightning/estimator.py
horovod/spark/lightning/remote.py
setup.py
test/integration/test_spark_lightning.py

Using context manager is likely to stop reader earlier than async
dataloader worker thread. This would rise a runtime error in petastorm.
Fixes #3082 .

Estimator/Lightning: use lightning datamodule

---

examples/spark/pytorch/pytorch_lightning_spark_mnist.py
horovod/spark/lightning/estimator.py
horovod/spark/lightning/remote.py
test/integration/test_spark_lightning.py

- [-] Did you write any tests to validate this change?  
- [-] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?
Allows user to pass in PyTorch Lightning profiler to the PL estimator

Add lightning profiler

---

horovod/torch/mpi_ops.py

Signed-off-by: guoze.lin <guozelin@tencent.com>
This is a PR from JIZHI Team & TaiJi AI platform in Tencent.
Fixes #3109.

fix torch op handles lazy release which may cause oom in elastic scenario

---

docs/mocks.py
horovod/spark/common/store.py

Enable extraction of storage_options from url.
Fixes #3057

Added support for extraction of storage options from url.

---

test/parallel/test_tensorflow2_keras.py

There were no tests for MetricAverageCallback, LearningRateScheduleCallback and LearningRateWarmupCallback from
hvd as noted in #2659. This PR adds testing to verify the callback works.

Add tests for Keras callbacks: MetricAverageCallback, LearningRateScheduleCallback and LearningRateWarmupCallback

---

examples/spark/keras/keras_spark_mnist.py
horovod/spark/keras/remote.py

- [n/a] Did you update the docs?
- [manual] Did you write any tests to validate this change?  
- [n/a] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?
Enables Keras users to customize the Tensorboard callback.  One use of this is to pass in a range of batches.

Allow caller to customize the Tensorboard callback

---

horovod/spark/lightning/remote.py

The Experiment key in comet logger is lost when serialize-deserialize from CPU to GPU in lightning extimator. 
Need to remember the key, and resume it from GPU side.

Fix Cometlogger experiment key lost issue

---

horovod/runner/mpi_run.py
test/integration/test_static_run.py

Fixes #1637.
I notice horovod's MPICH implementation is broken (#1637) but Intel MPI implementation is good (#2374). Per [Intel MPI's official page](https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/mpi-library.html), it implements the MPICH specification (in fact it's MPICH derivative), so we can safely use Intel MPI's implementation for MPICH.

fix MPICH implementation

---

test/parallel/test_tensorflow2_keras.py

This fixes issue #2664 by performing gradient aggregation with a real gradient instead of a constant.
- [ X] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ X] Did you update the docs?
- [X ] Did you write any tests to validate this change?  
- [ X] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?
PR #2647 shifts the gradient allreduce when the gradient is computed (both through the DistributedOptimizer or through the DistributedGradientTape). Which means that this unittest, by design in TF2.4, doesn't call allreduce in _aggregate_gradients().
Since this unittest provide a gradient as constant (without effectively computing it), the gradient will never be …

test_gradient_aggregation with real gradient instead of a constant

---

horovod/spark/common/util.py
test/utils/spark_common.py

See discussion here for context: https://github.com/horovod/horovod/pull/3255#issuecomment-963140981

Revert "Fix Horovod pyarrow IndexError: list index out of range (#3255)"

---

horovod/data/data_loader_base.py
horovod/spark/lightning/datamodule.py
horovod/spark/lightning/estimator.py
horovod/spark/lightning/remote.py

- Adding debugging logs to lightning data loader.
- skip adding path if profiler is 'simple'
- Make async queue size customizable.

Debugging for lightning data loader and fix for simple profiler.

---

.github/workflows/ci-results.yaml

Of course, #3271 did not work, this is how you do it correctly.

Fix check status name and details link attempt 2

---

.github/workflows/ci-results.yaml

Environment variables are only substituted in " not '. Fixes #3273.

Fix check status name attempt 3

---

horovod/common/basics.py
test/parallel/test_mxnet2.py
test/parallel/test_torch.py

Signed-off-by: TJ <tix@uber.com>
Torch head unit tests are failing due to deprecation of getargspec in inspect package. Replace it with inspect.signature.

Try to fix unit test failures for torch head

---

.buildkite/gen-pipeline.sh
.github/workflows/ci.yaml
docker-compose.test.yml
test/single/data/expected_buildkite_gpu_heads_pipeline.yaml
test/single/data/expected_buildkite_gpu_non_heads_pipeline.yaml

Spark 3.2.0 has been released, adding to test space while removing 3.0.3.

Add Spark 3.2.0 to test space, remove 3.0.3

---

README.rst
docs/install.rst
docs/mocks.py
docs/summary.rst

Some people make futile attempts to build Horovod on their Windows systems and seek help about it, e.g., #3373.

Docs: Clarify that Windows is not supported; fix Sphinx build

---

.buildkite/gen-pipeline.sh
test/single/data/expected_buildkite_gpu_heads_pipeline.yaml
test/single/data/expected_buildkite_gpu_non_heads_pipeline.yaml

This uses new images for our buildkite EC2 instances.

Move buildkite agents to v5.7.2

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml

This allows us to run the CI on any branch without a PR.

Allow to run CI manually on any branch

---

docker/horovod-cpu/Dockerfile
docker/horovod-ray/Dockerfile
docker/horovod/Dockerfile

Similar to #3338, this time for released docker images.

Make docker fail on first failing command in RUN (part 2)

---

CHANGELOG.md
horovod/__init__.py

This is a cherry-pick from the `hotfix-0242` branch.

Bump version to 0.24.2

---

horovod/tensorflow/mpi_ops.cc

The function has been renamed for TF 2.9-rc0: https://github.com/tensorflow/tensorflow/commit/51950258ea4cd5a6e50b926db7efee30358c1ce8

Fix for TF 2.9 API change: tensorflow_accelerator_device_info

---

CHANGELOG.md
examples/spark/keras/keras_spark_mnist.py
horovod/spark/common/params.py
horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/spark/keras/util.py
horovod/spark/lightning/estimator.py
horovod/spark/lightning/remote.py
horovod/spark/torch/estimator.py
horovod/spark/torch/remote.py
test/integration/test_spark_keras.py
test/integration/test_spark_lightning.py
test/integration/test_spark_torch.py

For model training reproducibility.

[Spark]: expose random seed as an optional parameter

---

.github/gen-workflow-ci.py
.github/workflows/ci-results.yaml
.github/workflows/ci.yaml
.github/workflows/upload-pypi.yml

Restrict Github Action permissions in our workflows. Supersedes #3523.

Restrict Github Actions permissions

---

.github/gen-workflow-ci.py
.github/workflows/ci-results.yaml
.github/workflows/ci.yaml

Fix typo in permissions. fix buildkite download action

---

.buildkite/get_changed_code_files.py
.github/get-changed-code-files.py
README.rst
docker/README.md
docker/helm/Chart.yaml
docker/helm/README.md
docker/helm/templates/NOTES.txt
docker/helm/templates/_helpers.tpl
docker/helm/templates/config.yaml
docker/helm/templates/job-service.yaml
docker/helm/templates/job.yaml
docker/helm/templates/secrets.yaml
docker/helm/templates/statefulset-service.yaml
docker/helm/templates/statefulset.yaml
docker/helm/values.yaml
docs/summary.rst

Adds Helm chart to `docker/helm`. These were copied from https://github.com/helm/charts/commit/41312e665542de109088139ac64f695031d2bd11 and updated.

Add Helm Chart

---

CHANGELOG.md
horovod/__init__.py

Bump version to 0.25.0

---

test/integration/test_spark_lightning.py

Add missing return value of validation_step().

test: fix XOR model in test_spark_lightning.py

---

horovod/torch/CMakeLists.txt

Fixes #3537. There was an upstream change in hipify_python that requires absolute paths to be passed to hipify. The proposed changed also works with the older version of hipify_python.

[ROCm] Fix call to hipify

---

test/integration/test_spark.py

Test: increase flaky spark test timeout

---

horovod/common/controller.cc

Signed-off-by: Rohit Santhanam <rohit.santhanam@amd.com>
Fix ROCm specific build failure.
/cc @maxhgerlach

[ROCm] Fix build failure.

---

.buildkite/gen-pipeline.sh
.github/workflows/ci.yaml
docker-compose.test.yml
test/single/data/expected_buildkite_gpu_heads_pipeline.yaml
test/single/data/expected_buildkite_gpu_non_heads_pipeline.yaml

Test head versions not only with Gloo but also with MPI.
Once #3557 is (fixed and) merged, this can be merged as well.

Test heads and mins with MPI

---

.github/workflows/codeql-analysis.yml

Configures the same concurrency for CodeQL workflow as we have for CI workflow.

Configure concurrency of CodeQL workflow

---

Dockerfile.test.cpu
Dockerfile.test.gpu
docker/horovod-cpu/Dockerfile
docker/horovod/Dockerfile
docs/troubleshooting.rst
test/parallel/test_tensorflow.py

Update test containers to use a newer OpenMPI version (4.1.4).

Bump test OpenMPI version to 4.1.4.

---

docker/horovod-nvtabular/Dockerfile

Signed-off-by: Lee Yang <leewyang@gmail.com>
Fixes #3691.

restrict protobuf version

---

.buildkite/gen-pipeline.sh
.github/workflows/ci.yaml
horovod/tensorflow/mpi_ops.cc
test/single/data/expected_buildkite_gpu_heads_pipeline.yaml

This should fix build failures with TF nightly caused by [2be83013 (tensorflow)](https://github.com/tensorflow/tensorflow/commit/2be830137aca09da21d599e04ba7d7ad0059ed05).
https://github.com/tensorflow/tensorflow/issues/57494

Header stream.h moved in tensorflow

---

.github/workflows/codeql-analysis.yml

CodeQL action v1 will be deprecated soon. Also upgrades checkout and setup-python actions in codeql workflow.

Upgrade codeql, checkout and setup-python actions

---

docs/keras.rst
docs/tensorflow.rst
horovod/_keras/__init__.py
horovod/tensorflow/__init__.py
horovod/tensorflow/gradient_aggregation.py
horovod/tensorflow/gradient_aggregation_eager.py
horovod/tensorflow/keras/__init__.py
test/parallel/test_tensorflow.py
test/parallel/test_tensorflow2_keras.py

This PR is a followup to #3695 and the discussion made [here](https://github.com/horovod/horovod/discussions/3705) to scale down the gradients of local variables in partial distributed gradient tape, distributed optimizer, and the local gradient aggregators.
#3705

TensorFlow: scale the gradients of local variables 

---

.buildkite/gen-pipeline.sh
.github/workflows/ci.yaml

This particular test uses Gloo though MPI is to be tested.

MXNet MPI api test should really run MPI

---

CHANGELOG.md
horovod/__init__.py

This is a hotfix release fixing broken 0.26.0. Fixes #3744.

Bum version to 0.26.1

---

CHANGELOG.md

Updates to the changelog found during release.

Update CHANGELOG.md from release

---

GOVERNANCE.md

Signed-off-by: TJ <tjx@nvidia.com>
Update TJ's employer in governance

Update TJ's employer in governance

---

horovod/tensorflow/mpi_ops.cc

- [] Did you update the docs? N/A

Update usage of TensorFlow Status

---

.github/gen-workflow-ci.py
.github/workflows/ci-results.yaml
.github/workflows/ci.yaml

Upgrades GHA in CI to latest major versions.

Upgrade GHA versions, fix publish-test-results warning

---

docker-compose.test.yml
horovod/_keras/__init__.py
horovod/keras/__init__.py
horovod/tensorflow/keras/__init__.py
horovod/tensorflow/sync_batch_norm.py

Signed-off-by: TJ <tjx@nvidia.com>
Add kwargs to support addition parameters added by keras.layers.batchnormalization.

Add kwargs to _moments to support additional Keras parameters

---

test/parallel/test_tensorflow2_keras.py
test/parallel/test_tensorflow_keras.py

Keras tests: Fix optimizer import for recent nightly

---

Dockerfile.test.cpu
Dockerfile.test.gpu
docker/horovod-cpu/Dockerfile
docker/horovod-nvtabular/Dockerfile
docker/horovod/Dockerfile

Docker: Restrict numpy<1.24.0 for pandas<1.1.0, h5py<3.0, mxnet

---

docker/horovod-nvtabular/Dockerfile
docs/spark.rst

Signed-off-by: Lee Yang <leewyang@gmail.com>
Fixes #3797

replace conda w/ pip install for horovod-nvtabular docker image

---

Dockerfile.test.gpu
assert-package-versions.sh
docker-compose.test.yml
docker/horovod-nvtabular/Dockerfile

Replace package tf-nightly-gpu by tf-nightly

---

horovod/tensorflow/__init__.py
horovod/tensorflow/gradient_aggregation.py

Resolve conflicts between multiple hvd distribution wrappers reusing the same gradient accumulation counter

TF: Resolve conflicts between multiple optimizer wrappers reusing the same gradient accumulation counter

---

CHANGELOG.md
horovod/__init__.py

Releasing v0.27.0.
I aimed to add all user-facing changes to the changelog, roughly in commit order. Please have a look if it looks right.

Bump version to 0.27.0

---

.github/pull_request_template.md

`CONTRIBUTING.md` -> `GOVERNANCE.md`

Update TSC link in PR template

---

CHANGELOG.md
horovod/common/operations.cc

I missed a typo there that only affects builds with ROCm.
Fixes #3838.

Fix ROCm build for recent Reducescatter changes

---

docker/horovod-nvtabular/Dockerfile

Update extra-index-url for nvidia pypi to fix horovod-nvtabular Docker build 

---

Dockerfile.test.cpu
Dockerfile.test.gpu
test/single/test_ray.py

Ray version for CPU is fixed to 1.7.0, for GPU even 1.3.0, released docker images ship latest version 2.2.0.
Moving CI to latest ray release.

Upgrade ray to latest version

---

docker-compose.test.yml

https://github.com/horovod/horovod/pull/3864#issuecomment-1472544769:
> After yesterday's PyTorch release we pick up `torch==2.0.0` now, rather than a nightly/dev version, which blocks the CI:
> 
> ```
> 2023-03-16T17:52:42.3497842Z #44 [39/51] RUN /horovod/assert-package-versions.sh
> 2023-03-16T17:52:42.3498192Z #44 sha256:94c0c4138de63c79ca985f9905edc3b9f598aa742087af4998fd87a12805d32f
> 2023-03-16T17:52:43.1000727Z #44 0.739 tf-nightly==2.13.0.dev20230316 [32mfound[0m (matches tf-nightly / tf-nightly==.*\.dev20\d{6})
> 2023-03-16T17:52:44.0024362Z #44 1.680 torch==2.0.0 [31mfound BUT[0m torch-nightly-cu116 / torch==.*\.dev20\d{6}.* [31mexpected[0m
> 2023-03-16T17:52:44.4534918Z #44 2.151 pytorch-lightning==1.5.9 [32mfound[0m
> 2023-03-16T17:52:45.3372508Z #44 3.095 …
```

Move torch-nightly to cu118 from cu116

---

horovod/_keras/__init__.py
horovod/spark/keras/tensorflow.py
horovod/tensorflow/xla_mpi_ops.cc
test/parallel/test_tensorflow.py

Let's collect more fixes for TensorFlow nightly builds here.

Further fixes and updates for tf-head

---

test/integration/test_static_run.py

test: fix failcase exit code requirements

---

horovod/keras/__init__.py

Fixes the keras.all_reduce function with missing positional arguments.

Fix keras allreduce function

---

horovod/_keras/__init__.py

Fix missing Keras variables shim

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml
.github/workflows/codeql-analysis.yml
.readthedocs.yaml

Supposed to work around https://github.com/docker/docker-py/issues/3113 and https://github.com/readthedocs/readthedocs.org/issues/10290

CI: Pin requests<2.29.2 for docker-compose, update readthedocs build image

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml
.github/workflows/codeql-analysis.yml
setup.py

https://github.com/docker/docker-py/issues/3113 is fixed with docker-py release 6.1

CI: Unpin requests for docker-compose

---

CHANGELOG.md
horovod/__init__.py

Preparing release v0.28.0.
I aimed to add all user-facing changes to the changelog, roughly in commit order. Please have a look if everything looks right.

Bump version to 0.28.0

---

horovod/tensorflow/mpi_ops.py

This PR is to corrret **horovod_local_rank** method of tensorflow.
[#3939](https://github.com/horovod/horovod/issues/3939)

Fix local_rank_op for tensorflow

---

horovod/common/common.h
horovod/common/group_table.h

This fixes a build issue I experience with gcc 13 on Fedora 38. Some headers are missing.

fix: add missing headers

---

horovod/_keras/__init__.py
horovod/keras/__init__.py
horovod/tensorflow/__init__.py
horovod/tensorflow/gradient_aggregation.py
horovod/tensorflow/gradient_aggregation_eager.py

Add backward_passes_per_step for gradient aggregation with partial distributed optimizer.
N/A

Add backward_passes_per_step for gradient aggregation with partial distributed optimizer

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml
.github/workflows/codeql-analysis.yml

With docker==7.0.0, running `docker-compose` breaks:
```
docker-compose -f docker-compose.test.yml build test-cpu-gloo-py3_7-tf1_15_5-keras2_2_4-torch1_8_1-mxnet1_5_1_p0-pyspark3_4_0
File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/docker-compose", line 8, in <module>
sys.exit(main())
File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/compose/cli/main.py", line 81, in main
command_func()
File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/compose/cli/main.py", line 200, in perform_command
project = project_from_options('.', options)
File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/compose/cli/command.py", line 60, in project_from_options
return get_project(
File …
```

Move from `docker-compose` to `docker compose`

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Fixes build script for Python 3.7 docker image.

Use Python 3.7 get-pip script where needed

---

Dockerfile.test.cpu
Dockerfile.test.gpu
setup.py

CI: Add protobuf constrait when installing with tensorflow

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml

Uses `macos-latest` for macOS tests.

Use `macos-latest` in CI
