README.md
horovod/tensorflow/mpi_ops.cc

VGG-16 has one giant tensor and a lot of small tensors to be reduced.  Before this change, it would try to fill up fusion buffer and wait for all the small tensors to be ready to be reduced.  This causes large tensor, which may be available earlier than that, to have to wait unnecessarily long.
With this change, we stop attempting to fuse more tensors if we encounter non-fusible tensor.  We can later apply some additional heuristics to do some look-ahead, but for now, this seems to be giving almost all the benefits of tensor fusion with minimal cost.

Improve performance of Tensor Fusion for networks with large tensor size discrepancy (e.g. VGG-16)

---

setup.py

Cray MPI doesn't have `mpicxx`, so we need the ability to specify the command that will show MPI compilation flags.
Additionally, `mpicxx -show` and `CC --cray-print-opts=all` have slightly different behavior.  Former displays compiler name AND flags, while latter just prints flags.
We assume the flags start with `-`, so if the first word in the result does not start with `-`, we assume that it's the compiler name and skip it.

Support for Cray MPI: custom command to discover MPI compilation flags

---

docs/troubleshooting.md
horovod/tensorflow/mpi_ops.cc

We currently allow `ncclCommInitRank` to update the value in the map directly, which causes an issue if there is an error - `ncclCommInitRank` may return corrupted value.
Thanks to @sjeaugey for the suggestion!

Better error check for NCCL init

---

horovod/tensorflow/mpi_ops.cc
setup.py

During initial integration with NCCL, we have observed an issue (hanging) with dynamic NCCL communicator creation via `ncclCommInitRank()` and then immediate call to `ncclAllreduce()` & `cudaStreamSynchronize()` or `cudaEventSynchronize()`.  Stack traces look like this:
```
Thread 55 (Thread 0x7f0085cb9700 (LWP 69796)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x00007f008a16b1eb in ?? () from /home/asergeev/mpi/nccl/libnccl.so.2 
#2 0x00007f008a1a40e1 in ?? () from /home/asergeev/mpi/nccl/libnccl.so.2 
#3 0x00007f008a1a479e in ?? () from /home/asergeev/mpi/nccl/libnccl.so.2 
#4 0x00007f008a1a6315 in ?? () from /home/asergeev/mpi/nccl/libnccl.so.2 
#5 0x00007f008a1b520d in ?? () from /home/asergeev/mpi/nccl/libnccl.so.2 
#6 …
```

Replace one-second sleep with an MPI barrier in NCCL initialization

---

examples/keras_mnist.py

I get a the following error when I try to run in python 3. This is the fix. 
```
File "keras_mnist.py", line 82, in <module>
validation_data=(x_test, y_test))
...
TypeError: 'float' object cannot be interpreted as an integer
```

Python 3 compatability fix

---

README.md
docs/benchmarks.md
docs/running.md

1. Open MPI 3 specific instructions.
2. Dealing with non-routed network interfaces.
3. Keras 2.0.9 bug.
4. `-mca pml ob1` to avoid UCX issues.
5. Benchmarking instructions.
Covers questions in #70, #67, #60.

Various README updates

---

.travis.yml
README.md
docs/benchmarks.md
docs/running.md
docs/troubleshooting.md

Potentially solves #94 and solves an internal issue I had with Open MPI 3.0.0.

Replace `-oversubscribe` with `-map-by slot`

---

.travis.yml

TensorFlow upgraded base image to Ubuntu 16 (https://github.com/tensorflow/tensorflow/issues/15777).  Travis CI does not support Ubuntu 16 (https://github.com/travis-ci/travis-ci/issues/5821), so we need to dockerize our tests.

Dockerize Travis as TensorFlow will require new GLIBC

---

.travis.yml

They have recently changed keras github url. Redirect from `fchollet` to `keras-team` still works, but this PR better changes the url to the new one in the .travis.yml.

Fix/Update Keras github url in .travis.yml

---

docs/docker.md

Fix spelling error in the docker documentation

---

horovod/tensorflow/__init__.py

This PR updates `BroadcastGlobalVariablesHook` to create a new broadcast op each time the hook is run on a new graph.
Certain TensorFlow APIs, e.g. [tf.estimator.train_and_evaluate](https://www.tensorflow.org/versions/master/api_docs/python/tf/estimator/train_and_evaluate), depend upon being able to instantiate hooks once and reuse them across different TensorFlow graphs/sessions. In these cases the [begin()](https://www.tensorflow.org/api_docs/python/tf/train/SessionRunHook#begin) method is expected to add ops to the current graph if needed. However, the current BroadcastGlobalVariablesHook only adds broadcast ops to the current graph at the time the hook is first run. As a result, [this fork of the MNIST estimator example](https://gist.github.com/smurching/bb703e024507dde065ea11289b36da2 …

Update BroadcastGlobalVariablesHook to create a new broadcast op when run on a new TF graph

---

horovod/common/mpi_message.cc
horovod/common/mpi_message.h
horovod/common/operations.cc
horovod/common/wire/mpi_message.fbs
horovod/common/wire/mpi_message_generated.h

Fuse all available MPI requests together into a single request to save total # of MPI communications.  Improves performance on a very large scale (512+ GPUs).

MPI request fusion

---

Dockerfile

The current Dockerfile is broken because of mismatched cuDNN versions (I filed a bug against tensorflow: https://github.com/tensorflow/tensorflow/issues/17566). Test image pushed to rongou/horovod on dockerhub.
Fixes #192, fixes #203.

Pin Dockerfile to a specific cuDNN version.

---

horovod/common/__init__.py

Correcting incorrect function name.
see #213

 Error on using hvd.mpi_threads_supported() error: undefined symbol: mpi_threads_supported 

---

Dockerfile

Looks like the tensorflow benchmarks don't work with 1.6.0 any more.

Upgrade tensorflow to 1.8.0 in the Dockerfile.

---

setup.py

By default, nccl is linked statically.
To link against the shared lib `export HOROVOD_NCCL_LINK=SHARED`.

Selectable shared or static linking of libnccl

---

examples/pytorch_mnist.py
horovod/torch/mpi_ops.py
test/test_torch.py

Note: only made the synchronous functions that do not modify tensors in place differentiable.  The reasoning here is that modifying tensors in place and performing async ops doesn't lend itself conceptually well to the concept of a graph, but open to adding additional support.
Because the input tensor needs to have the property requires_grad for this to do anything, there should not be any additional memory or compute cost from this implementation.

Made synchronous pure functional Horovod ops differentiable in PyTorch

---

horovod/common/common.cc
horovod/common/common.h
horovod/common/hashes.h
horovod/common/operations.cc
horovod/common/operations.h
horovod/common/timeline.cc

- another recommendation
in `horovod/common/timeline.cc`:
those escaped `"` can be rewritten as raw string literal

C++11 syntax enhancement

---

README.md
horovod/common/__init__.py
horovod/common/operations.cc
horovod/common/operations.h
horovod/keras/__init__.py
horovod/tensorflow/__init__.py
horovod/torch/__init__.py

This enables users to initialize Horovod on a specified list of ranks or a given communicator. It allows multiple Horovod instances to be embedded in a larger MPI application. Very similar to the existing (stale) #218

Initialize Horovod with the provided MPI ranks or MPI communicator

---

horovod/common/__init__.py
horovod/keras/__init__.py
horovod/tensorflow/__init__.py
horovod/tensorflow/mpi_ops.py
horovod/torch/__init__.py
horovod/torch/mpi_ops.py
setup.py
test/common.py
test/test_tensorflow.py
test/test_torch.py

Split off `horovod.common` C++ code compilation into both `horovod.tensorflow` and `horovod.torch`.  Preparation for migrating PyTorch plugin to C++.
**Note:** You can still import both `horovod.tensorflow` and `horovod.torch` into the same Python script, but they will create two separate MPI communicators and background threads.

Support incompatible TensorFlow and PyTorch ABI

---

.travis.yml
setup.py

`pip install torch_nightly torchvision` brings in `torch` as well.

Fix torch_nightly test to not use `torch`

---

horovod.exp
horovod.lds

Fixed issue with dynamically linking PyTorch module on Mac OSX 

---

horovod/common/operations.cc

Use `MPI_Type_size` to get the size of MPI types instead of dividing `buffer_len` by `num_elements`, which may give division-by-zero errors for empty tensors, or using sizeof(MPI_DOUBLE), which does not have correct behavior.

Use MPI_Type_size to get sizes of MPI types

---

horovod/torch/__init__.py
test/test_torch.py

This resolves an issue very specific to SGD, which only maintains state when momentum is specified.  Without momentum, it's stateless, and attempting to access the state dict during broadcast raises an error.  This solution is to simply skip broadcast if the state dict is empty.

Fixed broadcast_optimizer_state for stateless optimizers

---

horovod/torch/mpi_ops_v2.cc

Borrowed from https://github.com/pytorch/pytorch/commit/e2d2b270dbe7c738687c04b3fac5b7051d770f72.

PyTorch 1.0: Switch to new way to initialize CPU tensors

---

horovod/torch/mpi_ops_v2.cc

Inspired by https://github.com/pytorch/pytorch/pull/12360.  Improves on #555 by not creating brand new non-Variable Tensor.

PyTorch 1.0: Switch to new way to initialize CPU tensors (v2)

---

horovod/common/operations.cc

TensorFlow treats AbortedError in a special way - it will do infinite retries in MonitedSession if AbortedError is encountered in the hook.  Switching to UnknownError should prevent this retry logic.
Fixes #552

Switch Horovod Shutdown to UnknownError

---

LICENSE
horovod/common/half.h
horovod/common/operations.cc
test/test_tensorflow.py
test/test_torch.py

Implements custom MPI operation to provide CPU-FP16 allreduce. Uses FP16<->FP32 conversion for the actual computation.

FP16 allreduce on CPU

---

.travis.yml

Fix for `error in absl-py setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers`.

Upgrade setuptools to avoid absl-py error

---

horovod/common/half.cc
horovod/common/half.h
horovod/common/operations.cc
setup.py

Use CPU intrinsics to do fast FP16 conversion & vectorization. Observe 10-12% speedup over two nodes.

Add AVX intrinsics to vectorize & speed up FP16-CPU computations

---

horovod/keras/__init__.py
horovod/keras/impl.py
horovod/tensorflow/__init__.py
horovod/tensorflow/keras/__init__.py
test/test_keras.py
test/test_tensorflow_keras.py

As shown in #554, #566, #430, and potentially other issues, sometimes sparse gradients are not so sparse.  This can cause bad performance and OOMs.
This change introduces option `hvd.DistributedOptimizer(..., sparse_as_dense=False)` that, if set to true, will force all sparse gradients to be densified.
Fixes #554 
Fixes #566 
Fixes #430

Added option to treat sparse gradients as dense tensors

---

horovod/torch/__init__.py
test/test_torch.py

Addresses Issue #564
1) Added a set, ```self._requires_update```, to ensure that all gradients are passed to allreduce even if a gradient is not calculated during ```loss.backward()```. If a gradient is not calculated, assume the gradient should be set to 0.
2) Added a function ```_allreduce_grad(self, p)``` to avoid redundant code because this is called both when making hooks and when forcing allreduce on missing gradients.
3) Created arbitrary parameter names even if ```model.named_parameters()``` is not passed into ```DistributedOptimizer()```. This ensures that the gradients which were forced to allreduce on one replica know which gradients to communicate with on the other replicas. Otherwise replicas will have communication problems about which gradients to perform allreduce on.

 Added force allreduce of all gradients in step()

---

horovod/torch/adapter_v2.cc
horovod/torch/adapter_v2.h
horovod/torch/mpi_ops_v2.cc

ATen is still undergoing major churn and many things are moving from the `at::` namespace to the `c10::` namespace. Both namespaces are exported into the `torch::` namespace so you can save yourself some trouble by using `torch::` everywhere and never `at::`.

Use torch:: instead of at:: namespace in Torch backend

---

horovod/torch/__init__.py
test/test_torch.py

Fixed broadcast_optimizer_state to properly convert nested types

---

examples/pytorch_imagenet_resnet50.py

The current examples reduces the `loss` which, during training, carries with itself the computation graph. This results in a memory leak which in my case resulted in OOM errors.
[Detaching](https://pytorch.org/docs/stable/autograd.html#torch.Tensor.detach) the variable before reduction solved the memory leak for me.

Fix memory leak in pytorch_imagenet_resnet50.py example

---

.travis.yml

Debian `sid` started including Python 3.7, and so `python3` now have a different meaning.  Update the integration tests to resolve this issue.

Fix Python3.6 integration tests

---

.travis.yml
examples/tensorflow_mnist.py
examples/tensorflow_mnist_estimator.py

Some of the examples were using depreciated tensorflow APIs to load the data and these changes fix the problem.
- updated the MNIST Dataset API
- updated ModeKey
Issue #673

Removed depreciated tensorflow dataset APIs

---

Dockerfile

With NCCL 2.3.5, setting `NCCL_SOCKET_IFNAME` causes the process to hang. See https://github.com/kubeflow/mpi-operator/issues/57. From talking to the NCCL guys, simply removing that line from `nccl.conf` should suffice. I've tested this on the mpi operator.

fix configuration issue with nccl 2.3.5

---

horovod/_keras/__init__.py

Keras added `name` argument as an optimizer configuration parameter which clashes with one of the arguments that we pass ourselves. Switching `**kwargs` -> `config` to avoid this issue.

Keras: pass optimizer parameters as dictionary instead of **kwargs

---

docs/running.md

Update running docs with new NCCL semantics

---

.travis.yml

Sometimes integration tests fail with an aborted error during MPI_Bcast.  This debug flag should help diagnose the issue.

Print stack trace upon MPI_Abort

---

horovod/common/operations.cc
horovod/tensorflow/mpi_ops.cc

The proposal is to revert the change of using PerformOperation() to do memory copy, since it's a blocking operation, unlike memory copy performed by TensorFlow.
I've seen 10%-15% performance improvement for a small embedding + MLP model with 2M parameters.  Each Allgather operation turns from 0.2ms to 0.035ms each.
@karakusc, could you try and see if this introduces any significant regression for large tensor use case?
Before the change:
[horovod-timeline-v1.json.zip](https://github.com/uber/horovod/files/2711596/horovod-timeline-v1.json.zip)
After the change:
[horovod-timeline-v2.json.zip](https://github.com/uber/horovod/files/2711595/horovod-timeline-v2.json.zip)

Have TensorFlow handle memcpy for Hierarchical Allgather

---

horovod/common/logging.cc
horovod/common/logging.h
horovod/common/mpi_message.cc
horovod/common/mpi_message.h
horovod/common/operations.cc
horovod/common/parameter_manager.cc
horovod/common/timeline.cc
setup.py

Adds a logging framework with different levels, which the user can activate by using the environment variable  `HOROVOD_LOG_LEVEL`. It takes the values as follows:
`fatal`, `error`, `warning` : Warnings like stalled tensors, etc **(default)**
`info`: Logs the configuration and initialization and shutdown,etc
`debug`: Logs how many tensors are being fused, what size, etc
`trace` : Logs names of tensors being reduced in addition to the above
This PR also adds some logs at the appropriate level. The intention is to allow users (or developers) to take a closer look at Horovod operations when they face a crash or hang. There is no performance effect to this (unless you turn on trace maybe, but even that was barely noticeable in my experience). If you think the level of some statement should be …

Adds a logging framework

---

test/test_keras.py
test/test_spark.py
test/test_tensorflow.py
test/test_tensorflow_keras.py
test/test_torch.py

We have so many deprecation warnings because of old TensorFlow/PyTorch, that Travis CI fails, e.g. https://api.travis-ci.org/v3/job/479219817/log.txt

Filter warnings to avoid Travis CI failure

---

.travis.yml
test/test_torch.py

Make situation where Horovod can actually finish allreduce operation before the next one is enqueued less likely.  With default 5ms timeout, we should not see all 10 loop iterations succeed.

Make duplicate name test more robust

---

horovod/mxnet/__init__.py
test/test_mxnet.py

The sequential wait_to_read and ret_list in broadcast_parameters are not needed. Thanks @alsrgv for pointing this out.
Verified in mxnet_mnist example.
@yuxihu @ctcyang Please help to review this. Thanks!

remove unnecessary wait_to_read and ret_list

---

examples/mxnet_imagenet_resnet50.py

Recently we identified a performance regression in MXNet for training resnet50_v1 when using MXNet ImageRecordIter. The [fix](https://github.com/apache/incubator-mxnet/pull/13980) has been merged. This PR is to update the imagenet example to pick up the fix by setting device_id for ImageRecordIter such that we can get desired performance.

MXNet: improve imagenet example performance

---

horovod/common/common.cc
horovod/common/mpi_message.cc
horovod/common/operations.cc
horovod/common/optim/bayesian_optimization.cc
horovod/common/optim/gaussian_process.cc
horovod/common/parameter_manager.cc
horovod/tensorflow/mpi_ops.cc
horovod/torch/adapter.cc
horovod/torch/adapter_v2.cc

Change all post-increments to pre-increments where necessary to improve performance.
For example consider the following:
```
class Integer {
public:
// Sample implementation of pre-incrementing.
Integer & operator++() {
myInt += 1;
return *this;
}
// Sample implementation of post-incrementing.
const Integer operator++(int) {
Integer temporary = *this;
++*this;
return temporary;
}
private:
int myInt;
};
```
The additional copy (temporary) in post-incrementing step is unnecessary.
---------------------------------------------------------------------------
Also optimized vectors which were not being reserved even though we knew
the exact number of elements that were going into it, this saves on
reallocation costs (and copies).
------------------------------------------------------------------ …

Optimized vectors and post-increments. [Refactored for Performance]

---

README.md
horovod/mxnet/__init__.py
horovod/mxnet/mpi_ops.cc

Recently we add [aggregated updates](https://github.com/apache/incubator-mxnet/pull/13346) in MXNet for SGD optimizer. The same aggregation behavior will extend to other optimizers. This requires changes in Horovod's DistributedOptimizer wrapper for MXNet to support allreduce multiple tensors in a single update call. This PR is to add this support. We are also working to add CI in MXNet for Horovod to identify such breaking API changes.
In addition, we fixed two issues:
1. We add a sync point in broadcast_parameters to make sure tensors pushed to MXNet engine got processed to avoid potential duplicate name error.
2. We fix horovod_mxnet_broadcast_async function to do in-place and not-in-place broadcast correctly. Thanks @alsrgv for pointing it out.

MXNet: support aggregation in optimizer & few bugfixes

---

horovod/common/operations.cc
horovod/common/optim/bayesian_optimization.cc
horovod/common/optim/bayesian_optimization.h
horovod/common/parameter_manager.cc
horovod/common/parameter_manager.h

- Use time between samples instead of aggregated time spent in the background thread for computing sample score
- Normalized scores after each sample to focus the Bayesian optimization more on certain ranges of parameters
- Increased noise parameter from 0.2 -> 0.8 to reflect apriori entropy expectations in samples

Improved autotuning scoring and parameter search process

---

README.md
examples/mxnet_imagenet_resnet50.py
examples/mxnet_mnist.py
horovod/mxnet/__init__.py

This PR makes the following changes:
1. support broadcast parameter which type is ParameterDict
2. update imagenet example to provide an option to train with Gluon Trainer API

MXNet: support Gluon Trainer API

---

setup.py

IBM PowerAI DDL will be installed in Anaconda environments. The path will not always be '/opt/DL/ddl' anymore.
HOROVOD_DDL_HOME or HOROVOD_DDL_INCLUDE/HOROVOD_DDL_LIB can be used to
specify include/lib dirs.

Add option to pass include/lib dirs for building with PowerAI DDL

---

README.md
examples/mxnet_imagenet_resnet50.py

No need to call `split_and_load `, which is meant for splitting data when the number of context is greater than 1. Calling `as_in_context` should be sufficient. Also I made the training loop simpler.

Update MXNet example in README.md

---

README.md
examples/mxnet_mnist.py

Current mxnet examples uses an old module API which has been gradually replaced by a more user-friendly Gluon API. Replacing the example and README using Gluon API for mxnet.

Simplify mnnist example using Gluon API and update README

---

horovod/spark/util/safe_shell_exec.py

We've encountered an issue with launching ssh inside safe_shell_exec.
OpenSSH makes use of tcsetattr() to set terminal properties, which gets
propagated to whole process group.  setsid() provides better isolation
of newly spawned process.
Additional reading: https://en.wikipedia.org/wiki/Process_group

Use os.setsid() instead of os.setpgid()

---

horovod/spark/util/safe_shell_exec.py

Makes downstream life easier, e.g. for #869.

Switch safe_shell_exec() from byte stdout/stderr to text stdout/stderr

---

horovod/run/run.py

safe_shell_exec uses line buffering which does not play very well with
Keras and tqdm -- libraries that make use of progress bars.

horovodrun: use os.execve() for mpirun

---

README.md

In `README.md`, the "Kubeflow" link is broken (goes to a non-existing `kubeflow/openmpi` folder). I've updated the link to point to `kubeflow/mpi-job` instead, which I believe is the updated name of the old component.

Updated README link for Kubeflow MPI Job

---

.travis.yml

See tensorflow/tensorflow#27067
Updates symlinks to gcc-4.9/g++-4.9 before Horovod installation, and restores them afterward.
gcc-4.8 would work for TensorFlow as well, but does not interoperate well with pybind11 used by PyTorch (https://github.com/pybind/pybind11/issues/1032)

Pin GCC 4.9 in CI

---

examples/mxnet_mnist.py
horovod/mxnet/__init__.py
test/test_mxnet.py

Fixes #895 
In Gluon, we defer initialization for some parameters until their shapes are known during the first forward pass. This makes it difficult for us to sync parameters among workers when we train with different random seeds for workers.
To solve the issue, we inject broadcast into init_impl of deferred initialized Gluon Parameter. Thanks @romerojosh for suggesting this idea.

MXNet: support broadcasting deferred initialization parameters in Gluon

---

README.md
examples/mxnet_imagenet_resnet50.py
examples/mxnet_mnist.py
horovod/mxnet/__init__.py

DistributedTrainer is a subclass of Gluon Trainer. We override the `_allreduce_grads` function in Trainer to use Horovod `allreduce_` instead of kvstore pull/push methods. This makes distributed training using MXNet Gluon API with PS and Horovod have the same internal workflow.
Thanks @ptrendx and @romerojosh for proposing this [idea](https://github.com/horovod/horovod/pull/915#issuecomment-474022074).

MXNet: add DistributedTrainer for Gluon

---

examples/mxnet_imagenet_resnet50.py
examples/mxnet_mnist.py
horovod/mxnet/__init__.py

We currently perform average on gradients using allreduce methods in DistributedOptimizer and DistributedTrainer. This is equivalent to normalizing optimizer.rescale_grad by Horovod size(), which has better performance. 
This PR replaces allreduce average with normalized rescale_grad. Our tests show 2~3% performance boost when training ResNet50 with 8 GPUs.

MXNet: Normalize rescale_grad in optimizer by Horovod size

---

horovod/mxnet/__init__.py
horovod/mxnet/mpi_ops.cc
horovod/mxnet/mpi_ops.h
horovod/mxnet/mpi_ops.py

@romerojosh noticed that small but noticeable time is spent pushing the Horovod ops to the engine, which has the effect of holding back GPU kernel launches if these ops are scheduled on the GPU context.
These small stalls are removed if these operations are put into the CPU context explicitly.
Placing these operations into the CPU context also makes some sense, since the underlying Horovod operation that is pushed to the MXNet engine itself doesn't mutate the GPU data, but just enqueues work to Horovod.
Since now all operations are pushed to CPU context, we also use kCPUPrioritized when pushing such that we can leverage the default multiple [MXNET_CPU_PRIORITY_NTHREADS](http://mxnet.incubator.apache.org/versions/master/faq/env_var.html) to schedule CPU jobs. This also aligns with the way …

MXNet: push Horovod operations to engine using CPU context

---

horovod/mxnet/mpi_ops.cc
horovod/mxnet/mpi_ops.h

Currently, if HAVE_CUDA is set and HOROVOD_GPU_ALLREDUCE/ALLGATHER/BROADCAST is not set, we copy the tensor to CPU, perform Horovod operations and copy it back from CPU regardless of the tensor context. However, copy to CPU is needed only when the tensor is not in CPU context.
This PR checks the context of the tensors to avoid unnecessary copy to CPU. We also refactor the code to make this change cleaner.

MXNet: perform copy to CPU when needed

---

setup.py

When building Horovod with Pytorch plugin explicitly disabled, do not add cffi to the dependency list.

Do not require cffi if pytorch build is disabled

---

horovod/mxnet/tensor_util.cc

Fix include issue for the upcoming MXNet 1.4.1 release.

MXNet: explicitly include c_api.h in tensor_utils.cc

---

README.md

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Add missing import for torch.nn.functional

---

horovod/run/common/service/driver_service.py
horovod/run/common/util/network.py
horovod/run/run.py

1. Align verbosity with Spark.  `horovodrun --verbose` is equivalent to `horovod.spark.run(verbose=2)`, since the latter has `verbose=1` by default.
2. `-np` is required unless `-v` is specified.
3. `--start-timeout` should be an integer.
4. Self-diagnose NAT issues (#1032)

Bugfixes in horovodrun argument handling and verbosity

---

horovod/run/common/util/env.py

Resolves the following warning:
```
Warning: could not find environment variable "OLDPWD"
```

Ignore OLDPWD environment variable in Horovodrun

---

docker-compose.test.yml

A workaround until https://github.com/tensorflow/tensorflow/issues/28845 is resolved.

Pin tf-nightly-gpu to 1.14.1.dev20190517

---

horovod/torch/__init__.py
test/test_torch.py

When adding the ability to perform local gradient accumulation, a bug was introduced which caused an error if `named_parameters=None`, i.e. was left at its default, when passed to `hvd.DistributedOptimizer`.

Fix bug introduced by _allreduce_delay

---

test/test_tensorflow.py

Fixes break introduced in a recent `tf-nightly-gpu`.

Specify GPU configuration for eager TensorFlow tests

---

docker-compose.test.yml

1. Pin TF until tensorflow/tensorflow#29559 is resolved.
2. `s/torchvision_nightly/torchvision/` due to pytorch/vision#833.

Pin tf-nightly to 1.14.1.dev20190606 & remove torchvision-nightly

---

docs/conf.py
horovod/torch/__init__.py
test/test_torch.py

NVIDIA AMP does not support passing additional flags to `optimizer.step()`, such as `optimizer.step(synchronize=False)`.
This PR switches API to use context manager:
```python
optimizer.synchronize()
with optimizer.skip_synchronize():
optimizer.step()
```

Replace .step(synchronize=False) with optimizer.skip_synchronize()

---

setup.py

Remove the unnecessary `MSHADOW_USE_F16C` compiler flag when building Horovod with MXNet
Fix https://github.com/horovod/horovod/issues/1138

Fixes build error in MXNet on certain platforms

---

examples/mxnet_imagenet_resnet50.py

Fix the example of imagenet when users runs with synthetic data. Before this fix, it would fail with error 'batch_fn' not defined.

fix imagenet example with synthetic input

---

horovod/mxnet/__init__.py

**Problem**
Due to a security feature of Python added in 3.2 https://mail.python.org/pipermail/python-announce-list/2012-March/009394.html and then dropped in 3.6 https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-compactdict , the order of elements w.r.t. order of insertion in `dict()` is not guaranteed.
As a consequence, the order of params in Gluon can vary between Python interpreters instances/processes.
**Solution**
Add a sort by name in `_allreduce_grads`.
Signed-off-by: Serge Panev <spanev@nvidia.com>

Fix MXNet Gluon DistributedTrainer for Python < 3.6

---

horovod/run/common/util/host_hash.py

Apparently, if the full hostname is used in mpirun, e.g. `john-cdhx-3.gce.cloudera.com-11aed9aa6c5cdabe73c81686492d16bc:2`, MPI is able to deduce that `john-cdhx-3` is localhost and hence skip running `rsh` script.
This causes `Exception: Timed out waiting for command to run. Please check that you have enough resources to run all Horovod processes. Each Horovod process runs in a Spark task. You may need to increase the start_timeout parameter to a larger value if your Spark resources are allocated on-demand.`
Fixes #1000 
Possibly related #952
cc @mengxr

Use the first fragment of hostname for host-hash in Spark

---

horovod/torch/__init__.py

According to https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager, we should use try-finally around `@contextmanager`.

Use try-finally in contextmanager

---

Dockerfile
Dockerfile.test.cpu
Dockerfile.test.gpu
README.rst
docs/gpus.rst
docs/index.rst
docs/summary.rst
horovod/common/util.py
setup.py
test/common.py
test/test_stall.py
test/test_timeline.py

g++ version selection has been a long-standing pain point.  TensorFlow from PyPI requires g++ 4.8.5 or 4.9, PyTorch from PyPI requires g++ 4.9+, and Conda versions require g++ 5.4.0+.
This change introduces the ability of Horovod to use different compiler per framework and provide users with meaningful error messages when it's known that given compiler/framework combination will not work.
Additionally, this change allows us to remove cherry-picked g++-4.9 and use g++-7 & g++-4.8.5 combination.
Fixes #1197
Fixes #1131

Horovod auto-selection of g++ version

---

setup.py

It's preferred to use `gcc` for `CC` and `g++` for `CXX`.  Since `g++` depends on `gcc`, we must be able to find a matching `gcc` compiler.

Autodetect matching gcc compiler

---

setup.py

This pr is an amendment to the pr that Alex created for autodetecting matching gcc compiler. Since different plugins may be compiled using different compilers, the gloo needs to be compiled with the same compiler, which means gloo should be compiled each time a plugin is compiled.

Separately build gloo for each plugins

---

docker-compose.test.yml

There are two separate issues.
`tf-nightly-gpu` between 20190710 - 20190715 fails with:
```
File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/module_wrapper.py", line 174, in __setattr__
if arg not in self.__all__ and arg != '__all__':
File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/module_wrapper.py", line 161, in __getattr__
raise e
File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/module_wrapper.py", line 158, in __getattr__
attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow_estimator.python.estimator.api' has no attribute '__all__'
root@opusgpux1-wbu2:/# pip3 install tf-nightly==1.15.0.dev20190709
```
The issue is resolved in `tf-nightly` 20190717, but the `tf-nightly-gpu` build is …

Pin tf-nightly-gpu and mxnet-cu100 --pre

---

horovod/common/basics.py

C API defines horovod_init, horovod_init_comm, and horovod_shutdown as returning
void.  When ctypes interprets their return values as ints, it returns garbage.

Do not return random ints from init and shutdown

---

horovod/spark/__init__.py

Added guard to namedtuple class to prevent pyspark from overwriting it and breaking serialization

---

horovod/tensorflow/__init__.py

This is necessary to support `bcast_op.run()` use cases.
cc @zsh-thu

hvd.tf.broadcast_variables: return Tensor in eager mode and Op in graph mode

---

test/test_stall.py

The mpi4py package is not used and will cause trouble to integration tests for non-MPI cases.

Remove unsed imported package mpi4py in test_stall.py

---

setup.py

Fix g++ autodetection in cases when some of the system flags are not defined

---

setup.py

After submodule gloo is separately built for each plugin in  #1209,  there can be a situation that one plugin can access to libraries that weren't compiled by its selected compiler. To prevent this corruption, each plugin should be built based on the copy of the global compiling options.

Backup global compiling options when building Tensorflow and PyTorch plugins.

---

docker-compose.test.yml
horovod/mxnet/mpi_ops.cc
horovod/mxnet/tensor_util.cc

Due to a new set of [APIs](https://github.com/apache/incubator-mxnet/pull/15551) introduced in recent MXNet master branch, we hit [undefined symbol error](https://github.com/horovod/horovod/issues/1217) when running Horovod with nightly MXNet build. This PR fixes #1217 and https://github.com/apache/incubator-mxnet/issues/15578 by using C API.

Fix integration with MXNet nightly build

---

Dockerfile.test.cpu
Dockerfile.test.gpu
setup.py

Due to ABI compatibility with GCC after 5.1, different ABI compiler setting can lead to "undefined symbol" errors for submodule Gloo during runtime for Pytorch plugin. So we must use the same ABI compiler flag that PyTorch uses to compile Gloo. By setting `CMAKE_CXX_FLAGS_[DEBUG/RELEASE]` (whichever mode we are using), cmake can append these flags to CMAKE_CXX_FLAGS when compiling files. 
This pr also added `cmake` as a required package for test docker, so that integration tests can build Gloo for each plugins.

Add abi related compiler args when build cmake extension.

---

.buildkite/gen-pipeline.sh
docs/running.rst
horovod/run/run.py

Enable the same --hostfile option in horovodrun as in mpirun.
Users can specify a list of hosts in the hostfile as:
<host1> slots=<num_procs>
<host2> slots=<num_procs>
...
Tested on a GPU cluster with 8 nodes.
This PR fix https://github.com/horovod/horovod/issues/1231

Add -hostfile option to horovodrun

---

setup.py

#1154 Broke the build for PowerAI DDL.
The location of "horovod/common/ddl_mpi_context_manager.cc" is incorrect in setup.py
https://github.com/horovod/horovod/commit/4451dd0df5243fd9941022f72b2ff17cb6833222#diff-2eeaed663bd0d25b7e608891384b7298R676
@nvcastet

Update reference to horovod/common/ddl_mpi_context_manager.cc

---

horovod/mxnet/adapter.cc
horovod/mxnet/adapter.h
horovod/mxnet/mpi_ops.cc
horovod/mxnet/mpi_ops.h

This issue arises `[1,0]<stderr>:mxnet.base.MXNetError: [05:07:07] src/ndarray/ndarray.cc:1282: unknown device mask` when running some specific MXNet model script when horovod installed without NCCL.
The issue is because we had two Async nested calls, for example, `A` and `B` and it is called as `B(A)`. The temporary CPU tensor is created in Async call method `A` and it's deleted when it's goes out of scope, so the Async method `B`doesn't aware of it and tries to copy the data from CPU tensor(Which was created in `A`) to GPU which results in above failure. This block of code is only executed when horovod compiled without NCCL. The fix is to create a shared pointer outside of the `B` scope and pass it in `B(A)` and once the tensor usage has finished, it will be deleted from the memory …

(MXNet) Fixed: unknown device mask issue

---

horovod/run/run.py

Fix hostfile argument bug in horovodrun:
`args.hostfiles` ==> `args.hostfile`

Fix hostfile argument bug in horovodrun

---

.buildkite/gen-pipeline.sh
examples/tensorflow2_mnist.py
examples/tensorflow2_synthetic_benchmark.py
examples/tensorflow_mnist_eager.py
examples/tensorflow_synthetic_benchmark.py
horovod/_keras/__init__.py
horovod/tensorflow/__init__.py

Motivation: new TensorFlow-Keras 2.0 [doesn't use](https://github.com/tensorflow/tensorflow/blob/498e815097e74aff7fefdbbae69ba9daf6e9c023/tensorflow/python/keras/engine/training_eager.py#L272) `Optimizer.get_gradients()` in eager mode.  However, it started using `Optimizer.apply_gradients()`, which was not the case with legacy Keras.
The proposal is to align gradient aggregation to happen during apply, similar to MXNet.  This way we will be able to deprecate `hvd.DistributedGradientTape()` and align user experience between Graph and Eager mode further.

Move allreduce to opt.apply_gradients when possible

---

examples/pytorch_imagenet_resnet50.py
examples/pytorch_mnist.py

Default thread settings sometimes cause PyTorch to overuse CPU resources available on the server.

Limit # of CPU threads for PyTorch

---

docker-compose.test.yml

mxnet-cu100 --pre is failing with:
```
E   OSError: /usr/local/lib/python2.7/dist-packages/horovod/mxnet/mpi_lib.so: undefined symbol: _ZN5mxnet12on_enter_apiEPKc
```

Pin MXNet-GPU-head to 1.6.0b20190817

---

docs/gpus.rst

Include and lib paths have to be specified explicitly on CentOS / RHEL when LD_LIBRARY_PATH is empty

CentOS / RHEL instructions

---

Dockerfile
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml

Previous upgrade #1320 did not take into account that PyTorch https://download.pytorch.org/whl/torch_stable.html is not usable for latest cuda10 releases, and that PyTorch silently ignores CUDA mismatch errors instead of loudly failing.

Pin stricter versions for PyTorch 1.2.0 upgrade

---

horovod/run/run.py

Addresses #1325 to support IPs as well as `.` subdomain separators in domain names.

Allow . characters in remote hostnames

---

setup.py

Resolves the following scenario:
```
>>> from distutils.version import LooseVersion
>>> LooseVersion('1.0.0') == None
File "<stdin>", line 1, in <module>
File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 46, in __eq__
c = self._cmp(other)
File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 335, in _cmp
if self.version == other.version:
AttributeError: 'NoneType' object has no attribute 'version'
```
Fixes #1334

Fix compiler version check

---

horovod/run/common/util/env.py

`is_exportable` is queried with the environment variable name. `()` is not part of the name, but value.

Fix BASH_FUNC_* environment exclude

---

horovod/run/gloo_run.py
horovod/run/mpi_run.py
test/test_common.py

Gloo job should raise error if any task failed. But current master code if some task failed, gloo job will still exit normally.
I add checking code and raise error if needed.
(This keep similar behavior with `mpirun`, which will exit with non-zero value if any task failed)
We could manually test this by:
```
horovodrun -np 1 --gloo python -c "raise RuntimeError('error1')"
echo $?
```
**Before**
`horovodrun` exit with 0
**After**
`horovodrun` exit with 1, and raise Runtime error "Run gloo job failed."

Make gloo job raise error when any task failed

---

test/test_keras.py

See https://github.com/keras-team/keras/pull/13246.

Fixed Keras tests for changes to weights in RMSprop optimizer for TF 2.0 compat that adds iteration scalar to the head of the weights list

---

horovod/common/basics.py

This error check in `init()` when attempting to initialize Horovod with an existing mpi4py communicator breaks this functionality completely. The issue is that the flag indicating that MPI is enabled is set in within `horovod_init_comm/InitializeHorovodOnce`, the function being blocked by the error check.

Fix error check when initializing Horovod with existing mpi4py communicator

---

docker-compose.test.yml

Recently we compressed the MXNet pip package to meet PyPI package size limit. This causes undefined symbol errors. Pin MXNet nightly to a specific version while we are resolving the issue.

Pin MXNet nightly

---

horovod/run/gloo_run.py

Without this change, users who have `/bin/sh` as their default shell will see the following error:
`sh: 1: Syntax error: Bad fd number`

Fix shell syntax.

---

horovod/run/common/util/settings.py
horovod/run/mpi_run.py
horovod/run/run.py

* Also, add '--mpi-args' flag to pass extra arguments to MPI.
In the case of LSF clusters, the slot numbers in the '-H' arguments can be
overwritten by the LSF MPI config. So to run on 2 boxes with 6 GPUs each, you
need to use: horovodrun --start-timeout 180 -np 12 --mpi-args="--map-by ppr:6:node" -H host1:6,host2:6 python mnist.py

Add Spectrum MPI support to horovodrun

---

horovod/common/ops/ddl_operations.cc

Hello,
IBM DDL support half precision training. I have add two lines to make it work with Horovod.

support fp16 with ibm ddl

---

build-docker-images.sh

Auto-remove temporary docker containers used to read horovod/tensorflow/pytorch/mxnet versions.

(minor change) Auto-remove temporary docker containers in build-docker-images.sh

---

test/test_torch.py

Right now these tests will fail with "CUDA error: invalid device ordinal" if number of available GPUs is less than number of local processes.

Skip test_horovod_allreduce_multi_gpu and test_model_parallelism if not enough GPUs.

---

horovod/common/ops/collective_operations.cc

For clarity, use output tensor size (`e.output->size()`) when writing to output tensor pointer (`e.output->data()`).
Note: for AllreduceOp, input tensor and output tensor have same shape/size, so this doesn't actually change any functionality.

(minor change) AllreduceOp: use output tensor pointer and size

---

horovod/run/common/service/driver_service.py
horovod/run/common/service/task_service.py
horovod/run/common/util/network.py
horovod/run/common/util/settings.py
horovod/run/driver/driver_service.py
horovod/run/run.py
horovod/run/task/task_service.py
horovod/run/task_fn.py
horovod/spark/__init__.py
horovod/spark/driver/driver_service.py
horovod/spark/task/task_service.py

I have run horovod.spark in a three nodes cluster. However, it got the following warning:
```
WARNING: Open MPI failed to TCP connect to a peer MPI process.  This
should not happen.
Your Open MPI job may now hang or fail.
Local host: sr505
PID:        86258
Message:    connect() to 10.1.2.104:1053 failed
Error:      Operation now in progress (115)
```
And the job got to hang. This may be related to [link](https://github.com/open-mpi/ompi/issues/4963).
And also, different NIC can provide different performance. So, we could specify the NIC for using in this patch.

support user specify the NIC

---

horovod/common/operations.cc
horovod/common/ops/collective_operations.cc
horovod/common/ops/collective_operations.h
horovod/common/ops/cuda_operations.cc
horovod/common/ops/cuda_operations.h
horovod/common/ops/ddl_operations.cc
horovod/common/ops/mpi_cuda_operations.cc
horovod/common/ops/mpi_cuda_operations.h
horovod/common/ops/nccl_operations.cc
test/test_torch.py

Allgather with CUDA tensors does not always work with tensor fusion/CUDA.
1. Build Horovod without HOROVOD_GPU_*
```
import torch
import horovod.torch as hvd
hvd.init()
// The following allgather will succeed because it will run on the CPU (manually cudaMemcpy to CPU, run CPU allgather) in pytorch/tensorflow/etc.
tensor = torch.cuda.FloatTensor(*([4])).fill_(hvd.rank())
result = hvd.allgather(tensor)
// Tensor fusion works because the CUDA memory is manually copied to/from CPU
// and AllgatherOp uses std::memcpy for tensor fusion
tensor1 = torch.cuda.FloatTensor(*([4])).fill_(hvd.rank())
tensor2 = torch.cuda.FloatTensor(*([4])).fill_(hvd.rank())
handle1 = hvd.allgather_async(tensor1)
handle2 = hvd.allgather_async(tensor2)
result1 = hvd.synchronize(handle1)
result2 = …
```

Add CUDA Allgather implementation to support tensor fusion

---

Dockerfile.test.cpu
Dockerfile.test.gpu
docs/contributors.rst
horovod/run/mpi_run.py
horovod/spark/__init__.py
test/test_run.py
test/test_spark.py

- makes horovod.spark.run() use horovod.run.mpi_run() and exposes extra_mpi_args
- adds lots of tests
This PR is easiest to review commit by commit.

Refactor horovod.spark.run()

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml

Upgrade tests to TensorFlow==1.15, PyTorch==1.3.0, Keras==2.3.1, and TensorFlow tests 2.0 to use release version

---

README.rst
docs/contributors.rst
docs/summary.rst
horovod/common/basics.py

* Adds documentation on how to build the docs
* Links the online documentation from prominent location in README.rst
* Links to the Contributors Guide from new section `Compiling`
* Makes imports robust against possible doc build failure:
```
autodoc: failed to import module 'tensorflow' from module 'horovod'; the following exception was raised:
...
File ".../horovod/common/basics.py", line 19, in <module>
import horovod.common.util as util
AttributeError: module 'horovod.common' has no attribute 'util'
```

Improve documentation build and reference

---

horovod/common/controller.cc

Remove "Cache coordinated" tracing message when running with `HOROVOD_LOG_LEVEL=trace` to limit excessive logging output.

Remove cache coordinated trace message.

---

horovod/run/task/task_service.py

Fix the following error:
```
Launching horovodrun task function was not successful:
File "/home/xianyang/opt/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/xianyang/opt/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/xianyang/opt/miniconda3/lib/python3.7/site-packages/horovod/run/task_fn.py", line 67, in <module>
_task_fn(index, driver_addresses, settings)
File "/home/xianyang/opt/miniconda3/lib/python3.7/site-packages/horovod/run/task_fn.py", line 24, in _task_fn
task = task_service.HorovodRunTaskService(index, settings.key, settings.nic)
File "/home/xianyang/opt/miniconda3/lib/python3.7/site-packages/horovod/run/task/task_service.py", line 37, in …
```

fix 'task_service' init error

---

horovod/common/util.py
horovod/tensorflow/__init__.py
horovod/tensorflow/mpi_ops.py
horovod/torch/__init__.py
horovod/torch/mpi_ops.py
test/test_adasum_tensorflow.py
test/test_common.py

Fixes #1564 and #1568
Running the GPU check during module import can result in errors of the following when only TensorFlow is installed:
```
AssertionError: daemonic processes are not allowed to have children
```
This change enforces that GPU checks are only performed when the `hvd.allreduce` call is made so Gloo / MPI checks can succeed.

Fixed GPU check to run lazily to prevent recursive subprocess creation

---

horovod/common/operations.cc
horovod/common/ops/cuda_operations.cc
horovod/common/ops/cuda_operations.h
horovod/common/thread_pool.cc
horovod/common/thread_pool.h
setup.py

Currently, Horovod creates a new thread to wait on CUDA events and trigger callbacks every time it performs an operation with NCCL. This PR adds a thread pool to reuse threads.

Use thread pool for finalizer threads.

---

.github/workflows/docs-summary.yml

Adds a github workflow that checks that `README.rst` and `summary.rst` are in sync.
This PR for some reason does not execute this workflow, but [PR #2](https://github.com/G-Research/horovod/pull/2) does. That check will succeed once #1538 is merged into master.
The check also allows for expected differences between `README.rst` and `docs/summary.rst`, provided in `docs/summary.rst.patch`.

Makes github check summary and readme sync.

---

CONTRIBUTING.md

Changes to Horovod's governance:
- Added @romerojosh and @jaliyae as voting members of the TSC
- Added @ebarsoum and @skaarthik as non-voting members of the TSC
- Changed chairman of the TSC from @alsrgv to @tgaddair 
- Formalized TSC procedures and responsibilities of voting / non-voting members

Updated governance details and added members to the TSC

---

horovod/common/ops/adasum/adasum.h
setup.py

Add extra checks for x86 compiler flags and x86 AVX headers/functions

Fix non-x86 build failures caused by #1485

---

docker-compose.test.yml

Issues fixed in https://github.com/NVIDIA/nccl/issues/269 and https://github.com/NVIDIA/nvidia-docker/issues/1143

Upgrade NCCL to 2.5.6, unpin CUDA docker digest

---

horovod/common/controller.cc

The updated code in #1594 that was merged introduced another error in fusion. In particular, based on my suggestion to simplify, it was modified to use `response.tensor_sizes()` to compute sizes for fusion instead of generating new tensor entries. However, entries in `response.tensor_sizes()` are in elements, not bytes, causing the fusion logic for allreduce to be incorrect (may create fused responses larger than allocated buffer).  
~~I have reverted to the original version of #1594 to deal with this.~~
Multiplication of `response.tensor_sizes()` by `GetTypeSize()` corrects this.

Correction to tensor size used for fusion in #1594

---

horovod/mxnet/adapter.cc
horovod/mxnet/adapter.h
horovod/mxnet/mpi_ops.cc
horovod/mxnet/mpi_ops.h
horovod/mxnet/tensor_util.cc
horovod/mxnet/tensor_util.h
test/test_mxnet.py

This PR includes the following changes:
1) Avoid early destruction of NDArray invoked by Python garbage collection by making a copy using shared_ptr
2) Simplify code by removing unnecessary template class
3) Code refactoring
4) Fixed a bug in ResizeND mentioned in https://github.com/horovod/horovod/issues/1409
This PR fixes https://github.com/horovod/horovod/issues/1533
@eric-haibin-lin @karan6181 @yuxihu Please help review!

Fix a crash bug in MXNet due to early free of tensor object

---

examples/get_gpu_resources.sh
examples/keras_spark3_rossmann.py
examples/keras_spark_rossmann_run.py
horovod/spark/task/mpirun_exec_fn.py
horovod/spark/task/task_info.py
horovod/spark/task/task_service.py
test/common.py
test/spark_common.py
test/test_spark.py

Added support for Spark 3 TaskContext to fetch GPU resources per task

---

.buildkite/gen-pipeline.sh
horovod/_keras/__init__.py
test/test_tensorflow2_keras.py
test/test_tensorflow_keras.py

Fixed Keras DistributedOptimizer to use base from_config method to support 2.0 learning rate schedules

---

horovod/torch/__init__.py
test/test_torch.py

Fixed issue with broadcasting optimizer state for params that don't require grads, added back utility function to broadcast any object

---

Dockerfile.test.cpu
Dockerfile.test.gpu

The latest torch-nightly is no longer causing segfaults.

Unpin torch-nightly

---

horovod/common/operations.cc
horovod/common/ops/cuda_operations.cc
horovod/common/ops/cuda_operations.h
horovod/common/thread_pool.cc
horovod/common/thread_pool.h
setup.py
test/test_torch.py

Recreating the ThreadPool without joining was resulting in errors of the form:
```
Thu Jan 16 16:21:02 2020[0]<stderr>:terminate called without an active exception
Thu Jan 16 16:21:02 2020[0]<stderr>:Aborted
```
This PR allows `ThreadPool::create` to be called during the second init by joining and clearing threads on shutdown.
Also fixes an issue with mixed install (using CUDA without any GPU Horovod ops) where Horovod CUDA headers would be included and the `HAVE_CUDA` macro would be set, but implementation files would not be included, causing symbol lookup errors at runtime.

Fixed issue with ThreadPool not joining on reinitialization

---

horovod/common/global_state.h
horovod/common/mpi/ddl_mpi_context_manager.cc
horovod/common/mpi/ddl_mpi_context_manager.h
horovod/common/operations.cc
horovod/common/ops/adasum_gpu_operations.cc
horovod/common/ops/adasum_gpu_operations.h
horovod/common/ops/cuda_operations.cc
horovod/common/ops/ddl_operations.cc
horovod/common/ops/ddl_operations.h
horovod/common/ops/gpu_context_impl.cc
horovod/common/ops/gpu_operations.cc
horovod/common/ops/gpu_operations.h
horovod/common/ops/hip_operations.cc
horovod/common/ops/mpi_gpu_operations.cc
horovod/common/ops/mpi_gpu_operations.h
horovod/common/ops/nccl_operations.cc
horovod/common/ops/nccl_operations.h
horovod/tensorflow/mpi_ops.cc
setup.py

- add ROCm and ROCm TensorFlow support to setup.py
- Renamed symbols and files
- CUDA -> GPU
- Cuda -> Gpu
- cuda -> gpu
- HAVE_CUDA -> HAVE_GPU --- iff generically referring to any GPU device
- CUDAContext becomes GPUContext and uses pimpl pattern to decouple
CUDA and HIP implementations of GPU interface.
- New GPUContext methods
- StreamCreate
- StreamSynchronize
- GetDevice, SetDevice
- MemcpyAsyncD2D, MemcpyAsyncH2D, MemcpyAsyncD2H
Signed-off-by: Jeff Daily <jeff.daily@amd.com>

Initial support for ROCm: rename CUDA to GPU et al, pimpl for GPU details

---

examples/keras_spark3_rossmann.py
examples/keras_spark3_rossmann.py.patch

Currently only CPU inference is available for end-to-end example keras_spark3_rossmann.py
This PR enables GPU inference for that example:
- There is a flag indicating whether to infer on GPU. It's disabled by default.
- GPU inference runs on a configurable Spark 3.0 cluster.
- This PR also demonstrates Spark 3.0 GPU scheduling.
Besides, there's another pending git commit to enable batch inference on GPU: https://github.com/chuanlihao/horovod/commit/7d5a5690f988a500fbd80dbdeb1609a7a8f90dc6

Enable GPU inference for e2e example keras_spark3_rossmann.py

---

horovod/mxnet/__init__.py

The current MXNet `DistributedOptimizer`/`DistributedTrainer` implementations will unnecessarily launch Horovod ops in the case where a script is run on a single rank. This PR adds checks to prevent this from occurring.

Prevent launching Horovod ops in MXNet DistributedOptimizer/DistributedTrainer if running on a single rank.

---

docs/spark.rst

Example file keras_spark_rossmann_advanced.py got renamed to keras_spark_rossmann_run.py during code review but we missed this spot in the docs.

Fix keras spark example in docs

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Petastorm is not compatible with the newly released Pandas==1.0.0 and causes the tests to fail. We will remove this pinned version after petastorm is fixed.

Pinned Pandas version to 0.24.2

---

.buildkite/gen-pipeline.sh

Funding for 2020 cloud testing is still being worked out.  To avoid running up a large bill, we're disabling GPU tests until funding has been secured.

Disable GPU CI tests until billing issues are resolved

---

Dockerfile.test.cpu
Dockerfile.test.gpu
setup.py

After fix is confirmed and new petastorm version is released, we will update the petastorm version and merge.

Update tests to petastorm==0.8.2 to fix pandas==1.0.0 compatibility

---

horovod/mxnet/__init__.py

#1186 introduced a sort of the parameter list to ensure the parameters were submitted to Horovod in a consistent order across workers when using `DistributedTrainer` so that requests to Horovod are given globally consistent names. This sort should not be applied in the case that the parameter list originates from a `ParameterDict` in MXNet as that data structure is already ordered (based on the graph construction). 
A particular reason this sort should only be applied when absolutely necessary is that the sort by name produces `priority` values based on a name-based ordering, which is unrelated to the underlying computation. Preserving the order of the parameter list from a `ParameterDict` results in assigned priorities consistent with those applied in the native MXNet `Trainer`. 
Update: …

Use parameter names when scheduling allreduces in DistributedTrainer. 

---

Dockerfile.test.cpu
Dockerfile.test.gpu

The 0.16 release of PyArrow requires numpy > 0.15, but older versions of MXNet are incompatible with more recent versions of numpy.  As such, we need to test against an older version of PyArrow.
In a followup PR, we will have per-test versions of PyArrow so we can test old MXNet + old PyArrow as well as new MXNet + new PyArrow.

Pin pyarrow<0.16.0

---

horovod/common/controller.cc

When using the cached communication path, the shutdown flag in the generated `response_list` is left unset (defaults to `false`). I added the missing call to `response_list.set_shutdown`.

Properly set set_shutdown flag in response_list when using cached communication path

---

horovod/_keras/callbacks.py

I ran into a type error with `hvd.callbacks.MetricAverageCallback()`. It turns out it was because `tf.Variable` did not respect the type specified with keras `set_floatx`. Using the backend API fixed the issue, and it's probably good to do that every where that's possible.
@nvcastet @bnemanich

Use backend api instead of tensorflow api in keras callbacks.

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml

This PR includes the following changes:
1. Enable all previously disabled GPU tests using G4 spot instances in AWS, now that budgeting has been sorted out.
2. Pin PyTorch to a specific working nightly until #1731 fixes v1.5.0 API incompatibilities.
3. Revert NCCL used in testing to 2.4.8, as 2.5.6 caused segfaults in pytests.

Reenabled GPU tests on g4dn.12xlarge spot instances

---

horovod/mxnet/mpi_ops.cc
horovod/mxnet/mpi_ops.py

Recent testing has shown that there is an issue with the existing MXNet out-of-place broadcast implementation in setting the output result on the root rank. The existing implementation has a race condition that can return zero tensor instead of the expected output if it is queried quickly after the `hvd.broadcast` call. For instance, in this example here:
```
tensor = nd.full((1), 42, dtype=np.int32)
output = hvd.broadcast(tensor=tensor, root_rank=0)
result = output[0].asscalar()
```
we see that `result` on the root rank can sometimes be `0` instead of the expected value `42`.
The issue is due to this special handling for root rank and the call to `TensorUtil::Copy` here: https://github.com/horovod/horovod/blob/master/horovod/mxnet/mpi_ops.cc#L101
The problem arises because …

Fix root rank output handling bug in MXNet out-of-place broadcast.

---

Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml

MXNet nightly stopped supporting python 2.7. This PR will test horovod with mxnet 1.5 when Python version is 2.7

Do not run mxnet nightly with py2.7

---

CONTRIBUTING.md

Added Nicolas Castet to the Technical Steering Committee members list

---

horovod/torch/__init__.py
test/test_torch.py

Import ABC from collections.abc instead of collections for Python 3.9 compatibility

---

setup.py

Add env variable to specify architecture-specific compiler flags.
For example, to be compatible with the older CPU architecture 'Sandy Bridge' and tune for 'Broadwell':
HOROVOD_BUILD_ARCH_FLAGS="-march=sandybridge -mtune=broadwell" ... pip install horovod

Add extra build flag 'HOROVOD_BUILD_ARCH_FLAGS'

---

horovod/spark/common/params.py
horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/spark/torch/estimator.py
horovod/spark/torch/remote.py

Some traninig jobs require to apply custom transformations to each batch before passing it to train or validation step. For instance, for training resnet model, each batch is cropped and scaled. this diff enables such transformations: 
an example transformation is:
```
def _transform_row(row):
transform = transforms.Compose([
transforms.RandomResizedCrop(224),
transforms.RandomHorizontalFlip(),
transforms.ToTensor(),
transforms.Normalize(mean=[0.485, 0.456, 0.406],
std=[0.229, 0.224, 0.225])
])
codec = CompressedImageCodec('png')
class_to_index = {val[0]: int(key) for key, val in index_to_class.items()}
row['image'] = row['image'].apply(lambda row: transform(Image.fromarray(codec.decode("image", row))).flatten().tolist())
row['noun_id'] = row['noun_id'].apply(lambda val: …
```

support data transformation  before train and validation in torch estimators

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml
horovod/run/run.py

- Removed Python 2 tests for upcoming framework releases
- Requiring frameworks to build successfully  with Horovod in Docker image
- Using context manager when parsing the host file to prevent file handle leak

Cleanup tests to improve debugging and deprecate Python 2 for new framework releases

---

horovod/run/common/util/settings.py
horovod/run/mpi_run.py
horovod/run/run.py
test/test_run.py
test/test_spark.py

To maintain compute/memory locality, it is often good practise to
bind processes to NUMA nodes.
In ppc64le architecture with large models, I see a 20% performance gain
because tensor swapping happens between GPU memory and system memory and
CPU/GPU link (NVLINK) is faster than inter-socket link.
The PR also makes socket binding the default for SMPI (ppc64le). Even
with those flags, you may end up in a situation when a process with a GPU is bound to a
non-local CPU socket. That happens usually when GPUs are not split evenly across sockets or
you don't use all the GPUs of a node. In those cases, it
is recommended to use a rankfile to get more control: --binding-args="--rankfile myrankfile"

Add process binding arguments to horovodrun

---

horovod/run/elastic/driver.py
horovod/run/gloo_run.py
horovod/run/http/http_server.py

some methods expose too much complexity, this simplifies the name for the caller

Renaming few functions to hide complexity

---

horovod/run/run.py

This reverts commit 5e822b50fab2aae0abde1533c346ee2cff47cbde.
Fix history following: https://github.community/t5/How-to-use-Git-and-GitHub/Authorship-of-merge-commits-made-by-Github-Apps-changed/td-p/48797

Revert "Add mpi_args to horovod.run.run (#1770)"

---

setup.py

In some setups, Horovod will be installed along with other dependencies at once, and the pip compiler will use the dependency graph to determine the package install order.  This can create problems if TensorFlow, PyTorch or MXNet are listed as dependencies in the same file:
```
...
tensorflow==1.15
horovod
```
In this case, pip may decide to install Horovod before TensorFlow, because Horovod does not explicitly depend on any framework.  Now, users can optionally declare that TensorFlow must be installed before Horovod, or it will be installed as part of installing Horovod:
```
...
tensorflow==1.15
horovod[tensorflow]
```
Note that because this information is not passed to `setup.py`, it cannot be used to enforce that Horovod must build successfully with any particular framework.  As such, …

Added extras_require to ensure Horovod is installed after frameworks

---

Jenkinsfile.ppc64le

WMLCE 1.7.0 has CUDA 10.2, NCCL 2.5.6, TensorFlow 2.1.0, and PyTorch 1.3.1

Move Power CI to WMLCE 1.7.0

---

horovod/common/controller.cc
horovod/common/controller.h
horovod/common/gloo/gloo_controller.cc
horovod/common/gloo/gloo_controller.h
horovod/common/mpi/mpi_controller.cc
horovod/common/mpi/mpi_controller.h

In elastic mode, new workers will start with an empty cache.  If existing workers retain their cache, it can lead to segmentation faults due to inaccurate assumptions about the presence or absence of certain keys in the cache.
In the future, it may be worth exploring ways to allow for caches to be out of sync, or to synchronize them during the initial startup process of the new workers.

Clear response cache during controller initialization process

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml

See: https://github.com/pypa/setuptools/issues/2041
Estimators are currently incompatible with the latest version of TensorFlow due to the inability to pickle `tf.function` objects.  This will be evaluated again once https://github.com/tensorflow/tensorflow/pull/37837 lands.

Pin setuptools<46 and disable tf-nightly tests for estimators

---

docs/benchmarks.rst

Added missing -H param to benchmark docs

---

README.rst
docs/index.rst
docs/lsf.rst
docs/lsf_include.rst
docs/summary.rst
horovod/run/driver/driver_service.py
horovod/run/js_run.py
horovod/run/mpi_run.py
horovod/run/run.py
horovod/run/util/lsf.py
horovod/run/util/network.py
test/test_run.py

Example to run on a LSF cluster (e.g. Summit):
horovodrun python train.py
Also, perform cpu/mem process binding to get the best performance.
Contributors:
@bethune-bryant
@nvcastet

Add LSF and jsrun support to horovodrun

---

horovod/_keras/__init__.py

See: https://github.com/tensorflow/tensorflow/issues/37765#issuecomment-603496575
TensorFlow team had to rename this variable in order to avoid breaking other parts of their code.  Because this code has not been released yet, this change is safe to make to optimizer.

Renamed _HAS_ALL_REDUCE_SUM_GRAD to _HAS_AGGREGATE_GRAD for TensorFlow 2.2 changes

---

horovod/run/js_run.py
test/spark_common.py
test/test_adasum_pytorch.py
test/test_adasum_tensorflow.py
test/test_keras.py
test/test_mxnet.py
test/test_run.py
test/test_spark.py
test/test_tensorflow.py
test/test_timeline.py
test/test_torch.py

Make skipped tests explicit and provide a reason.
Use `common.temppath` for temporary files and auto-delete them after use.
Fixe race condition in `test_run.py` where `/tmp/hostfile` is being written by both MPI threads and one reads the unfinished file of the other thread and fails. Now both use unique temporary filename.

Harmonize unit tests

---

horovod/run/driver/driver_service.py
horovod/run/js_run.py
horovod/run/mpi_run.py
horovod/run/util/network.py
horovod/spark/__init__.py
test/test_run.py

There are some more places where `common_intfs` is mentioned. Renaming those to `nics` as well for sake of naming consistency.

More renaming of common_intfs to nics (cf. #1808)

---

docker-compose.test.yml
examples/pytorch_imagenet_resnet50.py
examples/pytorch_mnist.py

Some Infiniband implementations are not fork-safe (e.g. Summit MPI)
In this case PyTorch recommands to use 'forkserver' or 'spawn' to start
the dataloader workers.
See warning at https://github.com/pytorch/pytorch/blob/3789db40f20156f1c5fb5a8da3f26a613edcdf28/torch/nn/parallel/distributed.py#L137
To use 'forkserver' or 'spawn', the global state of the main script
needs to be nested under "if __name__ == '__main__':" to prevent the spawned
processes from re-executing the code.
See https://docs.python.org/3/library/multiprocessing.html#programming-guidelines

Use forkserver for pytorch dataloader

---

horovod/run/js_run.py
horovod/run/mpi_run.py
horovod/spark/gloo_run.py
horovod/spark/mpi_run.py
horovod/spark/runner.py
test/test_run.py
test/test_spark.py

Replaces method injection with better `mock.patch` approach in unit testing.
Removes `run_func` from `mpi_run` and `js_run`.
Removes `exec_command` from `gloo_run`.
Removes `execute` from `_get_mpi_implementation`.
Conflicts with #1807, should be merged later.

Remove method injection from testing.

---

horovod/run/common/util/network.py
horovod/run/driver/driver_service.py
horovod/run/js_run.py
horovod/run/mpi_run.py
horovod/run/runner.py
horovod/run/task/task_service.py

Horovod can be run from API as well, not just from the
horovodrun convenience script. Log and error messages
referring to horovodrun may be confusing then, especially
running Horovod on Spark.

Rename horovodrun to horovod in strings and comments

---

setup.py

to simplify CPU-only build:
requirements.txt:
~~~
tensorflow-cpu==2.1.*
horovod[tensorflow-cpu]==0.19.*
~~~
tensorflow-cpu package is around 100MB while tensorflow or tensorflow-gpu packages are around 400MB

Add [tensorflow-cpu] extra

---

.buildkite/gen-pipeline.sh
horovod/run/common/service/task_service.py
horovod/run/common/util/env.py
horovod/run/mpi_run.py
horovod/run/task/task_service.py
horovod/spark/driver/mpirun_rsh.py
horovod/spark/driver/rsh.py
horovod/spark/gloo_run.py
horovod/spark/mpi_run.py
horovod/spark/runner.py
horovod/spark/task/mpirun_exec_fn.py
horovod/spark/task/task_service.py
test/common.py
test/data/expected_buildkite_pipeline.yaml
test/test_buildkite.py
test/test_run.py
test/test_spark.py

MPI runs the training function via `orted` in the directory where `mpirun` is executed on the driver. Each Spark worker has a unique working directory. That working directory contains important files provided by Spark to the worker and python code.
This refactors how `SparkTaskService` passes environment variables to `BasicTaskService`. Used to be environment variable names where `BasicTaskService` picks the value from the worker's `os.environ`, where `SparkTaskService` now provides a dictionary with the override values. This dict is initialized with `os.environ` so `SparkTaskService` uses the entire worker's env. This env is overwriten by the command request's env. `HorovodRunTaskService` uses request's env only.
This further provides `HOROVOD_SPARK_WORK_DIR` with the working directory …

Make train fn see Spark worker's environment

---

horovod/run/common/service/task_service.py
horovod/run/common/util/network.py
horovod/run/runner.py
horovod/run/task/task_service.py
horovod/run/task_fn.py

Variables `retries` actually denote `attempts` semantics:
for iter in range(self._retries)
There is the first attempt and then a number of retries. Setting retries to 0 should still perform the first attempt. So naming these variables attempts makes it obvious that 0 is not a sensible value.
You could even say:
for retry in range(self._attempts)
where `retry == 0` is the first attempt and `retry > 0` is the index of retry happening (1, 2, ..., `attempts` - 1). This expression becomes more meaningful then:
if retry == self._attempts - 1:
raise

Renaming retries to attempts

---

horovod/run/common/service/task_service.py
horovod/run/common/util/network.py
horovod/run/common/util/safe_shell_exec.py
horovod/run/http/http_server.py
horovod/run/util/threads.py
horovod/spark/runner.py
horovod/spark/task/__init__.py
test/common.py
test/test_common.py
test/test_run.py

- Create a (daemon) thread with a single line: in_thread
- Create a thread that executes a function on an event: on_event
- Create a method that delays a parallel function call (for testing): delay
- Clean-up wait-on-event thread in safe_shell_exec

Move thread patterns into in_thread and on_event

---

horovod/run/common/util/safe_shell_exec.py
horovod/run/util/threads.py
test/test_run.py

The `forward_stream` method in `safe_shell_exec` looses the last line of stdout / stderr if it does not end with an EOL. Also adds tests around `safe_shell_exec.execute`.
**Note**: This includes PR https://github.com/horovod/horovod/pull/1869 so should be reviewed / merged after that.

Fix stdout / stderr reading issue and add tests

---

horovod/run/common/service/driver_service.py
horovod/run/common/util/network.py
horovod/spark/runner.py
horovod/spark/task/task_service.py
test/test_spark.py

In Elastic Horovod on Spark we have to refactor the `_task_fn` because tasks that start after initial registration of `num_proc` will still need to go through the task-to-task-addresses registration, but tasks do not have enough knowledge about 'the next task', so the driver node should decide which task registers which 'neighbour' task's addresses.
Notable change is that the task service now creates a task client, connects to the neighbour task service and returns the addresses to the service's client: https://github.com/horovod/horovod/pull/1896/files#diff-01388c5900727b90e6d99c70abc42d7aR79-R87
**Question**: `horovod.run.driver.driver_service._driver_fn` uses the same logic to determine task-to-task-addresses from the Horovod workers. That logic could be refactored as well so that …

Move task address registration into lancher

---

horovod/common/controller.cc
horovod/common/message.cc
horovod/common/message.h
horovod/common/tensor_queue.cc
horovod/common/tensor_queue.h
setup.py

This PR contains mostly small changes to improve the latency of the background thread loop. Mostly comprised of using references and `std::move` when possible to avoid extraneous copies. Also introduces `TensorQueue::PushMessagesToQueue` method to avoid repeatedly taking a lock on a mutex when replacing uncached messages to the state queue in the previous logic when each message was replaced individually with `TensorQueue::PushMessageToQueue`. Lastly, changes default CPU compilation flags to `-O3` from `-O2`.

Various changes to improve latency of background thread loop.

---

horovod/common/common.cc
horovod/common/common.h
horovod/common/operations.cc
horovod/common/ops/ccl_operations.cc

This PR converts the ability to set the Horovod background thread affinity from a CCL backend specific option to one that is generally available. This is controllable via the new environment variable `HOROVOD_THREAD_AFFINITY`. The behavior of the existing `HOROVOD_CCL_BGT_AFFINITY` environment variable is retained.

Enable setting Horovod background thread affinity in general.

---

README.rst
docs/summary.rst

This PR is about adding Polyaxon to the list of platforms that support Horovod on Kubernetes.
Polyaxon is an open source ML platform for Kubernetes and it has been supporting Horovod since 2018.
It has 2 ways to manage Horovod:
* [Native implementation](https://docs.polyaxon.com/integrations/horovod/)
* [MPI Operator implementation](https://docs.polyaxon.com/integrations/mpi/)

Add polyaxon as a platform to run Horovod on K8S

---

setup.py

Remove torchvision from pytorch extra

---

horovod/common/common.cc
setup.py

#1881 uses instructions not available on macOS.  This change avoids compiling with those instructions outside of Linux operating systems.

Fix compilation on macOS by disabling HOROVOD_THREAD_AFFINITY

---

horovod/run/driver/driver_service.py

Fixes #1851.  This occurrence was missed during a rename in #1808.

Fixed usage of settings.nics to use the new parameter name

---

test/test_spark.py

Fix Spark tests by ensuring that process 0 always reports the earliest timestamp

---

horovod/spark/common/estimator.py

When I run the following code, currently I can not see the verbose=2 log from horovod.spark.runner like the generated mpirun command. We can create SparkBackend by using this verbose value to see the logs.
```
keras_estimator = hvd.KerasEstimator(num_proc=args.num_proc,
store=store,
model=model,
optimizer=opt,
loss='mae',
metrics=[exp_rmspe],
custom_objects=CUSTOM_OBJECTS,
feature_cols=all_cols,
label_cols=['Sales'],
validation='Validation',
batch_size=args.batch_size,
epochs=args.epochs,
verbose=2)
```

Pass verbose from Estimator to SparkBackend

---

horovod/mxnet/__init__.py

Fixes a bug introduced by #1718. In that commit, some syncs were removed in `broadcast_parameters`. This led to an issue where back to back calls to `broadcast_parameters` would possibly crash due to duplicate name usage, as the broadcast calls within that function use `str(i)` for naming, where `i` is just an index in the list of tensors. 
These back to back calls commonly arise when running symbolic models in MXNet, for example in the MXNet RN50 example script:
```
(arg_params, aux_params) = mod.get_params()
if arg_params is not None:
hvd.broadcast_parameters(arg_params, root_rank=0)
if aux_params is not None:
hvd.broadcast_parameters(aux_params, root_rank=0)
```
To fix this, we can replace the `str(i)` naming for the broadcasts with the actual parameter names. 
On a similar note, I …

Use parameter names when scheduling broadcasts in MXNet broadcast_parameters.

---

setup.py

Hi guys.
We are using Horovod/Gloo to distribute TensorFlow training on our Hadoop cluster. To do so, we build a wheel which fits our needs and which we publish on our private repository. When building the wheel, we would like to be able to add a local version to the public version so that:
- We clearly identify our local builds to public builds.
- We can build multiple time the same public version of Horovod, with different version of TensorFlow for example.
In this PR, I follow recommendations of https://www.python.org/dev/peps/pep-0440/#public-version-identifiers
What do you think ? Thanks.

Added optional local version to package version

---

NOTICE
docs/mocks.py
horovod/torch/__init__.py
horovod/torch/sync_batch_norm.py
test/test_torch.py

Implementation of https://pytorch.org/docs/stable/nn.html#syncbatchnorm using Horovod.  Current version uses optimized CUDA kernels written for PyTorch and have two different invocations because they changed.  We can consider making our own implementation if it turns out to be a hassle.
As evidenced by https://arxiv.org/abs/1804.07612, small batches are great for training neural networks.  However, https://arxiv.org/abs/1803.08494 noted that multi-GPU training with small-batch BatchNorm is detrimental to performance.
SyncBatchNorm improves training where each worker can only hold few examples (1..4) and total number of workers is not too high - at which point it starts to lose its regularization abilities.
Fixes #1384

Sync Batch Norm for PyTorch

---

docs/mocks.py
examples/keras_imagenet_resnet50.py
examples/keras_mnist_advanced.py
examples/keras_spark3_rossmann.py
examples/keras_spark3_rossmann.py.patch
examples/keras_spark_rossmann_run.py
examples/tensorflow2_keras_mnist.py
horovod/_keras/callbacks.py
horovod/common/util.py
horovod/keras/callbacks.py
horovod/tensorflow/__init__.py
horovod/tensorflow/keras/callbacks.py
horovod/torch/mpi_ops.py
horovod/torch/sync_batch_norm.py
setup.py

Fixes #1921.
Adds deprecation warnings with removed versions.
Fixes docs for SyncBatchNorm.

Added optional initial_lr parameter to LearningRateScheduleCallback and updated docs

---

horovod/spark/keras/remote.py
test/test_spark_keras.py

Fixed the following exception when num_proc in KerasEstimator is larger than 4 using tensorflow 2.0. I found in horovod/spark/keras/remote.py `calculate_shuffle_buffer_size`,  the `max_local_size ` was a tensor so it caused the following error.
```
[1,6]<stderr>:  File "/home/yuzhou/miniconda3/envs/horovod2/lib/python3.6/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 57, in <module>
[1,6]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
[1,6]<stderr>:  File "/home/yuzhou/miniconda3/envs/horovod2/lib/python3.6/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 50, in main
[1,6]<stderr>:    task_exec(driver_addresses, settings, 'OMPI_COMM_WORLD_RANK')
[1,6]<stderr>:  File "/home/yuzhou/miniconda3/envs/horovod2/lib/python3.6/site-packages/ho …
```

Fix exception when the number of training process in Spark Estimator is large

---

.buildkite/gen-pipeline.sh
horovod/run/common/service/task_service.py
horovod/run/common/util/network.py
horovod/run/runner.py
horovod/run/util/threads.py
horovod/spark/driver/rsh.py
horovod/spark/gloo_run.py
horovod/spark/runner.py
test/data/expected_buildkite_pipeline.yaml
test/test_run.py
test/test_service.py
test/test_spark.py
test/test_spark_keras.py
test/test_spark_torch.py

This completes the new Spark over Gloo implementation by making `exec_command` in `horovod.spark.gloo_run` wait for the command executed via `rsh` and return its exit code. Further it reacts on the given `event` and aborts the command in that case.
For this, the `BasicTaskClient` can send `WaitForCommandExitCodeRequest` which blocks until command terminates on the service and returns its exit code. Turns the polling loop that sends a `CommandTerminatedRequest` request every second into an event-base notification by pushing the loop into the service. In static Horovod over Spark these requests are sent over localhost, but elastic Horovod on Spark will use this to wait for training functions' termination, which would send a request per second to each task service over the network. …

rsh returns exit code for horovod.spark.gloo_run

---

horovod/run/runner.py
horovod/run/util/lsf.py
test/test_run.py

1- Remove _get_driver_ip from LSF code path (inserted by #1807)
2- Switch query from LSB_JOBID to CSM_ALLOCATION_ID because LSB_JOBID
may point to several allocations
Also, add unit test for bug 1.

Fix horovodrun LSF feature

---

.buildkite/gen-pipeline.sh
test/data/expected_buildkite_pipeline.yaml

That one expression where we removed `${test} == *"py2"*` should have been removed all together. The diff of `test/data/expected_buildkite_pipeline.yaml` showed that some unrelated Python3 tests have been removed from `gen-pipeline.sh` output: https://github.com/horovod/horovod/pull/1954/files#diff-4e74656e364613b7a60c371254085f11L760
Amends #1954.

Remove and fix more Python2 conditions

---

docs/mpirun.rst

Fix outdated links in `docs/mpirun.rst` as some files have been renamed.

Fix outdated links

---

horovod/run/common/util/settings.py
horovod/spark/driver/mpirun_rsh.py
horovod/spark/driver/rsh.py
horovod/spark/gloo_run.py
horovod/spark/mpi_run.py
test/test_run.py
test/test_spark.py

Fixes #1969 **and** keeps key away from serialized `settings` when running on Spark.

Don't serialize the key in settings with Spark

---

horovod/tensorflow/__init__.py

It seems that Mixed Precision Keras policy is currently in broken state when used combined with Horovod. If you use the test repository, you can reproduce the issue (you will need 2+ GPUs) https://github.com/DEKHTIARJonathan/TF_HVD_Stability_Test.
The issues comes by the sequence of operations:
1. set_visible_devices()
2. define Keras Policy
**Reproducible Test Case:**
```bash
#!/usr/bin/env bash
export HOROVOD_GPU_ALLREDUCE=NCCL
export HOROVOD_GPU_BROADCAST=NCCL
export HOROVOD_NCCL_INCLUDE=/usr/include
export HOROVOD_NCCL_LIB=/usr/lib/x86_64-linux-gnu
export HOROVOD_NCCL_LINK=SHARED
export HOROVOD_WITHOUT_PYTORCH=1
export HOROVOD_WITHOUT_MXNET=1
export HOROVOD_WITH_TENSORFLOW=1
export HOROVOD_WITH_MPI=1
export HOROVOD_BUILD_ARCH_FLAGS="-march=sandybridge -mtune=broadwell"
pip uninstall …
```

Keras Mixed Precision Policy and Horovod are incompatible with Tensorflow 2.2

---

test/test_tensorflow.py

Simple fix in unittests to avoid having a unittest failure in case only one GPU is available.

Multi GPU unittest skip if only one GPU is available

---

build-docker-images.sh

`pip freeze` for latest PyTorch produces difficult to parse output:
```
$ pip freeze | grep torch
torch @ https://download.pytorch.org/whl/cu101/torch-1.4.0-cp36-cp36m-linux_x86_64.whl
```
This change uses the `pip show` command instead, which provides the correct output:
```
$ pip show torch | grep Version | awk '{print $2}'
1.4.0
```

Fixed example Docker image tags for latest PyTorch versions

---

horovod/run/mpi_run.py
test/test_run.py
test/test_spark.py

The os.environ cannot be pickled as it is not a `dict` but `os._Environ`:
AttributeError: Can't pickle local object '_createenviron.<locals>.encode'
Exception now reads `env argument must be a dict, not <class 'os._Environ'>: …`
Fixes #2037

Call to mpi_run with os.environ should fail with useful exception

---

Dockerfile.test.cpu
Dockerfile.test.gpu
horovod/torch/mpi_ops_v2.cc
test/test_torch.py

This change is for compatibility with upcoming PyTorch 1.6.0 release which removes support for `tensor.div_` for integral tensors.  
See: https://github.com/pytorch/pytorch/pull/38620.

Replaced integral division with explicit floor division for PyTorch

---

docker-compose.test.yml

See https://github.com/keras-team/keras/issues/14129, which removes dependency on tensorflow.

Unpin Keras following 2.4.2 release

---

horovod/common/ops/cuda_operations.cc
horovod/common/ops/gpu_context_impl.cc
horovod/common/ops/gpu_operations.cc
horovod/common/ops/gpu_operations.h
horovod/common/ops/hip_operations.cc
horovod/common/ops/nccl_operations.cc
horovod/common/ops/nccl_operations.h

Follow-up from a discussion in #1849 regarding handling networking failures (due to removed workers) gracefully in NCCL.
This follows the approach outlined by NVIDIA in https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/communicators.html#asynchronous-errors-and-error-handling.

Added NCCL async error handling

---

.buildkite/gen-pipeline.sh
test/data/expected_buildkite_pipeline.yaml
test/spark_common.py
test/test_run.py
test/test_spark.py

This fixes broken tests from removing `num_hosts` from settings (#2059) and `PYTHONPATH` injection into environment variables for MPI (#2038). Latter test were broken when run without `PYTHONPATH` set, which is true on buildkite. Adds specific tests for `PYTHONPATH` and `PATH` env injection and removes asserts from other more general tests.
Fixes silent failure of pytest so that above errors surfaces in buildkite unit tests again.

Fix test_run.py after removing num_hosts from settings

---

.buildkite/gen-pipeline.sh
horovod/run/common/service/driver_service.py
horovod/run/common/service/task_service.py
horovod/run/common/util/network.py
horovod/run/elastic/driver.py
horovod/run/gloo_run.py
horovod/spark/driver/driver_service.py
horovod/spark/driver/rendezvous.py
horovod/spark/runner.py
horovod/spark/task/task_service.py
test/common.py
test/data/expected_buildkite_pipeline.yaml
test/integration/data/elastic_torch_main.py
test/integration/elastic_spark_common.py
test/integration/test_elastic_spark_tensorflow.py
test/integration/test_elastic_tensorflow.py
test/integration/test_elastic_torch.py
test/spark_common.py
test/test_spark.py

Elastic Horovod on Spark auto-scale

---

horovod/spark/keras/util.py

When the `make_dataset` function is pickled and sent to the remote workers, TensorFlow's Autograph system attempts to convert it into the graph, but in the process changes the behavior, resulting in tensors with invalid shapes being fed to the Keras model.  This PR disables autograph in affected versions of TensorFlow.

Wrap dataset generation function to disable autograph to fix issues with invalid tensor shapes

---

README.rst
docs/summary.rst

Adding [a tutorial on Horovod](https://spell.ml/blog/distributed-model-training-using-horovod-XvqEGRUAACgAa5th) with some benchmarks I wrote to the `Guides` section of the `README`.
We have a native `horovod` integration built into @spellrun, so I went ahead and wrote a tutorial explaining how it works and providing some benchmarks comparing it to `DataParallel` and `DistributedDataParallel` in PyTorch. `horovod` looks very appealing in these:
The Horovod `README` mentions open pull requests for user guides, and I think this would can be a good resource for anyone looking to learn how it works, hence this pull request.

Include new Horovod tutorial in README

---

horovod/common/ops/cuda_operations.cc
horovod/common/ops/hip_operations.cc

This removes the `cudaEventBlockingSync` flag when creating `cudaEvent`s in Horovod. Blocking adds additional latency and should not be preferred over the default behavior.

Remove blocking sync flag from cudaEvents.

---

horovod/mxnet/mpi_ops.cc
horovod/mxnet/mpi_ops.h
horovod/mxnet/mpi_ops.py
test/test_mxnet.py

Fixes #1409 and fixes #1669.
This PR makes fixes the MXNet allgather implementation. The existing implementation did not correctly handle resizing the output buffer for allgather with issues described in an old unmerged PR #1424 and issue #1669. 
In one scenario, the use of a shallow copied tensor for the output resulted in modifications of the tensor shape not being propagated to the output Python tensor. This is remedied by passing the real output tensor into Horovod to be modified by the allgather op (and adding sync to ensure that the output tensor is not returned until the operation that modifies this tensor completes).
In the path where the allgather operation is completed on the CPU with input and output GPU tensors, the implementation erroneously uses an in-place operation, but …

Fix MXNet allgather implementation.

---

horovod/tensorflow/__init__.py

Accessing TFv1's `tf.get_default_graph` can succeed but cause deprecation warnings. Accessing `tf.compat.v1` first can silence those warnings.

Update __init__.py to silence deprecation warnings

---

horovod/tensorflow/__init__.py
horovod/tensorflow/sync_batch_norm.py
test/test_tensorflow.py

This PR adds a `SyncBatchNormalization` layer implementation using Horovod for TensorFlow.  
Fixes #2066.

Add SyncBatchNormalization layer for TensorFlow.

---

CHANGELOG.md
CONTRIBUTING.md

@apeforest is going to be stepping back from maintaining Horovod + MXNet integration, and @eric-haibin-lin will be taking on his role on the TSC going forward.

Updated changelog and TSC members

---

docs/conda.rst

This PR address issue #2084 by adding a link to the GitHub repo containing the file referenced in the docs.

Added link to repo containing Conda environment.yml file

---

horovod/tensorflow/mpi_ops.py
test/test_tensorflow.py

I noticed that the implementation of the allreduce gradient in TF was not forwarding the reduction op type. This is the existing TF grad function:
https://github.com/horovod/horovod/blob/2157e4034ed4f603da2b7a78ef0505090d92016b/horovod/tensorflow/mpi_ops.py#L107-L117
compared to that in PyTorch where `op` is correctly passed in the allreduce for the gradient:
https://github.com/horovod/horovod/blob/2157e4034ed4f603da2b7a78ef0505090d92016b/horovod/torch/mpi_ops.py#L155-L156
This PR adds the proper forwarding of the reduction op in the allreduce gradient, and also adds tests for the allreduce gradient with averaging, using the `test_horovod_allreduce_grad_average` that already exists in `test_torch.py` as a template. I also added tests for allreduce with average in general for TF since …

Properly forward reduce_op attribute to TF allreduce gradient implementation

---

horovod/tensorflow/mpi_ops.py

In TensorFlow 2, when wrapping an `allgather` call with `tf.function`, the shape of the input tensor may not be known (e.g., `(None, 128)`), in which case the existing gradient computation will fail when it attempts to calculate the size of the first dimension, which is `None`.  This PR changes this behavior to use graph-compatible ops that can be evaluated lazily.
Fixes #2110.

Fixed allgather gradient for cases where the tensor shape is not known during graph construction

---

test/test_tensorflow.py

When testing Horovod in the 20.06 NGC TensorFlow container with `HOROVOD_GPU_ALLGATHER=NCCL`, I found that some of the allgather tests were failing due to not properly setting devices. Not sure why the Horovod CI testing does not catch these issues. This PR fixes issues I encountered by splitting the problematic tests into `_cpu` and `_gpu` variants (see `test_horovod_allgather_variable_size_*` tests), or fixing the scope of the with device statement in existing tests (see `test_horovod_allgather_grad_*` tests).

Fix TF allgather tests

---

horovod/mxnet/__init__.py
horovod/mxnet/functions.py
test/test_mxnet.py

Recently, `broadcast_object` functions were added for TensorFlow and PyTorch to enable broadcasting Python objects using Horovod. This PR adds a `broadcast_object` implementation for MXNet, based on the existing PyTorch implementation.

Add broadcast_object function for MXNet.

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Pandas 1.1.0 is incompatible with older versions of numpy, but these numpy versions are required by some older framework versions.  This results in the following error:
```
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pandas/compat/numpy/__init__.py", line 21, in <module>
[1,1]<stderr>:    "this version of pandas is incompatible with numpy < 1.15.4\n"
[1,1]<stderr>:ImportError: this version of pandas is incompatible with numpy < 1.15.4
[1,1]<stderr>:your numpy version is 1.14.6.
[1,1]<stderr>:Please upgrade numpy to >= 1.15.4 to use this pandas version
```
For testing, we pin pandas < 1.1.0 so older versions of numpy can be supported.

Pin pandas<1.1.0 for older framework versions that install old versions of numpy

---

horovod/spark/common/params.py
horovod/spark/common/util.py
horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/spark/keras/util.py
horovod/spark/torch/estimator.py
horovod/spark/torch/remote.py
test/test_spark.py

Add label_shapes parameter to KerasEstimator and TorchEstimator

---

CHANGELOG.md
docs/oneccl.md
horovod/common/common.cc
horovod/common/common.h
horovod/common/operations.cc

Signed-off-by: Yana Shchyokotova <yana.shchyokotova@intel.com>
Now HOROVOD_THREAD_AFFINITY accepts several values, one for every local Horovod rank to make the pinning easier to set for multi-socket systems.
In case parse function detects some errors, the pinning is skipped.

Set multiple affinity in one variable HOROVOD_THREAD_AFFINITY

---

test/test_mxnet.py
test/test_tensorflow.py
test/test_torch.py

Fixes incorrect usage of `os.environ.get('HOROVOD_MIXED_INSTALL')` to skip some tests. `os.environ.get()` returns a string and as a result, the tests with a check on this environment variable are always skipped. This is corrected by casting the string result to an integer.

Fix usage of HOROVOD_MIXED_INSTALL env var in tests.

---

horovod/common/ops/cuda_operations.cc
horovod/common/ops/hip_operations.cc
horovod/torch/mpi_ops_v2.cc

Some platforms, like certain macOS environments, do not have `pthread_yield` available.  
This change also makes the code consistent with `timeline.cc`, which uses this yield function.

Changed pthread_yield to this_thread::yield for cross platform compatibility

---

docs/install.rst
setup.py

Add a separate option for pip installation with mxnet cpu build (`pip install horovod[mxnet-cpu]`). By default `pip install horovod[mxnet]` requires the GPU build. https://github.com/horovod/horovod/issues/2141

add `pip install horovod[mxnet-cu102]`

---

horovod/tensorflow/mpi_ops.cc

The following commit breaks ROCm support for horovod-tensorflow
https://github.com/horovod/horovod/commit/7a1c761c663eb758536c1bff62d9d9c9a032dd38
horovod build fails because the `<cuda_runtime.h>` cannot be found on the ROCm platform
This PR/commit fixes the above breakage by including the HIP runtime file (instead of the CUDA one), when compiling with ROCm.
In addition to the above change, this commit also renames a couple of cuda* names to the corresponding gpu* versions instead.
/cc @jeffdaily

Fix for ROCm breakage - 200805

---

horovod/tensorflow/sync_batch_norm.py

This PR updates the TF sync BN implementation to derive from `tf.keras.layers.BatchNormalization` for Keras/TF2 compatibility.
Additionally, original code source was from another repository, so updating attribution/copyright to reflect this: https://github.com/google/automl/blob/master/efficientdet/utils.py

Updating TF syncbn for TF2/Keras compatibility. Updating code attribution.

---

horovod/mxnet/__init__.py
horovod/mxnet/functions.py
horovod/tensorflow/__init__.py
horovod/tensorflow/functions.py
horovod/torch/__init__.py
horovod/torch/functions.py
test/test_mxnet.py
test/test_tensorflow.py
test/test_torch.py

This provides a controller-agnostic function to allgather arbitrary Python objects, useful for metrics aggregation when using Gloo (or MPI without needing to install `mpi4py`).

Added allgather_object utility function for TensorFlow, PyTorch, and MXNet

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml
horovod/spark/keras/remote.py
horovod/spark/keras/util.py
horovod/tensorflow/util.py
setup.py
test/data/expected_buildkite_pipeline.yaml
test/integration/test_elastic_spark_tensorflow2.py
test/test_keras.py
test/test_spark_keras.py
test/test_tensorflow.py
test/test_tensorflow_keras.py

This change is required for #2147 as latest version of Gloo requires GCC >= 5.
Related to #2030.

Upgraded min supported TensorFlow version to 1.15

---

horovod/torch/handle_manager.cc
horovod/torch/handle_manager.h
horovod/torch/mpi_ops.py
horovod/torch/mpi_ops_v2.cc

- [ YES ] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ N/A ] Did you update the docs?
- [ N/A ] Did you write any tests to validate this change?  
- [ N/A ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?
The controller will be blocked after do scale up workers action when using **Elastic Horovod** with PyTorch.
This issue only happen in PyTorch because PyTorch need a **handle** to record a uniq tensor name index. This **handle** variable will not be reset during horovod shutdown.   
For example:   
Now we running in one worker:   
* An tensor name of rank0 is **allgather.noname.6**   
Do scale up worker to 2:   
* The first tensor name of rank0 is …

[PyTorch] reset handle when horovod shutdown

---

horovod/tensorflow/__init__.py
horovod/tensorflow/mpi_ops.cc

Recent experiments I've run indicate that the use of `size_op()` and `local_size_op()` in the TF `DistributedOptimizer` can result in degraded performance. To recover performance in non-elastic cases, this PR limits the use of these ops to elastic cases only.
This PR also corrects the use of `HOROVOD_GPU_BROADCAST` with `HAVE_GPU` to determine when to build GPU versions of these scalar ops.

Limit usage of size_op and local_size_op to elastic cases.

---

examples/elastic/pytorch_synthetic_benchmark_elastic.py

When new workers are added, these broadcasts would cause deadlock.  In elastic mode, broadcast is handled through the `sync` method.

Removed initial broadcast from elastic example

---

test/test_tensorflow.py

During local testing, test failures were arising due to the existing TF sync BN tests. This PR updates the test to compare against the `tf.keras.layers.BatchNormalization` base layer from the change introduced in #2163, and also explicitly sets `fused=False` as that is what the `hvd.SyncBatchNormalization` implementation currently enforces.

Fix TF syncbn test.

---

horovod/runner/common/util/env.py
horovod/runner/driver/driver_service.py
horovod/runner/gloo_run.py
horovod/runner/launch.py
horovod/runner/util/lsf.py
horovod/runner/util/remote.py

1. add ~~`is_mpi_job`~~ `is_kubeflow_mpi` under ~~`horovod/run/common/util/env.py`~~ `horovod/runner/common/util/env.py` for determining whether the environment was setup by kubeflow/mpi-operator
~~2. for all shell command with `ssh`, add revision for mpi-job with `/etc/mpi/kubexec.sh`~~
2. wrap `get_ssh_command` with `get_remote_command` to support other shell tools.
Fixes #2198.

Add support for horovodrun on kubeflow/mpi-job

---

setup.py

When `nvcc` was not available on the PATH, it was resulting a cryptic failure. This PR will now check for both `nvcc` on the path and `nvcc` in `HOROVOD_CUDA_HOME` or `/usr/local/cuda`. If no `nvcc` binary can be found, an error is raised guiding the user to ensure `nvcc` is available in their path.

Check for nvcc in HOROVOD_CUDA_HOME in addition to PATH

---

horovod/mxnet/functions.py
horovod/tensorflow/functions.py
horovod/torch/functions.py

When running with `np > 2` this becomes an issue as the `size[2]` does not correspond to the `offset[2]`.

Fixed computation of the offset when using allgather_object

---

horovod/common/gloo/gloo_context.cc
horovod/runner/common/util/hosts.py
horovod/runner/http/http_server.py
setup.py
test/test_run.py
test/test_spark.py

When running a Gloo job with heterogeneous workers (uneven distribution of processes / GPUs per worker), the driver would incorrectly assign the cross rank, resulting in runtime failures.
cc @richardliaw

Fixed issue with cross rank in heterogeneous Gloo jobs

---

.github/workflows/docs-summary.yml
.github/workflows/examples-keras-spark3-rossmann.yml

The `pull_request` is the wrong event, that triggers whenever a PR is modified (includes adding comments, reviews, ...), `push` is the right event.
Duplicates #2220.

Run these github workflows on push events

---

horovod/common/ops/cuda_operations.cc

Disable cudaGetLastError to avoid errors when running on colocated containers

---

horovod/common/ops/cuda/CMakeLists.txt

If I build the current Horovod master with TF 1.15.2 on Ubuntu 16.04 (cmake version 3.5.1), `import horovod.tensorflow` fails with
```
NotFoundError: .../lib/python3.7/site-packages/horovod/tensorflow/mpi_lib.cpython-37m-x86_64-linux-gnu.so:
undefined symbol: _ZN7horovod6common13DataType_NameB5cxx11ENS0_8DataTypeE
```
(demangled: `horovod::common::DataType_Name[abi:cxx11](horovod::common::DataType)`)
I noticed that `-D_GLIBCXX_USE_CXX11_ABI=0` had not been passed to the compiler when building `compatible_horovod_cuda_kernels`, but this would have been necessary with the Tensorflow package from PyPI. This patch fixes that and the import works fine on my system now.
2. At least one member of the [technical steering …

Fix setting -D_GLIBCXX_USE_CXX11_ABI=0 when compiling CUDA kernels

---

.github/workflows/buildkite_unit_tests.yml

Buildkite does not run on master push event but on schedule, the download action will not be able to pick this up in a timely manner. Buildkite does not run on tags either. No need to run the workflow for those.

Don't run the Unit Tests workflow on master or tags

---

Dockerfile.test.cpu
docs/contributors.rst
setup.py

This simplifies initial setup of an development environment by invoking
```
pip install -e .[dev]
```
Rather than extracting the dependencies from documentation.
Note: this contains #1698, which is unrelated to this PR and should go into master first.

Add dev to extras_require in setup.py

---

.github/workflows/buildkite_unit_tests.yml

The Buildkite artifact download action did only download the first 100 artifacts, but Horovod has 483 (!). Move to the latest version of the action that fixes this.
Further, to avoid more disruptions, this moves to master so in case there is another bug in the actions I can fix them in actions' master and rerun the workflow without rerunning Buildkite (and waiting hours and raising the AWS bill).
With `continue-on-error: true`, those workflows won't fail on these actions. I keep an eye on them. Thanks for letting me test these actions here, if they work for Horovod, they work everywhere.

Download all BuildKite artifacts

---

.github/workflows/buildkite_unit_tests.yml

The new Unit Tests github workflow does not work for PRs from forked horovod repos because they run in the context of the forked repo and thus do not have the BuildKite token.
Until I have a solution for this situation, lets not run the actions in forked repos.

Do not fetch unit tests in forked horovods

---

test/test_tensorflow.py

Fixes incorrect usage of os.environ.get('HOROVOD_MIXED_INSTALL') to skip GPU-based tests of `alltoall` in `test_tensorflow.py`. (This is completely analogous to #2151)

Fix usage of HOROVOD_MIXED_INSTALL env var in alltoall tests

---

.buildkite/gen-pipeline.sh
test/test_buildkite.py

The `test_gen_pipeline_with_code_changes` test seems to be flaky: https://buildkite.com/horovod/horovod/builds/3759#3dbfa9f4-6965-4ca2-9245-44bf25918f8a and https://buildkite.com/horovod/horovod/builds/3759#abb99246-f4b4-4871-a471-2f7673efd7d1.

Fix flaky buildkite test

---

horovod/keras/elastic.py
horovod/tensorflow/keras/elastic.py

- [ yes ] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ N/A ] Did you update the docs?
- [ N/A ] Did you write any tests to validate this change?  
- [ N/A ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?
Can not run examples/elastic/tensorflow_keras_mnist_elastic.py in elastic mode.
1. missing run decorator in elastic.py file. Just import it and working well now.
3. If any member of the technical steering committee requests changes, they must be …

Fixed missing run in tf keras elastic mode

---

CMakeLists.txt

This fixes building Debug builds.
Further remove the ` set(CMAKE_CXX_FLAGS "$ENV{CPPFLAGS} ${CMAKE_CXX_FLAGS}")` line, as cmake already reads `CXXFLAGS` by default and there is no need to handle a non-standard `CPPFLAGS` environment variable.

Set compiler options based on cmake build type

---

CHANGELOG.md
horovod/common/basics.py
horovod/common/controller.cc
horovod/common/controller.h
horovod/common/global_state.h
horovod/common/operations.cc
horovod/common/timeline.cc
horovod/common/timeline.h
horovod/keras/__init__.py
horovod/mxnet/__init__.py
horovod/mxnet/mpi_ops.py
horovod/tensorflow/__init__.py
horovod/tensorflow/keras/__init__.py
horovod/tensorflow/mpi_ops.py
horovod/torch/__init__.py
horovod/torch/mpi_ops.py
test/test_timeline.py
test/test_torch.py

This PR 
1)introduces a new Python API for starting and stopping the timeline:
```
hvd.start_timeline('/path/to/timeline.json', mark_cycles=True)
...
hvd.stop_timeline()
```
2) Makes sure that timeline json file is valid json. 
3) Including starttime as metadata in timeline.
TODO
1/ thread detach() re-introduce. 
Fixes #2008.
This is followup from this PR: https://github.com/horovod/horovod/pull/2129 and addresses concurrent access. 

Dynamic timeline

---

CHANGELOG.md
docs/spark.rst
horovod/spark/common/store.py
horovod/spark/common/util.py
horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/spark/torch/remote.py
test/test_spark.py

* Add `DBFSLocalStore` that allows horovod.spark Estimator to use Databricks Filesystem local files API to persist intermediate data and training artifacts.
* Update the ways to pin GPU: when GPU-aware scheduling is available, pin GPU to the assigned GPU index from spark; otherwise, pin GPU to `hvd.local_rank()`.

Databricks supports horovod.spark.estimator

---

.github/workflows/buildkite_unit_tests.yml

This activates the unit test workflow for master branch again. Only merge this once Buildkite is configured to run on push to master (not only scheduled daily master builds).

Run unit test workflow on master, move if clause from steps to job

---

.github/workflows/buildkite_unit_tests.yml

My earlier change #2284 didn't consider the always-test-on-master-feature. You can see that the merge commit in master did kick off a full test run on Buildkite but the test workflow did not run. Not sure if this change fixes it. We can only test this in master.
With this merged into master, the test workflow should run on the merge commit though it is a non-code change.

Always test master

---

test/test_tensorflow.py

These "edge case" tests fail using the NCCL backend (see issue #2259)
1. test_horovod_alltoall_empty_gpu: `ncclGroupEnd failed: invalid usage`
2. test_horovod_alltoall_one_rank_receives_nothing_gpu: `ncclGroupEnd failed: invalid usage`
3. test_horovod_alltoall_zero_splits_gpu: `ncclGroupEnd failed: invalid usage`
This one passes: test_horovod_alltoall_one_rank_sends_nothing_gpu
*_cpu versions of all of these are OK, too.
Edit: 3. first showed a different NCCL error due to a bug in the test script

Tests for alltoall edge cases, some producing errors with NCCL 2.7.8-1 (#2259)

---

setup.py

This page contains nightly releases that are not intended for the use of the general public. They are provided as is for the purpose of testing for MXNet and ecosystem developers.

Remove dist.mxnet.io link from setup.py

---

.buildkite/gen-pipeline.sh
examples/elastic/tensorflow_keras_mnist_elastic.py
horovod/_keras/__init__.py
horovod/_keras/elastic.py
horovod/common/stall_inspector.cc
horovod/runner/elastic/driver.py
horovod/runner/launch.py
horovod/tensorflow/__init__.py
horovod/tensorflow/elastic.py
test/data/expected_buildkite_pipeline.yaml
test/integration/data/elastic_tensorflow_keras_main.py
test/integration/test_elastic_tensorflow_keras.py

Fixed Elastic tf.keras and added additional integration tests

---

docs/api.rst
docs/mocks.py
examples/elastic/pytorch_imagenet_resnet50_elastic.py
examples/elastic/pytorch_mnist_elastic.py
horovod/keras/elastic.py
horovod/tensorflow/elastic.py
horovod/tensorflow/keras/elastic.py
horovod/torch/elastic/__init__.py
horovod/torch/elastic/sampler.py
horovod/torch/elastic/state.py
test/test_torch.py
test/test_torch_elastic.py

Added ElasticSampler and PyTorch Elastic ImageNet example

---

horovod/tensorflow/__init__.py

For some reason, the `name` argument is not exposed in the public `allreduce` API for TF and is only available in the private `_allreduce` version. This PR adds the `name` argument to the TF `allreduce` to be more consistent with the other framework implementations.

Expose name argument to TF allreduce operation.

---

horovod/tensorflow/mpi_ops.py

This PR addresses an issue that arose with the TF `alltoall` gradient in a model parallel script (where workers may potentially building different graphs by rank). In that context, the current use of `tf.cond` would yield name mismatches in the first `alltoall` causing deadlocking. Solution is to not call `alltoall` inside the `tf.cond`, but instead use the conditional to determine the input and call the `alltoall` outside.

Update use of tf.cond in TF alltoall gradient.

---

cmake/Modules/FindMxnet.cmake

If the user did not specify `HOROVOD_WITHOUT_MXNET=1` then compilation would fail.
(NOTE: we should really setup CI without all frameworks installed).

Fix building Horovod when MXNet is not installed

---

CHANGELOG.md
horovod/__init__.py

This release adds Ray support for Elastic Horovod and removes dependency on SSH for Ray NIC discovery.

Bump version to 0.20.3

---

.github/workflows/buildkite_unit_tests.yml

There are more Buildkite build states that we want to ignore than just skipped: `blocked`, `canceled`, `skipped` and `not_run`

Unit test workflow ignores more build states

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Installing `typing` with Python 3.8 (which already includes it) is resulting in build errors. 
See: https://github.com/psf/black/issues/1707

Remove typing from test Dockerfiles

---

horovod/common/ops/cuda/cuda_kernels.cu

A bug was introduced in #1949 where when using the half2 `ScaleBufferImpl` for CUDA, if the buffer is a single half element, division is skipped due to mishandled rounding to compute thread blocks for half2 usage. This PR fixes this case so that the scaling is completed correctly in this case.

Fix averaging using CUDA half2 implementation one element half buffers.

---

CHANGELOG.md
examples/tensorflow2/tensorflow2_keras_mnist.py
horovod/_keras/__init__.py
horovod/tensorflow/gradient_aggregation_eager.py
test/parallel/test_tensorflow2_keras.py

This PR is a follow up #2346. This PR adds support for backward_passes_per_step > 1 for TF Keras optimizers executing in graph(non-eager) mode. This is one of the features that we have built into [Determined AI's](https://determined.ai/) fork of Horovod that we would like to upstream.

Support backward_passes_per_step > 1 for TF Keras Eager Execution

---

docker-compose.test.yml
horovod/tensorflow/gradient_aggregation_eager.py

TF 2.4 nightly no longer supports using a `tf.Tensor` as a Python `bool` inside a
`@tf.function`.  
Fixes issue raised in: https://github.com/horovod/horovod/pull/2384

Fix eager gradient aggregation for TF 2.4 nightly.

---

horovod/common/operations.cc

I encountered a Nan problem during training when I modified part of the source code. However, the try-cache here makes everything go well, no warnings or errors raised. PerformOperation() just makes callback like normal.
I found it difficult to locate the error so I added logs line by line. Finally I found my problem occured in InitializeBuffer due to incorrect CUDA driver API useage, which led to failure in ExecuteOperation. Then I fixed it and continued my development.
I believe it would be a useful infomation for other developers.
Thx!

Add debug log in operation.cc

---

CHANGELOG.md
examples/tensorflow/tensorflow_mnist_estimator.py
horovod/tensorflow/__init__.py
horovod/tensorflow/gradient_aggregation.py
test/parallel/test_tensorflow.py

This PR is a follow up #2346. This PR adds support for backward_passes_per_step > 1 for TF legacy optimizers (tf.train.Optimizer) executing in graph(non-eager) mode. This is one of the features that we have built into[ Determined AI's](https://determined.ai/) fork of Horovod that we would like to upstream.

Add support for backward_passes_per_step > 1 for LegacyOptimizers (TF) in Graph Mode.

---

horovod/_keras/__init__.py
test/parallel/test_tensorflow2_keras.py

When users subclass `tf.keras.Model` and implement a custom `train_step()` it is possible
that the gradients and variables  passed into `apply_gradients()` are a zip object instead 
of a list. Starting with TF 2.4, we use the `grads_and_vars` object in both conditional loops inside
`apply_gradients()` when doing local gradient aggregation, which means that by the time that
the false condition was executed, the zip iterator would have gone through the list and the updates
were empty. This issue was not previously detected in out tests, because they were not executed
inside a `tf.function()`. 
3. If …

Correctly handle grads_and_vars passed in as zips for TF Keras 2.4 w/  local gradient aggregation

---

horovod/tensorflow/gradient_aggregation.py
test/parallel/test_tensorflow.py

When using a an Estimator.RunHook to broadcast variables we broadcast all 
global variables. This PR marks the counter used for local gradient aggregation
as a local variable to avoid having it broadcasted as part of this callback.
Fixes issue raised in comments of #2401.

Make counter for local gradient aggregation a local variable.

---

Dockerfile.cpu
build-docker-images.sh

Fixes #2425.
Was able to reproduce locally.  Using v1.7.0.post1 had a separate error, but 1.5.0 worked fine.

Use mxnet==1.5.0 for CPU Dockerfile until issues with 1.6.0 and 1.7.0 are resolved

---

CHANGELOG.md
horovod/_keras/__init__.py
horovod/tensorflow/keras/__init__.py

`tf.keras` allreaduce uses the `tensorflow` allreduce under the hood but does not currently match its API. This PR brings the `tf.keras` allreduce API (mostly) in line with the tensorflow API.

Update tf.keras hvd.allreduce() API to match tensorflow allreduce()

---

.github/workflows/buildkite_unit_tests.yml

Build can take up to 8 hours: https://buildkite.com/horovod/horovod/builds/4299
Increasing workflow timeout avoids failing unit test results on master.
Also reduces log level of Buildkite download and unit test result publisher actions as they are stable now.

Increase timeout to wait for Buildkite build to finish

---

horovod/tensorflow/gradient_aggregation.py

As pointed out by @Richie-yan in https://github.com/horovod/horovod/pull/2401, using `tf.zeros_initializer()` introduces additional memory overhead.

Reduce memory usage for TF1 gradient aggregation.

---

horovod/tensorflow/mpi_ops.cc

Signed-off-by: zhaoyuan.ye <zhaoyuan.ye@enflame-tech.com>
Add tensor() to get the TF tensor_‘s pointer  in TFTensor class.

Add tensor() in TFTensor class to get the TF tensor_'s pointer. (#2452)

---

CHANGELOG.md
horovod/common/operations.cc
horovod/runner/launch.py
test/single/test_run.py

It's been observed empirically that the default cycle time of 5ms is too long, resulting in excessively long pauses between allreduce calls.
Similarly, the fusion buffer threshold of 64MB if often too small for models such as ResNet50 with fp32 gradients.

Changed default cycle time from 5ms to 1ms and fusion threshold from 64MB to 128MB

---

CHANGELOG.md
CMakeLists.txt
horovod/mxnet/CMakeLists.txt
horovod/tensorflow/CMakeLists.txt
horovod/torch/CMakeLists.txt

Search a Tensorflow-provided or system installed version of
Eigen/Flatbuffers if it exists. Otherwise use Eigen/Flatbuffers from
submodules.
Fixes #2429 .

Fix the search order of Eigen/Flatbuffers path (#2429)

---

.travis.yml
test/integration/elastic_common.py
test/parallel/test_torch.py

See: #2496.
Also, changed Elastic tests to use assertEquals for better diagnostics.

Disable dynamic timeline tests due to macOS failures

---

CHANGELOG.md
horovod/spark/torch/estimator.py

TorchEstimator currently returns a model without switching to eval mode. This PR fixes that.

Set model.eval() in TorchEstimator before return

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Temporary workaround for the following install error:
```
In file included from /usr/local/lib/python3.6/dist-packages/mxnet/include/mkldnn/dnnl.hpp:20:0,
from /usr/local/lib/python3.6/dist-packages/mxnet/include/mkldnn/mkldnn.hpp:24,
from /usr/local/lib/python3.6/dist-packages/mxnet/include/mxnet/ndarray.h:41,
from /tmp/pip-req-build-gm88s5we/horovod/mxnet/mpi_ops.h:24,
from /tmp/pip-req-build-gm88s5we/horovod/mxnet/mpi_ops.cc:21:
/usr/local/lib/python3.6/dist-packages/mxnet/include/mkldnn/oneapi/dnnl/dnnl.hpp:23:10: fatal error: oneapi/dnnl/dnnl_config.h: No such file or directory
#include "oneapi/dnnl/dnnl_config.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
horovod/mxnet/CMakeFiles/mxnet.dir/build.make:758: recipe for target 'horovod/mxnet/CMakeFiles/mxnet.dir/mpi_ops.cc.o' …
```

Pin mxnet-nightly following missing file oneapi/dnnl/dnnl_config.h

---

.buildkite/gen-pipeline.sh
test/single/data/expected_buildkite_pipeline.yaml

New Buildkite queue allows us to do two things:
1. Updates Nvidia drivers to support CUDA 11.1.
2. Allocates 10% of the GPU instances to a dedicated pool to increase liveness.

Updated CI to use latest Buildkite stack

---

horovod/spark/common/constants.py
horovod/spark/torch/estimator.py
horovod/spark/torch/remote.py
setup.py

This diff enables in-memory caching for TorchEstimator using Petastorm. It is blocked until https://github.com/uber/petastorm/pull/555 is landed and a new petastorm is released. 

Enabling in-memory caching for TorchEstimator

---

CHANGELOG.md
horovod/spark/common/store.py

The issue is that on Databricks, DBFSLocalStore cannot correctly write intermediate files due to the previous PR #2376. I updated DBFSLocalStore to avoid overwriting the methods in the superclass: `matches` and `get_localized_path`, because those are needed for the underlying LocalStore to work correctly. The dbfs parsing logic should be defined in dedicated methods.
I manually tested the change on Databricks and it works well.

Avoid overwriting methods in the super class of DBFSLocalStore

---

CHANGELOG.md
CMakeLists.txt
cmake/Utilities.cmake
horovod/common/exceptions.py
horovod/common/util.py
horovod/mxnet/CMakeLists.txt
horovod/mxnet/mpi_ops.py
horovod/tensorflow/CMakeLists.txt
horovod/tensorflow/mpi_ops.py
horovod/torch/CMakeLists.txt
horovod/torch/mpi_ops.py

Check if the versions of supported frameworks match with horovod
installation. Throw out a warning to let users know that version is
mismatched, which could result in a possible undefined-symbol error
when using the framework.
Fixes #2518 .

add support to check supported frameworks versions (#2518)

---

docs/requirements.txt

Moves to PyPi package for sphinx, also moves to latest version (3.x rather than 2.x), This also saves 40MB download per build.

Move sphinx to pypi

---

CHANGELOG.md
horovod/common/elastic.py
horovod/common/exceptions.py
horovod/runner/elastic/discovery.py
horovod/runner/elastic/driver.py
horovod/runner/elastic/worker.py
test/single/test_elastic_driver.py

During recovery, if horovod knows only known slots and hosts are removed,
and no new hosts and slots are joining, then the sync of training
parameters can be skipped. All the shrinked workers already have
up-to-date parameters.
Fixes (https://github.com/horovod/horovod/issues/1876)

elastic: avoid sync if workers are only shrinked (#1876)

---

horovod/_keras/callbacks.py

TensorFlow issue https://github.com/tensorflow/tensorflow/issues/41851 causes
the logs to be out-of-sync for Callbacks for which _supports_tf_logs is True.
A warning is logged upon instantiation of a MetricsAverageCallback.

Add warning in MetricsAverageCallback regarding TF 2.3 issue with logs sync (#2440)

---

setup.py

See #2543.  We may revert this / replace with dynamic parallelism strategy once this issue is resolved.

Remove -j8 default when installing Horovod due to race condition

---

horovod/runner/launch.py
test/single/test_ray.py
test/single/test_run.py

These defaults were overriding the environment variables.  This restores the preferred priority:
1. Command line arg
2. Environment variable
3. Default

Removed arg defaults from horovodrun to allow env variable overrides

---

CHANGELOG.md
horovod/ray/runner.py
test/single/test_ray.py

[ray] fix local_rank issue

---

.github/workflows/buildkite_unit_tests.yml

Use latest version of these github actions to stay up-to-date. This also upgrades publish-unit-test-result-action to v1.7.

Use latest actions

---

README.rst
docs/gpus.rst
docs/index.rst
docs/install.rst
docs/summary.rst

Now that we even moved to g++-7 we should mention in the docs that g++-4.9 and above is fine.

Mention g++ above 4.9 is also fine

---

.github/workflows/buildkite_unit_tests.yml

This simplifies logic and removes empty unit test results being displayed.
We now rely on buildkite to fail when no test results are generated.
This avoids situations like: https://github.com/horovod/horovod/pull/2606#issuecomment-763143453

Only analyse test results when any file was downloaded

---

setup.py

These dependency links have been added for reference only and where thought to be ignore by pip, but there seem to be situations where they are picked up. Removing them again. Fixes #2592.

Removes dependency links from setup.py

---

Dockerfile.test.cpu
Dockerfile.test.gpu
docs/contributors.rst
setup.py

Versions of some packages in [dev] do not exist for Python 3.8, moving to the first version that supports 3.8 for those.

Make 'pip install -e .[dev]' work with Python3.8

---

test/parallel/test_keras.py
test/parallel/test_mxnet.py
test/parallel/test_tensorflow.py
test/parallel/test_tensorflow_keras.py
test/parallel/test_timeline.py
test/parallel/test_torch.py
test/single/test_buildkite.py
test/single/test_run.py
test/utils/spark_common.py

Some tests import `test/utils/commons.py` but are missing the required `sys.path` modification. Those tests only work when run after other test that perform this modification. This makes them work on their own.

Make tests that use commons work on their own

---

horovod/torch/functions.py
test/parallel/test_torch.py

In torch v1.8.0, some optimizer params are represented as None values, which cannot be converted to tensors.  This PR changes the handling of such scalars to use the `broadcast_object` function instead of converting to tensors.  
Because such scalars are small as compared to multi-dimensional tensor parameters, the overhead of pickling via `broadcast_object` should be relatively low. But it is likely that there will be a small drop in the performance of `broadcast_optimizer_state` by adding this increased stability.

Fixed broadcast_optimizer_state to handle NoneType params

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml
examples/spark/keras/keras_spark3_rossmann.py.patch
examples/spark/keras/keras_spark_rossmann_run.py
test/integration/test_interactiverun.py
test/single/data/expected_buildkite_pipeline.yaml

Implements #2570.
- Removes oneccl-ofi test image, as this is identical to the oneccl image, ofi tests use the latter image now.
- Removes Gloo support from images that do not have `gloo` in their name (to avoid falling back to Gloo if the MPI kind is not available).
- Removes Elastic Horovod on Spark integration tests from test images other than the baseline, baseline with tf1, and PySpark variations (strips off 5 CPU-hours of testing, 30 minutes of buildkite time)

Rework test space combinations

---

examples/spark/keras/keras_spark3_rossmann.py
examples/spark/keras/keras_spark_mnist.py
examples/spark/keras/keras_spark_rossmann_estimator.py
examples/spark/keras/keras_spark_rossmann_run.py
examples/spark/pytorch/pytorch_spark_mnist.py
horovod/runner/common/service/task_service.py
horovod/runner/common/util/network.py
horovod/runner/common/util/safe_shell_exec.py
horovod/runner/task/task_service.py
horovod/runner/util/stream.py
horovod/runner/util/streams.py
horovod/spark/driver/rsh.py
horovod/spark/gloo_run.py
horovod/spark/runner.py
horovod/spark/task/task_service.py
test/integration/elastic_spark_common.py
test/integration/test_spark.py
test/integration/test_spark_torch.py
test/single/test_run.py
test/single/test_service.py
test/single/test_task_service.py
test/single/test_util.py

Currently, running your training function on Spark over Gloo does not forward stdout / stderr to your driver. The output is written to Spark workers' log files, which are sometimes hard to find.
This PR allows to forward stdout or stderr or both to the driver.

Forward stdout/stderr capture to driver over gloo

---

horovod/_keras/__init__.py
test/parallel/test_tensorflow2_keras.py

CC: @romerojosh @tgaddair @nluehr 
This PR aims to fix a bug with TF2.4 already reported here: https://github.com/tensorflow/tensorflow/issues/46863
Basically this PR does the following:
- Rollback the `allreduce` in `_aggregate_gradients` and make sure to execute the allreduce during gradient computation
- Yes it means that in the eventuality the Grad Step is skipped (by mixed precision) we have allreduced for no reason, but this event is supposed to be very rare. And it's still better than having worker to desynchronize or deadlock.
- `self._aggregated_gradients = True` has been moved to gradient computation instead of `allreduce` itself. This is done to work around that gradient tape is used to compute gradient with a CTL
@tgaddair : would be nice to push a new release" to address this …

[TF2.4 - HVD Keras Fix] - Horovod worker desynchronization - Potentially deadlock training TF 2.4

---

horovod/common/operations.cc

This PR updates the trace message in `EnqueueTensorAllreduces` to be more consistent with output from similar functions.

Update trace message in EnqueueTensorAllreduces.

---

.github/workflows/buildkite_unit_tests.yml

Move GitHub actions to v1, so that they always run the latest release, but do not break when v2 releases appear (in contrast to using latest).
Further adds `pull_request_build: commit` so that test results are compared to common ancestor of master and the branch (where it branched off master) and not compared to master HEAD.

Upgrade GitHub actions

---

setup.py

Not a big change, though I noticed that Horovod wasn't reporting the license in the metadata:
```
License: UNKNOWN
```
Now this will be fixed ;)

Adding Horovod License to the metadata

---

.buildkite/gen-pipeline.sh
docker-compose.test.yml
test/single/data/expected_buildkite_pipeline.yaml

There is a conflict between numpy dependency required by tensorflow 1.15.x and mxnet 1.4.1:
The conflict is caused by:
mxnet 1.4.1 depends on numpy<1.15.0 and >=1.8.2
tensorflow 1.15.5 depends on numpy<1.19.0 and >=1.16.0

Deprecate mxnet==1.4.1 tests

---

CHANGELOG.md
horovod/common/common.h
horovod/common/ops/collective_operations.h
horovod/mxnet/adapter.cc
horovod/mxnet/adapter.h
horovod/mxnet/mpi_ops.cc
horovod/mxnet/mpi_ops.h
horovod/mxnet/mpi_ops.py
horovod/tensorflow/mpi_ops.cc
horovod/tensorflow/mpi_ops.py
horovod/torch/adapter_v2.cc
horovod/torch/adapter_v2.h
horovod/torch/mpi_ops.py
horovod/torch/mpi_ops_v2.cc
test/parallel/test_mxnet.py
test/parallel/test_tensorflow.py
test/parallel/test_torch.py

Often alltoall graph nodes occur in pairs (as in `input->alltoall->[processing]->alltoall->output`). With non-uniform splits, one currently needs to add an extra hvd.alltoall() op just to know how much data was received from which workers in the first hvd.alltoall() so those can be targeted properly again in the second hvd.alltoall(). Since this information is already available internally, I propose to expose the received_splits as an extra output of the op.

Let hvd.alltoall return the received splits if non-uniform splits are sent (TensorFlow, PyTorch, MXNet) 

---

horovod/torch/functions.py

For non-tensor parameters, we should also follow the passed in
root_rank, as broadcast of all tensor parameters.

torch: add missing root_rank in broadcast_optimizer_state

---

horovod/spark/common/serialization.py
horovod/spark/common/store.py

Fixes #2674 
Save metadata using store because spark has 2G limit on file size

Fix bug #2674. Save metadata using store because spark has 2G limit on file size 

---

Dockerfile.cpu
Dockerfile.gpu

Installing horovod does not install all dependencies. Also installs pyspark and Spark.
What is the purpose of these docker images? Are those pushed to docker hub? What do you think of adding spark to them?

Install horovod for all frameworks in Dockerfile, incl. Spark

---

horovod/common/util.py
setup.py

If `HOROVOD_SKIP_COMPILE` is set to `1`, native libaries using CMake
will be skipped in building.
Also, check_build function (gloo, nccl, ...) should allow None as return value.
Fixes #2688.

setup.py: allow horovod to be installed without native libraries

---

horovod/_keras/__init__.py

- [Yes] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [No] Did you update the docs?
- [No] Did you write any tests to validate this change?  
- [No] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?
This PR fixes an issue the current horovod optimizer wrapper cannot correctly deal with the custom learning rate schedule.
fyi. @nluehr @DEKHTIARJonathan 
Without this PR, the following script would fail:
```python
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers
import horovod.tensorflow as hvd
hvd.init()
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus: …
```

Add support for custom LearningRateSchedule for TF2

---

setup.py

This makes it easier and faster to switch between debug and release builds during development because one doesn't need to clean the entire build dir.

Use separate CMake build dirs for release and debug builds

---

Jenkinsfile.ppc64le
docker-compose.test.yml

TF-Head seems to break our tests in `test-cpu-gloo-py3_8-tfhead-keras_none-torchhead-mxnethead-pyspark_3_0_1`:
```
test_keras.py:23: in <module>
import keras
/usr/local/lib/python3.8/dist-packages/keras/__init__.py:25: in <module>
from keras import models
/usr/local/lib/python3.8/dist-packages/keras/models.py:20: in <module>
from keras import metrics as metrics_module
/usr/local/lib/python3.8/dist-packages/keras/metrics.py:27: in <module>
from keras import activations
/usr/local/lib/python3.8/dist-packages/keras/activations.py:20: in <module>
from keras.layers import advanced_activations
/usr/local/lib/python3.8/dist-packages/keras/layers/__init__.py:24: in <module>
from keras.engine.input_layer import Input
/usr/local/lib/python3.8/dist-packages/keras/engine/input_layer.py:21: in …
```

Pin tf-nightly to 2.6.0.dev20210331

---

Dockerfile.test.cpu
Dockerfile.test.gpu

The tensorflow, torch, torchvision and mxnet dependencies are installed in `Dockerfile.test.cpu` and `Dockerfile.test.gpu` before Horovod sources are copied, thus they are cached by Docker as long as the RUN command does not change. This should not happen for nightly packages.
This PR moves the installation of nightly packages after copying Horovod sources. This forces their download and installation on every run. Release versions, however, are still installed before the copy and thus subject for caching.
See all the RUN commands before `Step 50/63 : COPY . /horovod` in https://buildkite.com/organizations/horovod/pipelines/horovod/builds/5125/jobs/b3a90cef-21b8-41b9-8595-b5a25c16bd51/raw_log. **They are all cached, which is a great cache hit rate if it wouldn't be …

Docker should not cache nightly packages

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml
test/single/data/expected_buildkite_pipeline.yaml

PyTorch 1.8.1 has been released earlier this month. Adding this to test space while deprecating (test) support for 1.2.0.

Add PyTorch 1.8.1 to test space, deprecate 1.2.0

---

docker-compose.test.yml

We had to pin tensorflow nightlies in #2814. This tests if nightlies work again and to un-pin it in master.

Un-pin tf-nightly

---

docs/summary.rst

Recent changes to README.rst have not been applied to docs/summary.rst, so that both went out of sync. This brings both back to sync.

Sync docs with README.rst

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml
examples/spark/keras/keras_spark3_rossmann.py
examples/spark/keras/keras_spark3_rossmann.py.patch
examples/spark/keras/keras_spark_rossmann_estimator.py
examples/spark/keras/keras_spark_rossmann_run.py
test/integration/test_spark.py
test/single/data/expected_buildkite_pipeline.yaml

Add latest mxnet 1.8.0 and Spark 3.1.1 releases to test permutations.

Move test baseline to mxnet 1.8.0 and Spark 3.1.1

---

test/parallel/test_tensorflow.py

The test requires at least four GPUs if it is run with two workers. Sometimes one of the Buildkite CI jobs seem to be run with only three active GPUs although four GPUs were requested. This causes quite confusing failure messages "ncclCommInitRank failed: invalid usage" if this test is not skipped. Example: https://github.com/horovod/horovod/pull/2839/checks?check_run_id=2402052960

Skip TensorFlowTests::test_horovod_allreduce_multi_gpu if there are less than 2 GPUs per worker

---

horovod/spark/torch/remote.py

Sometime we got the below kind of stdout and it is confusing:
Wed Apr 21 08:06:33 2021[1,0]<stdout>:epoch:	39	step	6500:	{'loss': 31255.2109375, 'all_metrics': []}
Wed Apr 21 08:06:37 2021[1,0]<stdout>:epoch:	39	step	0:	{'loss': 27432.6484375, 'all_metrics': []}
The first line is training and the second line is validation.
Adding phase str into stdout to make it more clear.

TorchEstimator: add phase into stdout

---

horovod/_keras/__init__.py

This reverts commit b1ae83a611d6005c705d73faf73aa0628d8c2a61.
This is to revert one of my previous PR. I realized the correct way to use the custom LR + HVD should be using this keras decorator: https://www.tensorflow.org/api_docs/python/tf/keras/utils/register_keras_serializable.
So, users should apply the above decorator to their LR subclass before applying HVD. Also, the original PR might expose the issue when the custom LR is a nested LR class.
cc. @nluehr @DEKHTIARJonathan @romerojosh 
3. If any member of the technical steering committee requests changes, they must be …

Revert "Add support for custom LearningRateSchedule for TF2 (#2706)"

---

horovod/common/basics.py
horovod/common/controller.cc
horovod/common/controller.h
horovod/common/operations.cc
test/parallel/test_torch.py

Fixes #2804. 
PR #2215 changed the Horovod initialization code to initialize the timeline unconditionally, rather than only in cases where the user sets `HOROVOD_TIMELINE`. This is a problem because the timeline spawns an additional writer thread that can consume CPU resources. Additionally, there are still places in the code that check whether the timeline is initialized in order to skip unnecessary operations, for example this code block here:
https://github.com/horovod/horovod/blob/2436af9d1c0681090919e314e0cfbd9bc13d7a53/horovod/common/ops/nccl_operations.cc#L165-L167
Since that PR, these branches/operations are executed every time, whether or not a user is using the timeline functionality. 
Another place this occurs is in the response cache coordination logic, where additional bits …

Require setting HOROVOD_TIMELINE=DYNAMIC to enable dynamic timeline API usage

---

horovod/tensorflow/keras/__init__.py

Signed-off-by: Josh Romero <joshr@nvidia.com>
The `num_groups` and `groups` arguments added to the DistributedOptimizer API in #2453 was added to the baseline Keras implementation but not the `tf.keras` API.  This PR exposes those arguments in `tf.keras` as well.

Expose groups/num_groups argument to tf.keras.DistributedOptimizer.

---

horovod/common/response_cache.cc

Fixes an issue discovered in #2872 with the response cache. The issue is that checks to see if messages or responses are cached (i.e. the two `ResponseCache::cached` methods) do not check that the `RequestType` and `ResponseType` are the same. Hence, if two Horovod operations are scheduled with the same name, but do different collective operations and the first operation is cached, the execution of the second operation is incorrect.
This PR adds an additional check for request/response type consistency.

Add response/request type consistency check to response cache.

---

CHANGELOG.md
docs/ray.rst
examples/ray/tensorflow2_mnist_ray.py
horovod/ray/__init__.py
horovod/ray/elastic.py
horovod/ray/runner.py
horovod/ray/strategy.py
horovod/ray/utils.py
horovod/ray/worker.py
test/single/test_ray.py

Closes https://github.com/horovod/horovod/issues/2702

[Ray] Use num_workers API for Horovod Ray

---

CHANGELOG.md
horovod/tensorflow/__init__.py
horovod/tensorflow/gradient_aggregation.py
test/parallel/test_tensorflow.py

- Fixes #2806
- Support sparse gradients aggregation in TF1 Keras.
- Respect `global_step` parameter for LegacyOptimizers when aggregating gradients. Previously, we'd always increment default tf `global_step`, but tensorflow allows users to pass custom `global_step` variables, and we should respect and support this behavior.

Support sparse gradients and respect `global_step` parameter in gradient aggregation.

---

CHANGELOG.md
horovod/spark/common/params.py
horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/spark/lightning/estimator.py
horovod/spark/lightning/remote.py
horovod/spark/torch/estimator.py
horovod/spark/torch/remote.py
test/integration/test_spark_keras.py
test/integration/test_spark_lightning.py
test/integration/test_spark_torch.py

Allow users to specify process_pool (default) or thread_pool for
petastorm reader.

Estimator: add petastorm reader_pool_type into constructor

---

Dockerfile.test.cpu
Dockerfile.test.gpu
horovod/keras/__init__.py
horovod/spark/torch/remote.py
horovod/tensorflow/keras/__init__.py
horovod/torch/sync_batch_norm.py
setup.py
test/integration/test_elastic_torch.py

In #2730 we have pinned torch nightly, this un-pins it by adjusting for upstream changed.
* The API of `torch.batch_norm_backward_elemt` changes in 1.9.0.
Unrelated changes but fixed in this PR:
* Some package imports broke readthedocs build in master.
* Latest petastorm version (0.11.0) breaks `BatchedDataLoader` constructor break master, so limiting to `petastorm<0.11.0` (#2909).
Not handled in this PR:
* Elastic torch tests started to fail on all torch versions across CPU and GPU on an uncaught GLOO IO Exception (#2908)

Un-pin torch-nightly

---

test/parallel/test_torch.py

The `test_timeline_api` test in `test_torch.py` is flaky on Ubuntu. Disabling the test again, which has been enabled recently for Ubuntu.

Skip flaky test_timeline_api in test_torch.py

---

CHANGELOG.md
examples/spark/keras/keras_spark_mnist.py
horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/spark/keras/util.py
horovod/spark/torch/remote.py
setup.py
test/integration/test_spark_keras.py

We set infinite epochs for petastorm reader in horovod, due to the known issue that data partition is not guarantee to be equivalent size. TF's dataset shuffle function will automatically refill the shuffle buffer after retrieving a single element.
Code in horovod:
```
if shuffle:
dataset = dataset.shuffle(shuffle_buffer_size)
```
Mixing infinite iterations from reader and TF's shuffle function, will introduce sample duplication and drop-out in a single epoch. For example, training dataset is [`0,1,2,3,4,5,6,7]`, and shuffle size is 8.
Shuffling buffer is initialized as `[0,1,2,3,4,5,6,7]`
It randomly pick 7, and refill with 0 again: `[0,1,2,3,4,5,6,0]`
Now it is highly possible 0 will be selected twice in next few iterations, even before other values are selected once.
This PR fixes …

Keras estimator: set reader's epoch = 1 to avoid sample duplication and drop-out in a single epoch

---

test/integration/test_spark_keras.py
test/integration/test_spark_lightning.py
test/integration/test_spark_torch.py
test/utils/spark_common.py

Use deterministic val dataframe, instead of split ratio.
Spark may split out unbalanced/empty dataframe since unittest data is
small.

test: fixing flaky estimator test using val dataloader

---

horovod/ray/strategy.py

This fixes an existing bug with using a Ray-based shuffling dataloader, which we are developing separately.

[ray] disable capturing child tasks in placement group.

---

.github/workflows/docker.yml

Pushing a few commits to a branch kicks of the docker workflow for each of them, causing concurrent runs. Firstly, the earlier runs are redundant, secondly, a slow earlier run may overwrite (on master only) images published by a later run.
This enforces a single concurrent run of the docker workflow for each branch, which kills earlier runs.

Enforce a single concurrent run of docker workflow per branch

---

.github/workflows/docker.yml
docker/horovod-cpu/Dockerfile
docker/horovod-ray/Dockerfile
docker/horovod/Dockerfile
setup.py

Previously, using `all-framemworks` extras for CPU builds was resulting in both `tensorflow-cpu` and `tensorflow` being installed, which broke `horovod.tensorflow` imports.
Also changes EC2 instance used to build the image to a smaller, cheaper instance, as most of the build is single-threaded and does not need high amounts of CPU, memory, or network bandwidth.

Fixed CPU docker images and added additional sanity checks

---

.github/workflows/docker.yml

Using matrix strategy when starting and stopping EC2 instances. Reduces some code duplication and starts and stops instances in parallel:
[![grafik](https://user-images.githubusercontent.com/44700269/119275430-4e5d3b00-bc15-11eb-9d0d-91bd95e44b3e.png)](https://github.com/horovod/horovod/actions/runs/869344199)

Use matrix to start and stop EC2 instances

---

.github/workflows/docker.yml

In fork repositories, the docker workflow fails as there are no AWS secrets. This annoys our forks.
Example: https://github.com/G-Research/horovod/actions/runs/874476267
Example with fix: https://github.com/G-Research/horovod/actions/runs/875035459

Do not start the docker workflow in a fork repository context

---

.github/workflows/docker.yml

Disabling docker workflow in forks (#2937) only worked partially, schedule event does not have the expected data in `github.event`.

Disable docker workflow on forks for schedule events

---

.github/workflows/docker.yml

We are still seeing issues with PRs from forks that try to build docker on EC2. Depending on the event (`schedule`, `push` or `pul_request`), the content of `github` changes.

Fix docker build for fork PRs

---

horovod/spark/lightning/remote.py
horovod/spark/torch/remote.py

torch estimator: check all ranks have same device type

---

.github/workflows/docker.yml

Some instances in EC2 have been dangling for a few days. I suspect it's due to workflow cancellation signals being sent when a new commit is pushed. Canceling the workflow (I suspect) is preventing the cleanup job from running at the end. This change moves the cancellation handler into the job, so that the following cleanup job can still run.

Move cancellation hook into job from workflow to ensure instance cleanup

---

horovod/torch/mpi_ops.py
test/parallel/test_torch.py

Root cause hasn't been found out. But if values_handle is not synced
firstly, sparse_allreduce_async will be hanging in unit test.
Fixes #2961

torch: sync values_handle firstly in sparse_allreduce_async

---

.github/workflows/docker.yml

A number of jobs have been failing due to issues in the Docker workflow. This PR makes a few changes to address this:
1. Removed parallelism, as it seems to result in some race conditions. Because the Buildkite tests take about 90 minutes to complete, it should not be necessary to parallelize the docker workflow, which will complete ahead of the tests even serially.
2. Changed cancellation behavior so `master` branch docker builds are never cancelled. This is important as otherwise we could miss building images for each SHA, version, etc. The assumption here is that `github.head_ref` will be empty on master, so we use the unique `github.sha` instead for the concurrency group.
3. Added metadata to identify EC2 workers in AWS. This will help us discover which jobs led to which instances …

Fixed docker workflow stability

---

horovod/spark/lightning/remote.py

lightning: turn off shuffling for validation dataset

---

.github/workflows/docker.yml
docker/horovod-cpu/Dockerfile
docker/horovod-ray/Dockerfile
docker/horovod/Dockerfile

We can build release Docker images with GitHub actions and avoid EC2 instances. The `horovod-ray` image is the largest, as the input image is 4.27 GB, where `horovod`'s input Nvidia image is only 2.17 GB.
Several improvements make this work now:
- running `pip install` with `--no-cache-dir` so that downloaded pip packages are not stored in the Docker image
- running `apt-get` together with `apt-get clean && rm -rf /var/lib/apt/lists/*` removes distribution files
- installing PyTorch first, as this requires 2 GB temporary space (GPU)
- pruning docker images before running docker build frees enough disk space to even build `horovod-ray` frees another 4 GB of pre-allocated disk space
It looks like we have 1.7 GB disk space head room: …

Build release Docker images on github-hosted runners

---

.github/workflows/docker.yml

Building and pushing Horovod release Docker images via GitHub Action (#2970 failed on master when actually pushing to the registry: https://github.com/horovod/horovod/runs/2807151712.
This cleans up 20 GB disk space before building the image. There are 18 GB more available for clean up, but those sometimes take 2-3 minutes to delete.

Clean up disk space before building Docker images

---

horovod/spark/gloo_run.py
horovod/spark/mpi_run.py
horovod/spark/runner.py

Add parameter to specify an executable path for workers spawn by horovod on spark.
Useful in situations where the python env is shipped with `conda-pack` or https://github.com/criteo/cluster-pack
PR similar to #2708 
Tested with horovod on spark in a CPU cluster.

Add executable arg to horovod.spark.run

---

.github/workflows/docker.yml

With the rework of our `docker.yml` we have lost the specific behaviour for fork repositories (#2970).
This change disables the `schedule` event for fork repositories, as well as the login step for Dockerhub.
And this adds some more context to the concurrency logic added in #2971.

Configure docker builds for forks

---

horovod/common/ops/cuda/cuda_kernels.cu
horovod/common/ops/cuda/cuda_kernels.h
horovod/common/ops/gpu_operations.cc
horovod/common/ops/gpu_operations.h
horovod/common/ops/nccl_operations.cc

For a Horovod allreduce operation using NCCL, the batched fusion buffer pack, prescaling, postscaling, and batched fusion buffer unpack are all individual CUDA kernel launches. This PR introduces a fused batched memcpy and scaling CUDA kernel to perform a (un)pack and scaling in a single kernel launch. This fusion reduces the number of kernels Horovod launches and improves performance by removing extra read/writes of GPU buffer memory between the existing individual pack and scaling kernels.

Add fused buffer scaling and unpack/pack kernels on GPU.

---

.buildkite/gen-pipeline.sh
docker-compose.test.yml
test/single/data/expected_buildkite_pipeline.yaml

Adds test support for
- Tensorflow 2.5.0
- PyTorch 1.9.0
Removes test support for
- PySpark 2.3.4
- Tensorflow 2.0.4, 2.1.3, 2.2.2
- PyTorch 1.3.1, 1.4.0, 1.5.1
Upgrades PySpark to latest patch releases:
- PySpark 2.4.8, 3.0.3, 3.1.2
This includes #2997.

Upgrade test versions to latest releases

---

test/parallel/test_torch.py

This test for `grouped_allreduce` accidentally shadowed `test_horovod_allreduce_grad_average`.

Fix name of TorchTests.test_horovod_grouped_allreduce_grad_average()

---

horovod/spark/keras/remote.py
horovod/spark/lightning/remote.py
horovod/spark/torch/remote.py

In #2927 we added `storage_options` to the store object, but in doing so, also made the `store` part of the closure sent to remote workers, resulting in an attempt to serialize / deserialize the store. Unfortunately, the HDFS store in particular cannot be serialized correctly, so this change fixes this by putting the `storage_options` only into the closure.

Removed store from closure variables sent to remote workers

---

Dockerfile.test.cpu
Dockerfile.test.gpu

This adds a `pip freeze` to the test image build to easily spot python package version changes across builds, especially useful when nightly builds fail.

Add pip freeze to spot package version changes

---

.github/gen-workflow-ci.py
.github/workflows/ci-fork.yaml
.github/workflows/ci.yaml

The new CI Workflow does not yet work well with fork PRs. This adds some debugging to CI and CI-Fork.

Add debugging to new CI Workflow

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml

The Buildkite step is skipped for fork PRs, as there are no Buildkite credentials in that context. I suspect this to case the dependent docker-config step to also get skipped, so that we do not build Docker images for fork PRs.
This change hopefully enforces docker builds for fork PRs.

Build docker images for fork PRs

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml

When flaky tests fail, they seem to fail all three attempts in our CI workflow. This runs the attempts in separate jobs to see if this isolation helps to recover from flaky tests.

Retry failed jobs in separate job

---

horovod/spark/common/store.py

To avoid possible file writing conflicts when multiple workflows using
same training path.
On Uber side, we have found that for some parallel autotune training workflows using same training file path, it is possible to run into `HDFS file not found` exception as below:
```
But see this error:
org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /user/csashi/canvas/workspaces/poka_yoke_model_exploration_v2/variables/fa2048ad-6b93-44a6-8e97-453a58f72d60/value/value.parquet_cached_metadata.pkl (inode 24400193212) Holder DFSClient_NONMAPREDUCE_1435370252_1 does not have any open files.
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2724)
at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFileInternal(FSD …
```

Estimator: make metadata path unique

---

.github/gen-workflow-ci.py
.github/workflows/ci-fork.yaml
.github/workflows/ci.yaml

The "Build and Test" job has been split in #3025 because it looked like a good idea (separation of concerns). But the job dependency graph is more complex now. And each job has the full `max-parallel`, where before that split the cpu images determined the `max-parallel` value as CPU build and test takes much longer than GPU build.
Merging both jobs together will de-prioritize the GPU jobs again and leave more concurrent jobs for other workflow runs.

Merge CPU and GPU CI jobs into one again

---

horovod/spark/keras/remote.py
horovod/spark/torch/remote.py

For torch and keras trainer. Lightning trainer has already supported.

Estimator: print trainer parameters to stdout

---

horovod/tensorflow/functions.py
test/parallel/test_tensorflow.py

This is a minor extension to #2839, adding process set support to these functions in `horovod.tensorflow`: `broadcast_variables()`, `broadcast_object()`, `broadcast_object_fn()`, `allgather_object()`.

Add process set support for some remaining functions [TensorFlow]

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml

Some more fine-tuned conditions for the CI workflow:
- the `schedule` event should not run every day on our thousands of fork repos at all
- buildkite job should also be triggered on `schedule` event
- print out buildkite build url when those tests fail
- provide AWS ECR credentials only horovod repo and not for fork PRs

Fine-tune Github CI workflow conditions

---

horovod/mxnet/__init__.py
horovod/mxnet/mpi_ops.cc
horovod/mxnet/mpi_ops.h
horovod/mxnet/mpi_ops.py
test/parallel/test_mxnet.py

This is a straightforward extension of #2839, adding the process set feature to the MXNet API.
Included are the ops `allgather`, `allreduce`, `alltoall`, `broadcast`, and `grouped_allreduce`, as well as the `DistributedOptimizer`.
There's also the `DistributedTrainer` that I didn't look into. I don't have much experience working with MXNet, but it seems that a Gluon Trainer would be a higher level concept meant to operate on an entire neural net. In that case adding an overall `process_set` argument might not be the right call as users will typically want to non-globally aggregate the gradients for just a subset of their parameters, not for the entire model.

Add process set support for MXNet

---

.buildkite/gen-pipeline.sh
.github/gen-workflow-ci.py
.github/workflows/ci.yaml

Pushing test images from master allows to use them as caches for later test builds. This mimics the behaviour that we have seen on Buildkite.

Push docker test images from Github

---

.github/workflows/ci-fork.yaml

The CI (Fork) workflow is broken, it cannot process the workflow result JSON because the jq query is broken.

Fix jq query for CI (Fork) workflow

---

horovod/spark/keras/remote.py

Local checkpoint and logs files are pushed into remote store
destination. Print remote store path instead of local path in stdout.

Estimator/Keras: use chkpt and logs path in remote store

---

horovod/torch/__init__.py
horovod/torch/functions.py
horovod/torch/mpi_ops.py
horovod/torch/mpi_ops_v2.cc
horovod/torch/optimizer.py
test/parallel/test_torch.py

This is a straightforward extension of #2839, adding the process set feature to the PyTorch API.
Included are the ops `allgather`, `allreduce`, `alltoall`, `broadcast`, `grouped_allreduce` and their gradients, as well as the `DistributedOptimizer` (+ `broadcast_object`, `sparse_allreduce_async`).

Add process set support for PyTorch

---

CHANGELOG.md
docs/contributors.rst
docs/install.rst
setup.py

Fixes develop/editable mode to support direct changes in the source code and incremental C++/CUDA builds.
Note: On the first rebuild,  I have noticed the CUDA code being rebuilt when not modified. It is potentially an issue with the add_cuda_library cmake code that generates the dependency file. On the second rebuild, the issue disappears.
This issue may disappear with using cudatoolkit (newer version of cmake) instead of cuda cmake module. Something we could try.
@romerojosh FYI ^^
Fixes #1520.

Fix develop/editable install mode

---

horovod/mxnet/__init__.py

Small update to #3083 to add more usage of `process_set.size()` in place of the world size.

Use process_set size instead of world size in MXNet DistributedOptimizer/Trainer in quick return conditions.

---

.buildkite/gen-pipeline.sh
.github/workflows/ci.yaml
docker-compose.test.yml
test/single/data/expected_buildkite_gpu_pipeline.yaml

This adds Tensorflow 2.6.0 to tests, removes support for 2.3.4 and upgrades 2.4 and 2.5 to latest patch release versions.

Add Tensorflow 2.6.0 to tests, remove 2.3.4

---

docker-compose.test.yml
docs/spark.rst
horovod/spark/lightning/estimator.py
setup.py

Fix compatibility for torch==1.4.0

pin pytorch_lighting to 1.3.8

---

horovod/data/data_loader_base.py
horovod/spark/lightning/datamodule.py

Since petastorm reader can have infinite loops, main thread has to drain
the queue in order to join the asynchronous worker thread. Otherwise
queue could always be full and asynchronous worker stucks in
queue.put(None).
Also call close_async_loader() in lightning datamodule to close async
dataloaders explicitly, to avoid uncaught exceptions.
Fixes #3119 .

Fix pytorch async dataloader race condition

---

horovod/spark/common/store.py
horovod/spark/keras/remote.py
test/integration/test_spark_keras.py

While using horovod v0.22.1 with tensorflow v2.4.2, a checkpoint error occurs during training. The error logs have been mentioned in #2988. This pr fixes the issue with loading the saved checkpoints for tensorflow version greater than 2.0.0

Fixed spark keras "IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpn_eenlao/checkpoint'" error

---

horovod/_keras/callbacks.py

- When the LearningRateScheduleCallback is initialized with multiplier = constant, it does not work correctly (there is no learning rate decay): more specifically learning rates = initial_lr * multiplier, initial_lr * multiplier, initial_lr * multiplier,... whereas the expectation it decays as  initial_lr,  initial_lr * multiplier,  initial_lr * multiplier^2 and such
- Another nit is when multiplier = constant, there is no need to enforce that staircase = True. The change made to fix the above mistake can handle staircase = False as well
- [Y] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [Y] Did you update the docs?
- [N] Did you write any tests to validate this change?  
- [N] Did you update the …

Fix error in keras Learning Rate Scheduler

---

horovod/spark/lightning/estimator.py

Lightning transformer, separate the model prediction function out of _transform function. So subclass can override the behaivor of how model is called.

separate prediction from transform

---

horovod/_keras/callbacks.py

- Fixes issue when start_epoch != 0
- [Y] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [Y] Did you update the docs?
- [N] Did you write any tests to validate this change?  
- [N] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?
Fixes mistake in keras LR scheduler callback when start_epoch != 0 and multiplier is a constant

Fix mistake in keras LR scheduler callback

---

CHANGELOG.md
docs/mocks.py
horovod/ray/runner.py
horovod/ray/strategy.py
test/single/test_ray.py

Adds a `PGStrategy` to `RayExecutor`, which will automatically capture the placement group should one be currently present, and use it for Horovod.

Make RayExecutor use the current placement group if one exists

---

CHANGELOG.md
horovod/spark/common/util.py

Horovod maps pyspark string type to numpy uint8 type. It blocks users using string type tensor input. I think originally the reason why we map string type to numpy uint8 is because tensorflow does not support string label. But with the mapping, horovod KerasModel would fail in transform stage anyway. And keras itself does not support string label (https://stackoverflow.com/questions/55970851/tensorflow-model-fit-does-not-work-with-strings-as-labels). We don't need to use the incorrect mapping to fail the transform
3. If any member of the technical steering committee requests …

Fix the mapping btw pyspark and numpy

---

test/parallel/test_torch.py

For torch nightly >=10.0, we need to add an explict join() call to avoid
hanging when testing duplicated name errors.
Fixes #3149 .

test_torch.py: add explicit join() for testing duplicated name errors

---

cmake/Modules/FindTensorflow.cmake
horovod/tensorflow/CMakeLists.txt

_pywrap_tensorflow_internal.so is missing on OSX.
Fixes #3132 .

CMake: skip TF XLA support for OSX

---

examples/spark/pytorch/pytorch_lightning_spark_mnist.py
horovod/spark/lightning/estimator.py
horovod/spark/lightning/remote.py

Spark/Lightning: fix the usage of checkpoint callback

---

.github/gen-workflow-ci.py
.github/workflows/ci-results.yaml
.github/workflows/ci.yaml

Test results are posted to the respective pull request:
However, results from fork PRs currently lack a few features: change stats (`±0`), added, removed or newly skipped tests:
Most of our contributions come from forks nowadays so identifying changes in test coverage is important but very hard without these change stats.
This fix makes PRs from forks also have change statistics. Test results are now published by the `CI (Results)` workflow **only**. This works for fork PRs as well for PRs from the horovod repo, so that there is only one place that publishes results.

Make fork PRs publish test change stats

---

horovod/common/ops/adasum_gpu_operations.cc
horovod/common/ops/nccl_operations.cc

On cuda 11.4 and nccl 2.11.4, calling `ncclBcast` fails with the error "invalid argument". `ncclBcast` was deprecated starting in nccl version 2.2.12. Switching to the new API of `ncclBroadcast` fixes this error. 

Support for nccl on cuda 11.4

---

.buildkite/gen-pipeline.sh
test/single/data/expected_buildkite_gpu_heads_pipeline.yaml
test/single/data/expected_buildkite_gpu_non_heads_pipeline.yaml

Buildkite seems to timeout on building the GPU images:
- https://buildkite.com/horovod/horovod/builds?branch=master
- https://buildkite.com/horovod/horovod/builds/6517#c096ad84-17b0-498c-86da-1cc800f656fc
Giving it 10 more minutes to build.
@tgaddair the build time probably increased due to reducing the number of CPUs.

Increase build timeout to 40m on Buildkite

---

cmake/Modules/FindTensorflow.cmake

Ubuntu 16.04 comes with CMake 3.5.1 by default. I tested that with this change Horovod builds successfully with TensorFlow in such a container.
We currently ask for version 2.8.12 or higher in the root `CMakeLists.txt`.

Change CMake syntax to be compatible with old versions of CMake

---

CHANGELOG.md
horovod/common/basics.py
horovod/common/common.h
horovod/common/controller.cc
horovod/common/message.cc
horovod/common/message.h
horovod/common/operations.cc
horovod/common/operations.h
horovod/common/ops/collective_operations.cc
horovod/common/ops/collective_operations.h
horovod/common/ops/operation_manager.cc
horovod/common/ops/operation_manager.h
horovod/common/response_cache.cc
horovod/common/tensor_queue.cc
horovod/common/tensor_queue.h
horovod/common/wire/message.fbs
horovod/common/wire/message_generated.h
horovod/torch/__init__.py
horovod/torch/mpi_ops.py
horovod/torch/mpi_ops_v2.cc
test/parallel/test.py
test/parallel/test_torch.py

Add barrier call to torch module to support easy synchronization for process sets. Existing methods that use other apis are either not well known or not designed to be a synchronization point. This also achieves parity with other distributed training frameworks. 
This also fixes a minor issue with is_initialized(). The horovod_is_initialized returns an atomic bool which will be interpreted as a random INT by ctypes on Mac. Changed it to return INT instead.
Fixes #3121  (issue).
https://github.com/horovod/horovod/issues/3121
3. If any member of the technical steering committee requests changes, they …

Add barrier call to torch module to support easy synchronization for process sets

---

horovod/_keras/callbacks.py

Fixes #2440 
Remove warning in MetricsAverageCallback after TF 2.5 after https://github.com/tensorflow/tensorflow/issues/41851
The keras history is now correct, however that doesn't seem to have fixed the progress bar (if that was working before...)

Remove MetricAverageCallback warning on tf >= 2.5

---

horovod/spark/common/util.py
test/utils/spark_common.py

Fixes #2193 .
Fix Horovod pyarrow IndexError: list index out of range

Fix Horovod pyarrow IndexError: list index out of range

---

CHANGELOG.md
Dockerfile.test.cpu
horovod/mxnet/mpi_ops.py
horovod/spark/keras/remote.py
horovod/spark/lightning/remote.py
horovod/spark/torch/remote.py
horovod/tensorflow/mpi_ops.py
horovod/torch/mpi_ops.py

In remote trainers of the horovod spark module, if multiple frameworks are imported in the same process, there's a chance that the _basics in horovod.common.process_set is pointing to the wrong shared lib path resulting in horovod not initialized error even after calling hvd.init(). This calls _setup again before fitting the model to make sure the shared lib is correct.

Call process_set._setup in init() to point to the correct native lib path

---

horovod/common/common.h
horovod/common/ops/cuda_operations.cc
horovod/mxnet/mpi_ops.cc
horovod/mxnet/mpi_ops.h
horovod/torch/cuda_util.cc
test/parallel/base_test_mxnet.py

This is a work-in-progress PR that builds on #2963 in preparation for MXNet PR (apache/incubator-mxnet#20331), which introduces a new asynchronous scheduling engine in that framework. This PR uses this new MXNet feature to take better advantage of changes introduced in #2963. 
This is a cleaned up and rebased version of #2972 to prepare for a merge of apache/incubator-mxnet#20331 which should be happening soon. Marking as WIP here until that upstream merge happens.
EDIT: apache/incubator-mxnet#20331 was merged so removing WIP status.
3. If any member of the technical steering committee requests …

Add support for MXNet async dependency engine.

---

.github/workflows/ci-results.yaml

This updates the GPU Buildkite check status for fork PRs:
These should be updated to pending and then the final outcome when the Buildkite tests are kicked off for fork PRs.
Unfortunately, this can only be tested once merged in master. The `continue-on-error: true` should make these steps not interrupt the workflow in case they fail.

Set GPU test check status for fork PRs

---

horovod/common/operations.cc

Fixes #3264.
avoid enqueuing more collective ops while horovod is shutting down.

fix issue 3264

---

.github/workflows/ci-results.yaml

In #3270 the "CI (Results)" workflow that runs for fork PRs and executes the Buildkite GPU tests updates the check statuses of the PR to indicate that these tests are running or have finished. This could only be tested in master.
The link of the check status now points to the "CI (Results)" workflow and not the triggering "CI" workflow. Further, the check status name is now prefixed with the workflow name "CI (Results) / ", so it aligns with other check status names.

Fix check status name and details link

---

CHANGELOG.md
docs/ray.rst
horovod/ray/adapter.py
horovod/ray/elastic_v2.py
horovod/ray/runner.py
test/single/test_ray.py
test/single/test_ray_elastic_v2.py

RayExecutor V2: Dynamic executor for elastic and static jobs
This resolves #3190 by adding elastic params to the RayExecutor API for horovod:
This API now supports both static(non-elastic) and elastic horovod jobs.
Example of static job(Identical to current RayExecutor):
```python
from horovod.ray import RayExecutor
ray.init()
hjob = RayExecutor(setting, num_workers=num_workers,
use_gpu=True
))
executor.start()
def simple_fn():
hvd.init()
print("hvd rank", hvd.rank())
return hvd.rank()
result = executor.run(simple_fn)
assert len(set(result)) == hosts * num_slots
executor.shutdown()
```
Example of an elastic job:
```python
from horovod.ray import RayExecutor
import horovod.torch as hvd
def training_fn():
hvd.init()
model = Model()
torch.cuda.set_device(hvd.local_rank())
@hvd.elastic.run …
```

RayExecutor: Dynamic executor for elastic and static jobs

---

horovod/torch/__init__.py

Fixes typo — `avaiable` — in `Warning! MPI libs are missing, but python applications are still avaiable.`

Fix typo `avaiable` in MPI libs warning

---

test/parallel/test_mxnet2.py

Replaces `as_in_ctx` calls with `as_in_context` calls in `test_mxnet2.py`.

Fix  method name in MXNet2 test.

---

.github/gen-workflow-ci.py
.github/workflows/ci-results.yaml
.github/workflows/ci.yaml

Buildkite uses the branch not literally but merely as an id to identify concurrent builds. This runs HEAD and non HEAD buildkite jobs in parallel by giving them individual branch names. This way way do not wait for the HEAD job because this now runs in parallel to the non HEAD job, which takes longer anyway. This should shave off an hour from the entire CI workflow.
Old job dependency:
https://github.com/horovod/horovod/actions/runs/1487590026
New job dependency:
https://github.com/horovod/horovod/actions/runs/1486597919

Run buildkite jobs in parallel

---

horovod/spark/common/store.py
horovod/spark/lightning/remote.py
horovod/spark/torch/remote.py
test/integration/test_spark_lightning.py

Fixes #3268. Creating named temporary output directories which are later copied to run path, then fetching the checkpoints from this named directory in run path to ensure latest checkpoints are fetched in multiple iterations.

Fix lightning and pytorch estimator loading from checkpoint

---

.buildkite/gen-pipeline.sh
.github/workflows/ci.yaml
Dockerfile.test.cpu
Dockerfile.test.gpu
examples/spark/pytorch/pytorch_lightning_spark_mnist.py
test/integration/test_spark_lightning.py
test/single/data/expected_buildkite_gpu_heads_pipeline.yaml
test/single/data/expected_buildkite_gpu_non_heads_pipeline.yaml

Reactivates Spark tests disabled in #3259. Fixes #3262.

Reactivate tests removed in #3259

---

horovod/spark/common/store.py
horovod/spark/lightning/remote.py
horovod/spark/torch/remote.py
test/integration/test_spark_lightning.py

Reverts horovod/horovod#3279
This is broken in multiple ways (#3288) which was not uncovered by testing because Spark tests were disabled for a while (#3263). Let's revert and do again now that Spark tests are back.

Revert "Fix lightning and pytorch estimator loading from checkpoint"

---

horovod/common/controller.cc
test/parallel/test_torch.py

When a Horovod operation is not given an explicit name in PyTorch code, it receives an automatically generated name that encodes an internal handle number. That handle, however, is a local concept and it can differ between Horovod processes if they enqueue different numbers of operations. Name mismatches then lead to stalls.
This situation was occasionally triggered in the PyTorch unit tests when running with MPI. For instance, I would see the following:
```
test_torch.py::TorchTests::test_horovod_broadcast_error 
[horovod/common/stall_inspector.cc:107] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or …
```

Fix hvd.barrier() tensor queue management and torch test failures from op name mismatches

---

Jenkinsfile.ppc64le

Fix ppc64le CI.
Move to ppc64le CI to TF 2.6.0 anf PyTorch 1.9.1. Also using RedHat UBI image (Ubuntu is not supported anymore for ppc64le with the AI stack).

Move ppc64le CI to TF 2.6.0 and PyTorch 1.9.1

---

horovod/common/controller.cc
test/parallel/test_torch.py

This is to fix the possible seg fault that happens when mixing barrier op with allgather. In TotalByteSizeOfAllgatherOutput function, it calculates the output size by accessing the tensor pointer of the response entry object, for ops like barrier or join whose tensor pointer is empty, horovod will seg fault.
Since the function only needs to be called when fusion is enabled, we simply skip the fusion calculation when op is join or barrier.
Added a new test for barrier that runs with multiple collectives to validate this change.
3308
3. If any member of the technical steering …

fix barrier seg fault and added test to mix it with multiple collectives

---

GOVERNANCE.md

Proposed adding new members to TSC:
- [ashahab](https://github.com/horovod/horovod/commits?author=ashahab), who has added a number of contributions in recent months around Horovod on Ray and Elastic Horovod.
- [Tixxx](https://github.com/horovod/horovod/commits?author=Tixxx), who was instrumental in Adasum and has been contributing a lot of to improve low-level Horovod performance and reliability.

Added members to TSC

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Setuptools released 60.1.0 on 24th December, with that christmas present, installing mpi4py fails: https://github.com/mpi4py/mpi4py/issues/160
https://github.com/horovod/horovod/runs/4625980553?check_suite_focus=true#step:10:1790
```
2021-12-24T10:10:25.5324561Z #28 0.777 Collecting mpi4py
2021-12-24T10:10:25.5327643Z #28 0.809   Downloading mpi4py-3.1.3.tar.gz (2.5 MB)
2021-12-24T10:10:25.9847293Z #28 1.256   Installing build dependencies: started
2021-12-24T10:10:28.2403790Z #28 3.491   Installing build dependencies: finished with status 'done'
2021-12-24T10:10:28.2404676Z #28 3.495   Getting requirements to build wheel: started
2021-12-24T10:10:28.3908932Z #28 3.660   Getting requirements to build wheel: finished with status 'error'
2021-12-24T10:10:28.3910150Z #28 3.660   ERROR: …
```

Fix mpi4py installation for setuptools >= 60.1.0

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml

Currently, docker only fails if the last command in `RUN` fails, otherwise it keeps on building the image. The resulting image fails during tests (in the best case) and a thorough investigation of the build process is the consequence. There have been a lot of situations in the past where errors in the build process have been hidden by this, e.g. https://github.com/horovod/horovod/runs/4648818225?check_suite_focus=true#step:10:1588.
This makes the `RUN` command fail on the first bash command that fails, not only on the last one.
Related, macOS tests run even if the build step fails. This is also fixed here.

Make docker fail on the first command that fails in RUN

---

horovod/common/process_set.cc
test/parallel/test_torch.py

I've been looking at some test failures in PR #3261, that popped up after rebasing to master: [CI logs for test-cpu-gloo-py3_7-tf2_7_0-keras2_7_0-torch1_10_1-mxnet1_9_0-pyspark2_4_8](https://github.com/horovod/horovod/runs/4700722148?check_suite_focus=true). As far as I can tell, these are not directly related to the proposed CMake changes. Perhaps the recent update to PyTorch 1.10.1 has made it more likely to run into them.
These related fixes come with this PR:
1. Properly reset internal state of `ProcessSetTable` when finalizing Horovod: In debug builds with Gloo, where Horovod is re-initialized after each torch test, an assertion would fail otherwise on such a re-init. Internal process set IDs now get more reasonable values, but I don't think this caused further bugs.
2. Add a …

Fix finalization of ProcessSetTable and some test flakiness with PyTorch 1.10.1

---

horovod/torch/mpi_ops_v2.cc

Fixes #3352. I've run the test suite from `tests/parallel/test_torch.py` 15 times in the environment described in the issue and did not encounter any hang.
I hope releasing the GIL here is not unsafe in any way.

PyTorch: Release Python GIL when yielding in foreground thread

---

horovod/common/controller.cc
horovod/common/ops/adasum/adasum.h
horovod/common/ops/collective_operations.cc

CodeQL identified a few integer multiplications that might overflow before cast to a larger type:
```
Multiplication result may overflow 'int' before it is converted to 'int64_t'.
This rule finds code that converts the result of an integer multiplication to a larger type.
Since the conversion applies after the multiplication, arithmetic overflow may still occur.
```
See [CWE-190](https://cwe.mitre.org/data/definitions/190.html) [CWE-192](https://cwe.mitre.org/data/definitions/192.html) [CWE-197](https://cwe.mitre.org/data/definitions/197.html) [CWE-681](https://cwe.mitre.org/data/definitions/681.html).
Fixes:
https://github.com/horovod/horovod/security/code-scanning/3
https://github.com/horovod/horovod/security/code-scanning/4
https://github.com/horovod/horovod/security/code-scanning/5 …

Fix possible integer overflow in multiplication

---

horovod/runner/js_run.py
test/single/test_run.py
test/utils/common.py

This addresses use of tempfile.mktemp() which [is not secure](https://docs.python.org/3/library/tempfile.html#deprecated-functions-and-variables). Another process may create a file with the same name in the time between the call to mktemp() and subsequent attempt to create the file by the first process.
- [x ] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ x] Did you update the docs?

Replaced use of tempfile.mktemp() with tempfile.mkstemp()

---

horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/spark/lightning/datamodule.py
horovod/spark/lightning/estimator.py
horovod/spark/lightning/remote.py
horovod/spark/torch/estimator.py
horovod/spark/torch/remote.py
test/integration/test_spark_lightning.py

In some cases (using pre-partitioned or sorted data), trainer doesn't
need data loader to shuffle rows. In this case, we should disable row groups
shuffling in Petastorm as well.

Spark: don't shuffle row groups if training data requires non-shuffle

---

horovod/spark/common/store.py
horovod/spark/keras/estimator.py
horovod/spark/lightning/estimator.py
horovod/spark/torch/estimator.py
test/integration/test_spark_lightning.py

Fixes #3268. Creating a ```copy()``` method to replace ```put()``` while syncing from local temporary directory to run path. ```put()``` is inconsistent with cp and currently has no mechanism to paste the contents from source directory to target without pasting the source directory itself if the target directory is already present, this case is unwanted for horovod and replacing this creates consistency for checkpoints path for both pytorch and pytorch lightning.

Fixes the checkpoint directory structure for pytorch and pytorch lightning

---

examples/pytorch/pytorch_lightning_mnist.py

Set GPU device with horovod local rank.

example: pytorch_lightning_mnist.py

---

CHANGELOG.md
docs/elastic.rst
horovod/ray/elastic_v2.py
horovod/ray/runner.py
horovod/runner/__init__.py
horovod/runner/elastic/discovery.py
horovod/runner/elastic/driver.py
horovod/runner/elastic/settings.py
horovod/runner/gloo_run.py
horovod/runner/launch.py
test/integration/data/elastic_tensorflow2_main.py
test/integration/data/elastic_tensorflow_keras_main.py
test/integration/data/elastic_tensorflow_main.py
test/integration/data/elastic_torch_main.py
test/integration/elastic_common.py
test/single/test_ray_elastic_v2.py

This adds support for resurrecting blacklisted hosts in elastic mode.
Currently hosts that get blacklisted remain in the blacklist for the lifetime of the job.
This cannot handle transient host failure or a scale-up after as scale-down.
This is especially the case for the Kubeflow mpi-operator on Kubernetes, as it always
gives pods known hostnames from its hostfile.
This patch will allow blacklisted hosts to become whitelisted after a configured cooldown period.
Users can configure the cooldown range by providing the `--blacklist-cooldown-range` parameter like this:
```bash
$ horovodrun -np 8 --blacklist-cooldown-range 10 100 --min-np 4 --max-np 12 --host-discovery-script discover_hosts.py python train.py
```
The above example configures the minimum cooldown period to 10 seconds and the …

Support resurrecting blacklisted hosts

---

horovod/spark/lightning/remote.py

Signed-off-by: Peng Zhang <pengz@uber.com>
The comet logger will fail in local if change save_dir without resume experience. 
Need to always resume the experience with the new save_dir path in arguments.

fix resume logger

---

horovod/common/ops/adasum/adasum_mpi.cc
test/parallel/test_torch.py

re-enable delta optimizer test and fix a bug in adasum communicator init logic
Signed-off-by: TJ <tix@uber.com>
This addresses [issue 3314](https://github.com/horovod/horovod/issues/3314). Torch's delta_optimizer test was disabled due to a deadlock issue with torch 1.10, this is to enable the test with a barrier at the end to properly synchronize. While the main root cause was due to the python GIL which was fixed by this [pr](https://github.com/horovod/horovod/pull/3353), another bug with adasum reduction comm init logic was discovered during debugging, adasum was always initialized relative to mpi_world, the correct relative communicator should be mpi_context->mpi_comm.
https://github.com/horovod/horovod/issues/3314
2. At …

re-enable delta optimizer test and fix a bug in adasum communicator init logic

---

Dockerfile.test.cpu
Dockerfile.test.gpu
docker/horovod/Dockerfile

See https://github.com/pytorch/pytorch/issues/72045.

Pinning pip to 21.0.0 as 22.0.0 cannot install pytorch from html link

---

.buildkite/gen-pipeline.sh
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml
docker/horovod-cpu/Dockerfile
docker/horovod/Dockerfile
test/single/data/expected_buildkite_gpu_heads_pipeline.yaml
test/single/data/expected_buildkite_gpu_non_heads_pipeline.yaml

Lets see how well things work with Ubuntu 20.04.

Upgrade to ubuntu 20.04

---

cmake/Modules/FindMxnet.cmake
cmake/Modules/FindPytorch.cmake
cmake/Modules/FindTensorflow.cmake

CMake executes Python code to detect installed frameworks. If that code fails, there is no trace in the logs, which makes identifying the cause very difficult. We only see it could not find the framework:
```
#44 63.09     CMake Error at /usr/local/lib/python3.8/dist-packages/cmake/data/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
#44 63.09       Could NOT find Mxnet (missing: Mxnet_LIBRARIES) (Required is at least
#44 63.09       version "1.4.0")
#44 63.09     Call Stack (most recent call first):
#44 63.09       /usr/local/lib/python3.8/dist-packages/cmake/data/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
#44 63.09       cmake/Modules/FindMxnet.cmake:65 (find_package_handle_standard_args)
#44 63.09 …
```

Allow stderr of executed cmake python code appear in logs

---

CHANGELOG.md
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml
horovod/common/util.py
horovod/spark/keras/tensorflow.py
horovod/tensorflow/keras/__init__.py
horovod/tensorflow/keras/callbacks.py
setup.py
test/integration/test_spark.py
test/integration/test_spark_keras.py
test/parallel/test_tensorflow.py
test/parallel/test_tensorflow2_keras.py
test/parallel/test_tensorflow_keras.py

See Tensorflow 2.6.0 [release notes](https://github.com/tensorflow/tensorflow/releases/tag/v2.6.0) for Keras package change:
tf.keras:
Keras been split into a separate PIP package (keras), and its code has been moved to the GitHub repository[keras-team/keras](https://github.com/keras-team/keras). The API endpoints for tf.keras stay unchanged, but are now backed by the keras PIP package. The existing code in tensorflow/python/keras is a staled copy and will be removed in future release (2.7). Please remove any imports to tensorflow.python.keras and replace them with public tf.keras API instead.
3. …

[TF - Fix] Fix imports from tensorflow.python.keras with tf.__version__ >= 2.6.0

---

horovod/tensorflow/mpi_ops.cc
test/parallel/test_tensorflow.py

Signed-off-by: TJ <tix@uber.com>
The tf head gpu and cpu CIs have been failing for a while. These are caused by 2 issues:
1. CPU is failing because keras.layer removed .apply method, we can just use the __call__ convention to pass inputs to the layer
2. GPU is failing due to a recent change to kernel registration logic(which I haven't completely figured out). It looks like under some conditions, the GPU kernel is replaced by CPU kernel of the Join op which result in "fake" allreduces from the joined rank being allocated on the wrong device. This will cause a deadlock since other non-joined ranks are waiting indefinitely for the joined ranks to finish allreduce that's not happening on the same device. For Join op, I skip registering the cpu op when allreduce device is set to gpu.
Fixes # …

Fixing GPU and CPU tf head failures

---

horovod/spark/runner.py

In Elastic Spark, the initial task-to-task registration has to use the actual next index, not the index + 1, as in elastic mode not all indices might exist on initialisation.
Fixes these errors:
```
Exception in thread Thread-18:
File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.7/dist-packages/horovod/spark/runner.py", line 179, in notify_and_register
next_task_addresses = driver.all_task_addresses(next_task_index)
File "/usr/local/lib/python3.7/dist-packages/horovod/runner/common/service/driver_service.py", line 112, in all_task_addresses
return self._all_task_addresses[index].copy()
KeyError: 2 …
```

Fix indices in initial task-to-task registration

---

horovod/spark/common/store.py

Signed-off-by: Peng Zhang <pengz@uber.com>
making the checkpoint file name optional to enable user to save model checkpoint in `.h5` format.

Make checkpoint name optional so that user can save to h5 format.

---

.github/workflows/codeql-analysis.yml
Dockerfile.test.cpu
Dockerfile.test.gpu
docker-compose.test.yml
docker/horovod-cpu/Dockerfile
docker/horovod-ray/Dockerfile
docker/horovod/Dockerfile
docs/install.rst
setup.py

This is a follow-up to PR #3261, which would require users of many distros to install a recent CMake from an external source (like `pip`).
If such a situation is identified in `setup.py`, we can automatically install a sufficiently recent CMake to a temporary directory and use that to build Horovod. That directory is cleaned up afterwards and the user or system environment is not affected. If `HOROVOD_CMAKE` is set, only that CMake binary is used without any change of behavior.

Build Horovod with temporarily installed CMake if necessary

---

docker/horovod-cpu/Dockerfile
docker/horovod-ray/Dockerfile
docker/horovod/Dockerfile

This fixes an issue introduced last minute by #3371. For some packages, `apt-get` requires user input and waits forever. With `DEBIAN_FRONTEND=noninteractive`, this is avoided.

Move apt-get into non-interactive mode

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml

Docker images are built at the end of our pipeline. If they get stuck, they run for 6 hours, cannot be cancelled and block newer commits in the branch. This reduces the timeout to 1h.

Add timeout to docker build

---

CHANGELOG.md
setup.py

Required by fsspec callback used in horovod/spark/common/store.py
Authored-by: Sammy Nah <sammy.nah@intel.com>
Fixes #3450.

[Setup] Require fsspec >= 2010.07.0

---

CHANGELOG.md
horovod/common/ops/cuda/CMakeLists.txt

The cuda architecture flags were ignored during our build:
```
ELF file    1: mpi_lib_v2.cpython-38-x86_64-linux-gnu.1.sm_52.cubin
ELF file    2: mpi_lib_v2.cpython-38-x86_64-linux-gnu.2.sm_35.cubin
ELF file    3: mpi_lib_v2.cpython-38-x86_64-linux-gnu.3.sm_50.cubin
ELF file    4: mpi_lib_v2.cpython-38-x86_64-linux-gnu.4.sm_60.cubin
ELF file    5: mpi_lib_v2.cpython-38-x86_64-linux-gnu.5.sm_61.cubin
ELF file    6: mpi_lib_v2.cpython-38-x86_64-linux-gnu.6.sm_70.cubin
ELF file    7: mpi_lib_v2.cpython-38-x86_64-linux-gnu.7.sm_80.cubin
```
Looking at the build output, nvcc was building the cuda object files with the good architecture flags but was doing device linking as a separate step (CUDA_SEPARABLE_COMPILATION) without any architecture flags.
We could add the flags to the extra device …

Fix ignored cuda arch flags

---

.buildkite/gen-pipeline.sh
.github/workflows/ci.yaml
docker-compose.test.yml
test/single/data/expected_buildkite_gpu_non_heads_pipeline.yaml

Looks like PyTorch v1.11.0 is available on https://download.pytorch.org/whl/torch_stable.html though it is not listed as released at https://pypi.org/project/torch/#history. The nightly version currently is `1.12.0.dev20220308+cpu`.
PyTorch v1.11. has just been released: https://github.com/pytorch/pytorch/releases/tag/v1.11.0
Add this version to the test space. It removes PyTorch `1.7.1`.

Upgrade PyTorch test version to 1.11.0

---

docs/elastic.rst
horovod/ray/elastic.py
horovod/ray/elastic_v2.py
horovod/runner/__init__.py
horovod/runner/common/util/hosts.py
horovod/runner/elastic/driver.py
horovod/runner/elastic/settings.py
horovod/runner/gloo_run.py
horovod/runner/launch.py
horovod/spark/driver/driver_service.py
horovod/spark/runner.py
test/integration/elastic_common.py
test/integration/elastic_spark_common.py
test/integration/test_interactiverun.py
test/integration/test_spark.py
test/integration/test_spark_lightning.py
test/integration/test_spark_torch.py
test/integration/test_static_run.py
test/single/test_elastic_driver.py
test/single/test_ray_elastic.py
test/single/test_ray_elastic_v2.py
test/single/test_run.py
test/utils/spark_common.py

Horovod uses `np` and `num_proc` synonymously across APIs, but not consistently one or the other.
This deprecates the use of `np` in favour of the more meaningful `num_proc`. The `np` variants are kept in public APIs to avoid breaking user code, while a deprecation warning is given. The deprecated variants should be removed in `v1.0.0` or `v1.1.0`.

Deprecate use of np, min_np, max_np, replace with num_proc

---

horovod/runner/elastic/discovery.py
test/single/test_elastic_discovery.py
test/single/test_elastic_driver.py

Fixes empty hostname returned from HostDiscoveryScript and make sure hostname is not empty.
Context:
When discovery script return nothing, HostDiscoveryScript will treat the empty result i.e. "" string as the available host.
It will fail training job as launcher cannot ssh on the host with empty address. Discovery script can return nothing when no workers are available or new workers are not ready yet.

Fixes empty hostname returned from HostDiscoveryScript

---

horovod/runner/elastic/driver.py

When any error other than a `RuntimeError` occurs, the host discovery thread silently dies, and the training process is unaware of any changes in the list of hosts.
Fix this by catching any `BaseException` instead.

Catch BaseException in host discovery thread to prevent silently dying

---

CHANGELOG.md
cmake/Modules/FindNCCL.cmake

Signed-off-by: Nicolas Castet <26874160+nvcastet@users.noreply.github.com>
Our build default is to link against NCCL static lib. Unfortunately, if this one is unfound (e.g. in NGC containers), the build will fail.
Adding a fallback to trying to link against NCCL shared lib if static is not found and `HOROVOD_NCCL_LINK` is not set to `STATIC`.

Fallback to NCCL shared lib if static one is not found

---

horovod/runner/gloo_run.py
test/integration/test_spark.py

Some environment variables on the host that runs `horovodrun` might not be supported by the remote shell (#3487). Looks like `env` does support those.

Use env to set environment vars in remote shell

---

horovod/tensorflow/gradient_aggregation_eager.py
test/parallel/test_tensorflow2_keras.py

Fixes gradient update timing in TF LocalGradientAggregationHelperEager.
Why?
The gradient updating timing in LocalGradientAggregationHelperEager was set one step before the locally aggregated gradients are allreduced. Therefore, the applied gradient are the locally aggregated gradient instead of the allreduced gradient. This PR fixes the issue.
The PR also improves the gradient aggregation test case to cover tf.IndexedSlices gradient and validates the updated values. Before the change, the grad and values are always zero which does not test anything. 
3. If any member of the technical steering …

Fixes gradient update timing in TF AggregationHelperEager

---

horovod/tensorflow/gradient_aggregation_eager.py
test/parallel/test_tensorflow2_keras.py

Fixes resource not found error in TensorFlow LocalGradientAggregationHelperEager.
When gradient aggregation is enabled with sparse gradient input, the following resource not found error will be thrown in LocalGradientAggregationHelperEager. Please check the newly added test case to reproduce the error. 
```
tensorflow.python.framework.errors_impl.NotFoundError:  Resource localhost/_AnonymousVar8/N10tensorflow3VarE does not exist.
[[{{node StatefulPartitionedCall/AssignAddVariableOp}}]] [Op:__inference_train_function_600]
```
The error message means the anonymous tf.Variable created for local gradient aggregation in LocalGradientAggregationHelperEager hasn't been initialized yet. Here is why.
LocalGradientAggregationHelperEager defines its `compute_gradients` as a tf.function. When a …

Fix resource not found error in TF AggregationHelper

---

CHANGELOG.md
horovod/common/common.h
horovod/common/ops/nccl_operations.cc
horovod/common/ops/nccl_operations.h
horovod/mxnet/adapter.cc
horovod/mxnet/adapter.h
horovod/tensorflow/mpi_ops.cc
horovod/tensorflow/xla_mpi_ops.cc
horovod/torch/adapter_v2.cc
horovod/torch/adapter_v2.h

Some developers have reported performance issues with the `alltoall` implementation in a TF workflow. With profiling, I found that one source of performance loss is in the implementation of the allocation of the output buffer in TF. In the current implementation, the output allocation triggers a device sync (https://github.com/horovod/horovod/blob/master/horovod/tensorflow/mpi_ops.cc#L341), which stalls the GPU launch pipeline and introduces some unneeded latency. This sync was also reported in #3457. This type of launch stalling and associated latency is particularly problematic for `alltoall` since it is typically used in the critical path of the model and usually is not overlapped with other work.
This PR uses CUDA events and CUDA stream wait operations to replace the CPU sync on …

Make TensorFlow output allocations asynchronous when using NCCL backend.

---

horovod/tensorflow/gradient_aggregation_eager.py
test/parallel/test_tensorflow2_keras.py

Fixes #3504
When clearing the locally aggregated/added gradient, we should rather assign with `tf.zeros_like`, because substracting by the local aggregated value doesn't work for infinite gradients.
Added a unit test for this. Without the change it'll fail.

clear locally accumulated gradient by assigning with zeros_like to avoid infinite gradient not correctly cleared up

---

horovod/spark/common/store.py
test/integration/test_spark.py

Signed-off-by: Weichen Xu <weichen.xu@databricks.com>
Fix bugs in DBFSLocalStore.
1. Make DBFSLocalStore support "file:/dbfs/..." style path
2. Make DBFSLocalStore implement `get_localized_path` correctly.
3. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
4. If any member of the technical steering committee requests changes, they must be addressed.

Fix bugs in DBFSLocalStore

---

cmake/build_utils.py

Use 
```
-gencode=arch=compute_xy,code=\"sm_xy,compute_xy\"
```
instead of
```
-gencode=arch=compute_xy,code=compute_xy
-gencode=arch=compute_xy,code=sm_xy
```
for the highest arch, which avoids generating ptx a second time. This slightly improves nvcc compilation time.

Avoid redundant ptx generation for maximum specififed compute capability

---

CHANGELOG.md
horovod/__init__.py

This is a cherry-pick from the `hotfix-0243` branch.

Bump version to 0.24.3

---

setup.py

The PyTorch Lightning dependency is only needed if using the PyTorchEstimator, which requires the `pytorch-spark` extras. For users only using the `horovod.torch` submodule, this imposes an extra dependency they do not necessarily need.

Move pytorch_lightning requirement to pytorch-spark extras

---

CHANGELOG.md
horovod/runner/__init__.py
horovod/runner/common/util/settings.py
horovod/runner/launch.py

Reworks network interfaces arguments in two places: the `horovod.run` API and the `horovodrun` CLI:
The `horovod.run` API deprecates `network_interface` argument in favour of `network_interfaces`, which becomes a list of strings, rather than a comma separated string that is to be split.
The `horovodrun` CLI replaces `--network-interface` with semantically more accurate `--network-interfaces`, which still takes a comma separated string of network interfaces, but also provides the new `--network-interface` argument, that semantically correctly expects a single network interface. That argument can be used multiple times to set multiple NICs.
Arguably, `--network-interfaces` could be removed completely, as `--network-interface` allows to specify multiple NICs. Unless, there is any use of …

Rework network interfaces args in horovod.run and horovodrun

---

examples/spark/pytorch/pytorch_lightning_spark_mnist.py
test/integration/test_spark_lightning.py

save_hyperparameters() should be called to save arguments passed into
the LightningModule init() function.

[Spark/Lightning]: Fix PTL Spark example with checkpoint usage

---

Dockerfile.test.gpu
docker/horovod-ray/Dockerfile
docker/horovod/Dockerfile
horovod/spark/common/params.py
horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/spark/lightning/estimator.py
horovod/spark/lightning/remote.py
horovod/spark/torch/estimator.py
horovod/spark/torch/remote.py
test/integration/test_spark_keras.py

Signed-off-by: TJ <tix@uber.com>
Sometimes the estimator can be created on a GPU host which initializes model weights on one device. Pinning to GPU again in remote trainer can have strange behaviors such as "Variable resource not found" error for Tensorflow since tf thinks the model weights were initialized on a different device.
https://github.com/horovod/horovod/issues/3524

Add an option to pin to gpu for all estimators

---

.buildkite/gen-pipeline.sh
.github/workflows/ci.yaml
examples/mxnet/mxnet2_mnist.py
examples/pytorch/pytorch_mnist.py
examples/tensorflow2/tensorflow2_keras_mnist.py
examples/tensorflow2/tensorflow2_mnist.py
test/single/data/expected_buildkite_gpu_heads_pipeline.yaml
test/single/data/expected_buildkite_gpu_non_heads_pipeline.yaml

This makes some examples runnable through the `horovod.run` API rather than `horovodrun`.
Those examples are also added to the CI (only tested on CPU).

Test examples running through API not horovodrun

---

CHANGELOG.md
horovod/spark/lightning/datamodule.py
horovod/spark/lightning/remote.py
horovod/spark/torch/remote.py

Spark/Lightning: add missing tranform_spec for Petastorm datamodule

---

.github/gen-workflow-ci.py
.github/workflows/ci-results.yaml
.github/workflows/ci.yaml

This splits the job that triggers Buildkite CI and downloads results into two jobs:
is split into trigger and download jobs:
In case of a download timeout or any other error while waiting for the results, rerunning the failed job does not rerun the CI but only downloads the results.
Example run (with reduced tests): https://github.com/horovod/horovod/actions/runs/2429186983/attempts/1
Re-run does not trigger a new CI: https://github.com/horovod/horovod/actions/runs/2429186983/attempts/2

Split Buildkite job for better re-run

---

.github/workflows/ci-results.yaml

Downloading results from Buildkite broke in #3563 for `CI (Results)` workflow (not the main `CI` workflow). This fixes it.

Fix `CI (Results)` workflow

---

CHANGELOG.md
README.rst
docs/install.rst
docs/summary.rst

Follow up for #3558 with new compiler requirements; also updating the changelog for #3513.
> 
> > Do we need to amend the documentation (where it mentions CMake dependency) and CHANGELOG.md?
> > 
> > We can do that in a follow up PR to avoid full CI cycles for these changes.
> 
> Good point! And I agree that it would be wise to do this in a separate PR.
> 
> CMake supports C++17 from version 3.8, so hopefully we should be good there with 3.13+. https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html
> 
> `gcc` seems to support all features of C++17 starting with version 8. https://gcc.gnu.org/projects/cxx-status.html#cxx17
> 
> We could add a phrase then like: "To install Horovod with TensorFlow 2.10 or later you will need a compiler that supports C++17 like `g++8` or newer."
> 
1. …

Update docs and changelog for PR #3558

---

.buildkite/gen-pipeline.sh
.github/workflows/ci.yaml
examples/elastic/tensorflow2/tensorflow2_mnist_elastic.py
horovod/runner/__init__.py
horovod/runner/gloo_run.py
horovod/runner/http/http_client.py
horovod/runner/launch.py
horovod/runner/run_task.py
horovod/spark/gloo_run.py
horovod/spark/runner.py
test/integration/elastic_spark_common.py
test/single/data/expected_buildkite_gpu_heads_pipeline.yaml
test/single/data/expected_buildkite_gpu_non_heads_pipeline.yaml
test/single/test_elastic_run.py

Currently, the elastic training mode can only be used through `horovodrun` and not the existing `horovod.run` API.
This allows to run `horovod.run` with `min_num_proc` or `host_discovery_script` set to run a `func` in elastic  mode.

Add elastic run api

---

horovod/spark/common/params.py
horovod/spark/common/util.py
horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/spark/lightning/estimator.py
horovod/spark/lightning/remote.py
horovod/spark/torch/estimator.py
horovod/spark/torch/remote.py
test/integration/test_spark_keras.py
test/integration/test_spark_lightning.py

Expose an parameter through all spark estimators to set start method for multiprocessing.
This is to avoid resource leaks in situations where CUDA calls are made in multiprocessing environment. According to CUDA [guidelines](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#um-fork-managed-memory), calling CUDA kernels on pinned memory region in forked processes will lead to undefined behavior such as handles not being cleared. Some leaks persist even when the process terminates.
3. If any member of the technical steering committee requests changes, they must be …

Expose an parameter through all spark estimators to set start method for multiprocessing

---

CHANGELOG.md
horovod/common/controller.h
horovod/common/mpi/mpi_controller.h
horovod/common/nvtx_op_range.cc
horovod/common/nvtx_op_range.h
horovod/common/operations.cc
horovod/common/ops/gloo_operations.h

In #3299 I forgot to register the `"HorovodReducescatter"` string with NVTX to use it in named op ranges. This means that `Reducescatter` ops would appear as "[Unknown]" in Nsight Systems profiles.
Besides that change I've defined virtual destructors for two abstract polymorphic base classes. This should fix a warning that has been mentioned in https://github.com/horovod/horovod/pull/3541. Generally I think having them virtual is a safer practice, but currently there probably is no actual problem because smart pointers (`std::shared_ptr` or `std::unique_ptr`) are used rather than raw base class pointers.

Add NVTX op tracing for Reducescatter, make base class destructors virtual

---

horovod/tensorflow/mpi_ops.cc

Since TensorFlow has moved to `_GLIBCXX_USE_CXX11_ABI=1`, we have ran into some issues with Horovod related to the use of `std::regex` when we build TF/Horovod on manylinux2014. `HorovodBroadcastInplaceOp` was crashing when `std::regex` was used.
To fix the problem, I replaced the regex with something simpler which is probably also faster and more lightweight.

Remove std::regex use for better cxx11 abi compatibility

---

.github/workflows/ci-results.yaml

This moves CI to use v2 of the publish action.

Use test result publish action v2

---

examples/elastic/tensorflow2/tensorflow2_mnist_elastic.py
examples/tensorflow/tensorflow_mnist_eager.py
examples/tensorflow2/tensorflow2_mnist.py

In `tensorflow_mnist.py` loss value was printed on every node (`local_rank == 0`) not only on global master process. I do not see any benefit from doing that. Moreover, it may confuse people why the printed loss values differ across nodes (I know loss values are not synchronized). 
I think it was simply a typo to use `local_rank == 0` instead of `rank() == 0`. If not, feel free to reject and close this PR.

fix local_rank typo in TF 2 example

---

cmake/Modules/FindPytorch.cmake

Fixes typo in FindPytorch.cmake. REGEX could not match for ROCm error message.

Fix Typo in FindPytorch.cmake

---

horovod/spark/lightning/datamodule.py

Spark/Lightning: add reader_worker_count and reader_pool_type

---

test/parallel/test_torch.py

I believe this change should fix test failures / hangs observed with PyTorch nightly in the CI.
For a detailed explanation see https://github.com/horovod/horovod/issues/3570#issuecomment-1192751996.
Fixes #3570.

torchhead: fix integer division rounding in unit test

---

CHANGELOG.md

On my computer (macOS 12.4, M1 Pro) this fixes building Horovod with PyTorch. Note that the problem does not occur if one builds with TensorFlow, too.
We need to make sure to build with a version of Eigen that's recent enough to include the commit https://gitlab.com/libeigen/eigen/-/commit/fd1dcb6b45a2c797ad4c4d6cc7678ee70763b4ed; else we get duplicate symbol errors. The latest release 3.4.0 includes the fix, which is why I opted for that version: https://gitlab.com/libeigen/eigen/-/tags/3.4.0 (commit hash 3147391d).
When we build with TensorFlow, we don't use Eigen from the submodule, but we use the version of the library that ships with the TF package. For that reason I believe that this change will not affect anything running in the CI: As far as I know, there, we always build with all …

Update Eigen submodule to fix build on macOS with aarch64

---

CHANGELOG.md
horovod/common/controller.cc
horovod/common/ops/cuda/cuda_kernels.cu
horovod/common/ops/gpu_operations.cc
horovod/common/ops/gpu_operations.h
horovod/common/ops/rocm/hip_kernels.cu

In a similar fashion to the recent PR #3590 for Allgather, this adds support for more efficient, batched memory copies in the GPU implementation of Reducescatter.
I've also fixed a related minor bug in `Controller::FuseResponses()`, where extra padding bytes were counted mistakenly for Reducescatter when aggregating tensors up to fusion buffer size.
To improve memory alignment this padding could be introduced for Reducescatter (and Allgather), too, but it would be a bit trickier to get right than for Allreduce.
3. If any member of the technical steering committee requests changes, they must be …

Add support for batched memory copies in GPUReducescatter

---

CHANGELOG.md
docs/requirements.txt
horovod/common/common.h
horovod/common/nvtx_op_range.cc
horovod/common/nvtx_op_range.h
horovod/common/operations.cc
horovod/common/operations.h
horovod/common/ops/collective_operations.cc
horovod/common/ops/collective_operations.h
horovod/common/ops/nccl_operations.cc
horovod/common/ops/nccl_operations.h
horovod/mxnet/__init__.py
horovod/mxnet/adapter.cc
horovod/mxnet/adapter.h
horovod/mxnet/mpi_ops.cc
horovod/mxnet/mpi_ops.h
horovod/mxnet/mpi_ops.py
horovod/tensorflow/__init__.py
horovod/tensorflow/mpi_ops.cc
horovod/tensorflow/mpi_ops.py
horovod/torch/__init__.py
horovod/torch/adapter_v2.cc
horovod/torch/adapter_v2.h
horovod/torch/mpi_ops.py
horovod/torch/mpi_ops_v2.cc
test/parallel/base_test_mxnet.py
test/parallel/test_mxnet1.py
test/parallel/test_tensorflow.py
test/parallel/test_tensorflow_process_sets.py
test/parallel/test_torch.py

This adds two new multi-tensor functions to Horovod: `hvd.grouped_allgather()` and `hvd.grouped_reducescatter()`. They are very similar to the existing `hvd.grouped_allreduce()`, introduced with PR #2453, giving users the equivalent extra control over tensor fusion for their `Allgather` and `Reducescatter` ops.
To implement this functionality I've added a new attribute `output_index` to `TensorTableEntry`. This allows an `AllgatherOp` or `ReducescatterOp` that has been enqueued as part of a group to allocate its output tensor properly (in contrast to `Allreduce` this cannot be done beforehand because the resulting output size is only known after cross-process coordination). I've also added warning log messages in case `AllocateOutput` ever fails because TensorFlow would crash with just a …

Add hvd.grouped_allgather and hvd.grouped_reducescatter

---

CHANGELOG.md
horovod/tensorflow/__init__.py

This PR adds a couple of additional functionalities to `DistributedGradientTape` to enable better gradient handling for model parallel cases.
1. Added new method `register_local_source` to `DistributedGradientTape`: This enables users to mark a source/variable as worker local so Horovod will skip performing any global averaging on gradients associated with that variable during a call to `gradients` and will instead return the unmodified local gradient. For example:
```
tape = hvd.DistributedGradientTape(tape)
for var in model.trainable_variables:
if <var is worker local>:
tape.register_local_source(var)
gradients = tape.gradient(loss, model.trainable_variables)
```
2. Added a new option `use_generic_names` to the `gradients` method: In model parallel scenarios, it is often the case that …

Add register_local_source and use_generic_names funtionality to DistributedGradientTape for TF.

---

horovod/common/gloo/gloo_controller.cc

For historical reasons, if gloo is used when negotiating, the allgather and allgatherv interfaces will be used for control communication.
But gloo now provided gather, gatherv interfaces, so replace the original allgather with gather and replace the original allgatherv with gatherv.
There will also be some improvement in performance

When negotiating, replace gloo allgather with gather

---

CHANGELOG.md
horovod/tensorflow/gradient_aggregation.py
horovod/tensorflow/gradient_aggregation_eager.py

When gradient accumulation is enabled (`backward_passes_per_step > 1`), the underlying optimizer iteration count update uses the `optimizer._iterations` private variable which might not be exposed for custom optimizers such as the [LossScaleOptimizer](https://github.com/keras-team/keras/blob/059781f3b02ff01d419637c76de833002869ff92/keras/mixed_precision/loss_scale_optimizer.py#L587) in keras. 
The users who have been using such optimizers would not have incremented the underlying iterations property as we just return a `tf.no_op()`, which in turn affects the update calculation. For instance, when we wrap  `Adam` optimizer with `LossScaleOptimizer`, the adam updates would have been miscalculated. This PR fixes this issue by using the safer `iterations` property.
1. All tests and other …

fix the optimizer iteration count when gradient accumulation is enabled

---

CHANGELOG.md
horovod/torch/adapter_v2.cc

This PR fixes what appears to be a quite serious bug in the handling of buffer allocations in the PyTorch backend that was discovered and reported by @eordentlich at NVIDIA. The issue is that the current implementation does not enforce any type of synchronization after PyTorch buffers are allocated. This is a problem because the PyTorch allocations can be completed asynchronously and not enforcing a sync or recording a dependency using an event results in a race condition when writing to these buffers. This was handled appropriately in the TensorFlow implementation (see: https://github.com/horovod/horovod/blob/ed15ddc8f269664d4a89671b33960d0fab9f2dd9/horovod/tensorflow/mpi_ops.cc#L404-L411), but similar code was never introduced for the PyTorch backend. I've added equivalent …

Fix race condition in PyTorch allocation handling.

---

horovod/common/ops/nccl_operations.h

add rccl p2p variable

---

test/parallel/test_process_sets_multi_comm.py
test/parallel/test_tensorflow2_keras.py
test/parallel/test_tensorflow2_keras_process_sets.py
test/parallel/test_tensorflow_process_sets.py
test/parallel/test_tensorflow_process_sets_dynamic.py
test/parallel/test_xla.py
test/parallel/test_xla_process_sets.py

As observed in #3557 there can be significant slowdowns with TensorFlow 2.9 when `HOROVOD_DYNAMIC_PROCESS_SETS=1` is set and MPI is used rather than Gloo. This PR refactors most process-set-specific tests for TensorFlow so they work with statically initialized process sets. This should avoid timeouts in CI pipelines on GPU-equipped AWS hosts.

TF: Make most tests use statically initialized process sets

---

CHANGELOG.md
horovod/tensorflow/__init__.py
test/parallel/test_tensorflow.py

Signed-off-by: Ata FatahiBaarzi <afatahibaarzi@linkedin.com>
This PR builds upon #3628 and adds a new API called `PartialDistributedGradientTape(tape, [local_layers], ...)` for model parallel use cases where unlike DistributedGradientTape() ranks only sync a subset of gradients and skip the gradients of their "local layers". A sample usage is shown in the unit test included with this PR.

add PartialDistributedGradientTape API

---

CHANGELOG.md
horovod/tensorflow/mpi_ops.cc
test/parallel/test_tensorflow.py
test/parallel/test_tensorflow_process_sets.py
test/parallel/test_xla.py
test/parallel/test_xla_process_sets.py

This PR adds support for `int8` and `uint8` allreduce in tensorflow along with the relevant tests. 
Corresponding issue:  https://github.com/horovod/horovod/issues/3642
Signed-off-by: Vignesh Kothapalli <k.vignesh1420@gmail.com>

feat: support uint8 and int8 allreduce in tensorflow

---

CHANGELOG.md
horovod/spark/common/params.py
horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/spark/keras/util.py
horovod/spark/lightning/datamodule.py
horovod/spark/lightning/estimator.py
horovod/spark/lightning/remote.py
horovod/spark/torch/estimator.py
horovod/spark/torch/remote.py
setup.py
test/integration/test_spark_keras.py
test/integration/test_spark_lightning.py
test/integration/test_spark_torch.py

Added:
- Petastorm reader level is used to parallelize shuffling samples.
- Random seed is added for Lightning datamodule to generate
reproducible data loading outputs.
Changed:
- Default reader pool is changed from `process` to `thread` for lower
memory usage.
Deprecated:
- `shuffle_buffer_size` field is removed. Global shuffle is enabled by default.
Use `shuffle` to enable shuffle or not.

Spark: adapt Petastorm 0.12.0 changes to speedup data shuffling

---

CHANGELOG.md
horovod/_keras/__init__.py
horovod/tensorflow/__init__.py
horovod/tensorflow/gradient_aggregation.py
horovod/tensorflow/gradient_aggregation_eager.py
test/parallel/test_tensorflow2_keras.py

This is to continue work done in #3628 and #3643 and adds the same functionality to the Distributed Optimizers and Local Gradient Aggregators. This is useful for model parallel use cases that use distributed optimizers and want to skip syncing their "local" gradients.
An example usage is shown in the unit tests included PR, but in short it's like the following:
```python
...
opt = hvd.DistributedOptimizer(opt)
for var in model.trainable_variables:
if <var is worker local>:
opt.register_local_var(var)
gradients = opt.compute_gradients(loss, model.trainable_variables, tape)
```
If this change get merged, similar to #3643 we can possibly add a new API called `PartialDistributedOptimizer`.

TF: Add register_local_var to distributed optimizers and gradient aggregators

---

CHANGELOG.md
CMakeLists.txt

In #3444 we've added a mechanism that helps CMake find `nvcc` when it's missing in `$PATH`, but the CUDA toolkit can still be found at a typical location. It has now been observed that this does not work as intended on older versions of CMake like 3.13 or 3.16 (#3545). 
CMake would go into an infinite loop with messages like 
```
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CUDA_COMPILER= NOTFOUND
```
`NOTFOUND` is the initial value assigned to `CMAKE_CUDA_COMPILER` by `check_language`, which is written to CMake's build cache then. We override it to a proper value `set(CMAKE_CUDA_COMPILER "${CUDAToolkit_BIN_DIR}/nvcc")`, but this change only appears to be …

Build: Fix finding nvcc (if not in $PATH) with older versions of CMake

---

CHANGELOG.md
horovod/common/ops/nccl_operations.cc
horovod/common/ops/nccl_operations.h
horovod/mxnet/__init__.py

NCCL 2.10+ introduced a native `ncclAvg` operation (https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html#c.ncclAvg). This PR enables the use of this feature for versions of NCCL that support it.

Enable use of native ncclAvg op for NCCL allreduces.

---

CHANGELOG.md
horovod/common/controller.cc
horovod/mxnet/mpi_ops.py
horovod/tensorflow/mpi_ops.cc
horovod/torch/__init__.py
test/parallel/base_test_mxnet.py
test/parallel/test_tensorflow.py
test/parallel/test_torch.py

This fixes Horovod crashing when scalar inputs are passed to `hvd.reducescatter` or `hvd.grouped_reducescatter`. Attempts to do so now raise exceptions that users can deal with appropriately.
Initially I thought it would be a good idea to have `hvd.reducescatter(3.14)` do exactly the same thing as `hvd.reducescatter([3.14])`, i.e., return a single-element 1D tensor on rank 0 and an empty 1D tensor on the other ranks. However, having given this some consideration, I feel that it would be confusing and potentially error prone if zero-rank inputs produced higher ranked outputs. It seems less surprising to deal with such a possibility explicitly in user code if necessary (just as it is the case with `hvd.allgather`).
Fixes #3698.

Fix reducescatter() and grouped_reducescatter() to raise clean exceptions for scalar inputs

---

CHANGELOG.md
horovod/_keras/callbacks.py
horovod/keras/callbacks.py
horovod/tensorflow/keras/callbacks.py
test/parallel/test_tensorflow2_keras.py

Signed-off-by: Ata FatahiBaarzi <afatahibaarzi@linkedin.com>
This PR is continuation of #3695, #3643, and #3628  and adds support for local variables for BroadcastGlobalVariablesCallback. So in model parallel use cases, the only the initial value of non-local variables are broadcasted.
An example use case is provided in the unit test included with this PR, but, in short, the callback will be used as follows:
```bash
...
local_variables = <local variables to current rank>
callbacks = [hvd.callbacks.BroadcastGlobalVariablesCallback(root_rank=root_rank, local_variables=local_variables)]
model.fit(..., callbacks=callbacks)
...
```

Support registering local variables for BroadcastGlobalVariablesCallback

---

CHANGELOG.md
horovod/spark/keras/estimator.py
horovod/spark/keras/optimizer.py
horovod/spark/keras/tensorflow.py
test/integration/test_spark_keras.py
test/parallel/test_tensorflow2_keras.py
test/parallel/test_tensorflow2_keras_process_sets.py

We haven't figured out a way to save and load wegihts for default reworked optimizers in Keras 2.11+.

Keras: Support only legacy optimizers in Keras 2.11+

---

.github/workflows/ci-results.yaml

Buildkite tests on forks are run via `ci-results.yaml`. Statuses are created when Buildkite is started and updated as `success` or `failure` when finished. That update did not work because permissions were missing for update step.

Grant status write permissions to update status step

---

CHANGELOG.md
horovod/__init__.py

Releasing v0.26.0.
Please pick your favourite features and note below to be highlighted in release title!
Example: https://github.com/horovod/horovod/releases/tag/v0.25.0.

Bump version to 0.26.0

---

.github/workflows/upload-pypi.yml

Adding `import packaging` to `setup.py` broke the `Upload to PyPi` workflow, which only runs on release. Fixing.

Fix Upload to PyPi workflow

---

.github/workflows/upload-pypi.yml
CHANGELOG.md
setup.py

Previous import was occurring in `setup.py` before `install_requires` had a chance to run, resulting in import failures if `packaging` wasn't already installed:
```
Collecting horovod[pytorch]>=0.24.0
Downloading horovod-0.26.0.tar.gz (3.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 78.7 MB/s eta 0:00:00
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
File "<string>", line 36, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/tmp/pip-install-lthh9g2p/horovod_ef63b9a15f0346eeadef7d18c3901759/setup.py", line 30, in <module>
from packaging import …
```

Fixed packaging import to occur after install_requires

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml

Tests that `setup.py` can build the source package and install Horovod from it. This should catch #3741 and #3739 in the future.
Together with #3741, this builds (without compiling anything) and installs horovod:
https://github.com/horovod/horovod/actions/runs/3245078387/jobs/5322133719#step:4:1068

Test installation via setup.py

---

CMakeLists.txt

Signed-off-by: Lang Xu [xulang7@gmail.com](mailto:xulang7@gmail.com)
Added mpi_gpu_operations.cc linking if MPI and ROCm are built
Fixes #3728

add mpi-gpu-operations linking if MPI and ROCm is built

---

CHANGELOG.md
horovod/common/controller.cc
horovod/common/controller.h
horovod/common/ops/ccl_operations.cc
horovod/common/ops/collective_operations.cc
horovod/common/ops/collective_operations.h
horovod/common/ops/gloo_operations.cc
horovod/common/ops/gpu_operations.cc
horovod/common/ops/gpu_operations.h
horovod/common/ops/mpi_gpu_operations.cc
horovod/common/ops/mpi_gpu_operations.h
horovod/common/ops/mpi_operations.cc
horovod/common/ops/mpi_operations.h
horovod/common/ops/nccl_operations.cc
horovod/common/ops/nccl_operations.h

I noticed in profiling that grouped Allgather operations can have vastly differing run times, in particular with FP16, although they add up to similar fused tensor sizes. For instance, an operation sending 6,292,992 bytes would take < 2 msec, but an operation sending 6,294,530 bytes would take > 7 msec. The decisive difference between these two examples is that, in the faster case, the buffer size is divisible by `2**9`, while there is only one factor of 2 in the other buffer size. 
Sylvain Jeaugey has pointed out in comments that Allgather and Reducescatter in particular benefit from memory alignment to 16 bytes (`2**4`): https://github.com/NVIDIA/nccl/issues/413#issuecomment-718862629, https://github.com/NVIDIA/nccl/issues/256#issuecomment-534192899
I could also measure performance …

Pad fused GPU Allgathers for better memory alignment

---

test/parallel/base_test_mxnet.py
test/parallel/test_mxnet1.py
test/parallel/test_mxnet2.py

Interestingly, `2.0.0beta1` is smaller than `2.0.0`, so we run v1 tests with v2 beta1.

Skip mxnet v1 tests for v2 pre-release

---

examples/spark/pytorch/pytorch_lightning_spark_mnist.py
test/integration/test_spark_lightning.py

Related to the failures we have observed for Torch 1.13+.
https://github.com/horovod/horovod/actions/runs/3492107499/jobs/5845520947#step:219:162
Broken line in PyTorch lightning side:
https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/strategies/horovod.py#L179
Reproducible error with `ReduceOp` in Torch 1.13:
```
>>> from torch.distributed import ReduceOp
>>> op = None
>>> op in (ReduceOp.SUM, None)
File "<stdin>", line 1, in <module>
TypeError: __eq__(): incompatible function arguments. The following argument types are supported:
1. (self: torch._C._distributed_c10d.ReduceOp, arg0: c10d::ReduceOp::RedOpType) -> bool
2. (self: torch._C._distributed_c10d.ReduceOp, arg0: torch._C._distributed_c10d.ReduceOp) -> bool
Invoked with: …
```

Skip EarlyStopping and ModelCheckpoint Callbacks for Torch 1.13+

---

.github/workflows/ci-results.yaml

Without this, not all artifacts might be downloaded or conclusion could not be detected.

GitHub CLI returns at most 30 elements, use --paginate to get all

---

horovod/_keras/__init__.py
horovod/keras/__init__.py
horovod/spark/keras/estimator.py
horovod/spark/keras/optimizer.py
horovod/tensorflow/keras/__init__.py
test/integration/test_spark_keras.py
test/parallel/test_tensorflow2_keras.py
test/parallel/test_tensorflow2_keras_process_sets.py
test/parallel/test_tensorflow_keras.py

Fixes #3793.
This is a band-aid solution; alternatively we could switch to a more lenient version parser.

Fix parsing Keras version identifiers like `2.2.4-tf`

---

cmake/Modules/FindTensorflow.cmake

Fixes #3754 
For context see https://github.com/tensorflow/tensorflow/issues/58281

tf-head: Fix undefined symbols by linking libtensorflow_cc.so.2

---

CHANGELOG.md
horovod/_keras/__init__.py
horovod/tensorflow/__init__.py
test/parallel/test_tensorflow.py

This PR fixes the local gradient scaling introduced in #3719 when the gradients are sparse (e.g. of type `tf.IndexedSlices`).

Handle tf.IndexedSlices types when scaling local gradients in TF.

---

horovod/common/ops/nccl_operations.cc

The MEMCPY_IN_FUSION_BUFFER event accidentally wasn't recorded for NCCLReducescatter, which made Horovod timelines a bit confusing to read.

Timeline: Add MEMCPY_IN_FUSION_BUFFER event for Reducescatter

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml

It looks like installing Python on macOS 12 is broken, it used to work with macOS 11, so pinning tests to `macos-11` rather than `macos-latest` (which recently moved to `macos-12`).

Use macos-11 as macos-latest moved to macOS 12.6.2

---

horovod/common/wire/message_generated.h

Here I've just run `flatc` on `horovod/common/wire/message_generated.fbs`. The generated header file was out of sync regarding one of the `ReduceOp` enum names (as pointed out in #3812). 

Update message_generated.h to match flatbuffers schema

---

CHANGELOG.md
horovod/tensorflow/__init__.py
test/parallel/test_tensorflow.py

In the `grouped_allreduce` routine for TensorFlow, the existing code uses the wrong `indices` array when forming the result. This PR corrects this issue and also adds proper support for mixed argument lists of tensors and `tf.IndexedSlices` to `grouped_allreduce`. It was also discovered during development of this PR that there were issues in properly handling `op` and `prescale_factor` and `postscale_factor` for both `allreduce` and `grouped_allreduce` so that was fixed as well. 
To catch these issues better in the future, numerous tests of the `tf.IndexedSlices` path for allreduce, as well as expanded testing of the `grouped_allreduce` were added.

Several fixes for allreduce and grouped allreduce handling of tf.IndexedSlices.

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Parallel tests run through `horovodrun` already produce logs where the beginning of each output line is marked with the rank of the process that wrote it. For example:
```
[1]<stdout>:test_common.py::CommonTests::test_gloo_built PASSED
[1]<stdout>:test_common.py::CommonTests::test_mpi_built PASSED
[0]<stdout>:test_common.py::CommonTests::test_gloo_built PASSED
[0]<stdout>:test_common.py::CommonTests::test_mpi_built PASSED
```
This enables the same feature for tests run via `mpirun` under OpenMPI or MPICH.

CI: Label log lines of tests run under MPI with process rank

---

setup.py

Spark tests fail since the latest release of pyarrow, which appears to bring in API changes.
Fixes #3829

Pin pyarrow < 11.0

---

CHANGELOG.md
examples/tensorflow2/tensorflow2_keras_mnist.py
examples/tensorflow2/tensorflow2_mnist_data_service_train_fn_compute_side_dispatcher.py
horovod/_keras/__init__.py
horovod/common/util.py
horovod/keras/__init__.py
horovod/spark/keras/estimator.py
horovod/spark/keras/optimizer.py
horovod/tensorflow/__init__.py
horovod/tensorflow/keras/__init__.py
test/integration/data/elastic_tensorflow2_main.py
test/parallel/test_tensorflow2_keras.py

Signed-off-by: Nicolas Castet <ncastet@nvidia.com>
Horovod was only checking for `tf.keras.optimizers.Optimizer` in  `DistributedOptimizer` but supported optimizers are under `tf.keras.optimizers.legacy.Optimizer` for Keras 2.11+.

Fix broken TF DistributedOptimizer with Keras 2.11+

---

CHANGELOG.md
docs/spark.rst
horovod/spark/common/util.py
horovod/spark/keras/remote.py
horovod/spark/lightning/remote.py
horovod/spark/task/task_info.py
horovod/spark/torch/remote.py

Signed-off-by: Li Jiang <bnujli@gmail.com>
When using spark estimators (torch/lightning/keras) in GPU clusters, `get_available_devices` will be called
https://github.com/horovod/horovod/blob/d29bc04488f00426b5a18946d667ee04b4544956/horovod/spark/task/task_info.py#L25-L28
in `_get_assigned_gpu_or_default`.
https://github.com/horovod/horovod/blob/d29bc04488f00426b5a18946d667ee04b4544956/horovod/spark/common/util.py#L766-L774
And the `get_available_devices` will get the devices by calling `_get_resources`.
https://github.com/horovod/horovod/blob/d29bc04488f00426b5a18946d667ee04b4544956/horovod/spark/task/task_service.py#L98-L107
It works well in single-GPU per node clusters. However, when it comes to clusters with multi-GPUs per node. Wrong GPU index may be returned.
For spark clusters, …

Support pinning to local rank GPU index in Spark estimators

---

CHANGELOG.md
horovod/common/controller.cc
horovod/common/operations.cc
horovod/common/operations.h
horovod/common/ops/collective_operations.cc
horovod/common/ops/collective_operations.h
horovod/common/ops/gloo_operations.cc
horovod/common/ops/gpu_operations.cc
horovod/common/ops/gpu_operations.h
horovod/common/ops/mpi_gpu_operations.cc
horovod/common/ops/mpi_operations.cc
horovod/common/ops/nccl_operations.cc
horovod/common/ops/nccl_operations.h
horovod/mxnet/mpi_ops.cc
horovod/mxnet/mpi_ops.h
horovod/mxnet/mpi_ops.py
horovod/tensorflow/__init__.py
horovod/tensorflow/mpi_ops.cc
horovod/tensorflow/mpi_ops.py
horovod/torch/mpi_ops.py
horovod/torch/mpi_ops_v2.cc
test/parallel/base_test_mxnet.py
test/parallel/test_tensorflow.py
test/parallel/test_torch.py

This adds support for the `prescale_factor` and `postscale_factor` arguments to the Reducescatter op. They are equivalent to the arguments of the same name for the Allreduce op. Averaging is now implemented via postscaling with a factor of `1. / process_set.size()`.
In contrast to Allreduce, we can't do the prescaling on the buffer allocated for the output tensor. This is because with Reducescatter the output tensor is smaller than the input tensor, but all input elements need to be prescaled. To avoid an extra temporary allocation, I decided to use the fusion buffer to do this scaling even for unfused tensors (at least with MPI and NCCL; with Gloo we already use a temporary buffer and I haven't updated that part). Of course, this requires the user to enable a sufficiently large fusion …

Add prescale_factor and postscale_factor for Reducescatter

---

CHANGELOG.md
horovod/common/common.h
horovod/common/operations.cc
horovod/common/operations.h
horovod/common/ops/collective_operations.cc
horovod/common/ops/collective_operations.h
horovod/common/ops/gloo_operations.cc
horovod/common/ops/mpi_gpu_operations.cc
horovod/common/ops/mpi_operations.cc
horovod/common/ops/nccl_operations.cc
horovod/common/ops/nccl_operations.h
horovod/mxnet/mpi_ops.cc
horovod/tensorflow/mpi_ops.cc
horovod/torch/mpi_ops_v2.cc
test/parallel/test_torch.py

This change is motivated by the observations posted to discussion #3819: We can compute the shapes of the output tensors of (grouped) Reducescatter operations early, without any inter-process communication, even though the scattered tensors may not be distributed evenly. (Allgather behaves differently in this regard: There, each rank receives exactly the same output tensor, but Horovod cannot determine its size without communication.) We can take advantage of this fact and allocate memory for output tensors early, before the Horovod operation is enqueued, and without blocking the Horovod background thread.
This still happens in the C++ backend, but in framework-specific code. Allocations should be asynchronous with TensorFlow and PyTorch, but as far as I can tell the respective call is …

Reducescatter: Allocate output tensors before enqueuing the operation

---

horovod/torch/CMakeLists.txt

Signed-off-by: Lang Xu xulang7@gmail.com
Added `hip` suffix to adapter_v2.cc when building with pytorch rocm
Fixes #3837

add hip suffix to adapter_v2.cc when building with pytorch rocm

---

.github/gen-workflow-ci.py
.github/workflows/ci.yaml

Buildkite has merged my changes, so we can move back from my fork to the original trigger action.

[CI] Move back to upstream buildkite trigger

---

CHANGELOG.md
CMakeLists.txt
cmake/Modules/FindNCCL.cmake

This change follows the discussion in  #3831 to avoid the NCCL error "Cuda failure 'CUDA driver is a stub library'".
- `CMAKE_CUDA_RUNTIME_LIBRARY` setting is only effective with CMake 3.17+ (and there is no Horovod build environment variable to control it at this time); with CMake 3.13 the CUDA runtime library is always linked statically on my system. https://cmake.org/cmake/help/latest/variable/CMAKE_CUDA_RUNTIME_LIBRARY.html
- added warning if dynamic CUDA RT (non-default) is combined with static NCCL (default)
- added CMake status message printing full NCCL_VERSION_CODE (e.g., 21505)
- made build environment variable HOROVOD_NCCL_LINK case-insensitive
Related code in `add_cuda` macro that is meant to explicitly add libraries depending on `CMAKE_CUDA_RUNTIME_LIBRARY` may not actually …

Build: Link CUDA runtime library statically by default

---

.github/workflows/ci-results.yaml

This enables DEBUG logging for the publish action. This has to be done in master to take effect.

[CI] Set publish action log level to DEBUG

---

.readthedocs.yaml

Signed-off-by: Abolfazl Shahbazi <abolfazl.shahbazi@intel.com>
This is just to use `Python 3.8` everywhere since all GitHub actions are on that version also `3.7` end of life is approaching fast: https://endoflife.date/python

Use Python 3.8 to build docs as well

---

CHANGELOG.md
horovod/tensorflow/__init__.py
test/parallel/test_tensorflow.py

Adding a new `get_local_and_global_gradients()` method to the `PartialDistributedGradient` for use cases where the separation is needed.
*More context:* Following the discussions in [discussions/3705](https://github.com/horovod/horovod/discussions/3705) and #3643, in model parallelism use cases, each rank has two sets of gradients: local gradients and non-local gradients. The non-local gradients are allreduced and hence synced accross the ranks, but the local gradients remain specific to each rank.
Now for operations such as gradient norm calculation, it needs to be done on the local and non-local gradients separately otherwise the result on each rank will be different due to their local gradients.
This new method provides the decoupled gradients to be used for upstream operations such as …

TF: Add get_local_and_global_gradients() to PartialDistributedGradentTape

---

CHANGELOG.md
horovod/tensorflow/__init__.py

Forces tf.logical_and and related ops during hvd allreduce condition check running on CPU.
Why?
tf.logical_and will be scheduled on GPU by default. However, other hvd control ops such as process_set_included_op or size_op and TF cond ops only run on CPU. It will end up doing a memory copy from host to device to compute the tf.logical_and and doing another device to host copy to compute tf.cond. The PR force all condition related ops running on CPU to avoid unnecessary host to device and device to host memory copy.
We see 10% performance improvement when memory copy resource is under contention in our internal workflow . 
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/GOVERNANCE.md) …

Force tf.logical_and in hvd allreduce condition running on CPU

---

CHANGELOG.md
examples/tensorflow2/tensorflow2_keras_mnist.py
examples/tensorflow2/tensorflow2_mnist_data_service_train_fn_compute_side_dispatcher.py
horovod/_keras/__init__.py
horovod/common/util.py
horovod/keras/__init__.py
horovod/spark/keras/bare.py
horovod/spark/keras/estimator.py
horovod/spark/keras/optimizer.py
horovod/spark/keras/tensorflow.py
horovod/tensorflow/__init__.py
horovod/tensorflow/elastic.py
horovod/tensorflow/gradient_aggregation_eager.py
horovod/tensorflow/keras/__init__.py
test/integration/data/elastic_tensorflow2_main.py
test/integration/test_spark_keras.py
test/parallel/test_keras.py
test/parallel/test_tensorflow2_keras.py
test/parallel/test_tensorflow2_keras_process_sets.py
test/parallel/test_tensorflow_keras.py

Re-enabling TF Keras 2.11+ optimizers. ~Those and the legacy ones should work out the box with Horovod.~
Using new optimizers with `LossScaleOptimizer` is broken in 2.11 but fixed in 2.12.
See discussions at https://github.com/keras-team/keras/issues/17275
and commit at https://github.com/keras-team/keras/commit/c98ea36b96f6036b1dec569e5e496aee06a44b29
EDIT:
They are quite a few changes in API between the 2 optimizer versions. But hopefully this PR properly integrates Horovod to the new ones while maintaining support for the old ones.

Re-enabling new keras optimizers

---

.buildkite/gen-pipeline.sh
.github/workflows/ci.yaml
CHANGELOG.md
CMakeLists.txt
docker-compose.test.yml
test/single/data/expected_buildkite_gpu_heads_pipeline.yaml
test/single/data/expected_buildkite_gpu_non_heads_pipeline.yaml

Another round of upgrading tested frameworks:
- fix MXNet versions
- upgrade torch to 1.13.1
- upgrade pyspark to 3.3.2, add 3.4.0, remove 3.2.3
- add Tensorflow 2.12.0, remove 2.9.3, upgrade to 2.11.1

Upgrade CI test frameworks and fix linking NCCL 2.12+

---

docs/conf.py
docs/mpi.rst

Fix (warning in) readthedocs build.
A warning appeared regarding an invalid label, which started to fail the build. I couldn't figure out easily how to fix the link without introducing extra duplicate label warnings (seem to be related to the nested file structure with `mpi.rst` and `mpi_include.rst`), so I just removed it. In the latest or stable docs the link currently doesn't work at all anyway.

Docs: Fix invalid link to local section

---

horovod/torch/cuda_util.cc

Macro testing on `__HIP_PLATFORM_HCC__` as workaround ROCm's not supporting PFN_cuCtxGetDevice (does support cuCtxGetDevice -> hipCtxGetDevice).
https://github.com/horovod/horovod/issues/3927

Fix torch build on ROCm by avoiding dynamically loaded cuCtxGetDevice

---

CHANGELOG.md
horovod/__init__.py

As Horovod v0.28.0 doesn't work with AMD GPUs, It would be nice to get a patch release out soon.

Bump version to v0.28.1

---

horovod/runner/mpi_run.py

This pull request addresses GitHub issue #3933, which reports a missing `-iface` argument in the mpirun command generated by the Horovod runner. The omission of this argument can lead to errors in setups with MPICH and multiple servers.

Fix missing -iface argument in generated mpirun command

---

.buildkite/gen-pipeline.sh
.github/workflows/ci.yaml
Dockerfile.test.gpu
docker-compose.test.yml
test/single/data/expected_buildkite_gpu_non_heads_pipeline.yaml

Nvidia doesn't provide the CUDA 11.6.1 container anymore -> minor bump to 11.6.2
Also, Nvidia doesn't provide any CUDA 10.x containers anymore. To continue testing TF 1.15.5 we can switch to the `nvidia-tensorflow` package from https://github.com/NVIDIA/tensorflow. In doing so, we drop testing with some old CUDA-10-specific versions of mxnet or torch. This tensorflow wheel is built for Python 3.8 (previously we used Python 3.7 for TF 1.15), which requires updating pyspark from 2.4 to 3.0. Ultimately, this means that some minimum versions in CI would differ between CPU and GPU paths.

CI: Bump container images to CUDA 11.6.2 and remove CUDA 10.x container configs

---

docker/horovod-nvtabular/Dockerfile

Work around install issue for `cudf-cu11` on Python 3.8: https://github.com/rapidsai/cudf/issues/13642
Also pinning related package `dask-cudf-cu11`.
Note: Command line to check available versions on Nvidia's package index: 
```
$ pip index versions cudf-cu11 --python-version 3.8 --index-url=https://pypi.nvidia.com
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
cudf-cu11 (23.4.1)
Available versions: 23.4.1, 23.4.0.1681363056, 23.4.0, 23.2.0, 22.12.0, 22.10.0
```
3. If any member of the technical steering committee requests …

Pin cudf-cu11 and dask-cudf-cu11 for horovod-nvtabular docker build

---

horovod/runner/mpi_run.py
test/single/test_run.py

Fixes #2761.
Horovod still uses `MPICH` in `mpirun --version` to detect MPICH. In the unittest, the test case has `MPICHLIB_CFLAGS` flag. However, not all MPICH builds has this flag. For example, on Ubuntu 22.04, the MPICH installed with `apt-get` has no `MPICH`.
Here is the way to reproduce it (using docker):
```docker
FROM ubuntu:22.04
RUN apt-get update && apt-install -y mpich && mpirun --version
```
The output is:
```
HYDRA build details:
Version:                                 4.0
Release Date:                            Fri Jan 21 10:42:29 CST 2022
CC:                              gcc -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -ffile-prefix-map=/build/mpich-0xgrG5/mpich-4.0=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat …
```

detect MPICH via `HYDRA`

---

horovod/_keras/__init__.py
horovod/tensorflow/__init__.py

In horovod elastic mode we are seeing 
```
[6]<stderr>:        gradients = tape.gradient(loss_value, self._model.trainable_weights)
[6]<stderr>:    File "/home/jobuser/.local/lib/python3.10/site-packages/horovod/tensorflow/__init__.py", line 1089, in gradient  *
[6]<stderr>:        grad = tf.IndexedSlices(grad.values / horovod_size, grad.indices, grad.dense_shape)
[6]<stderr>:
[6]<stderr>:    TypeError: `x` and `y` must have the same dtype, got tf.float32 != tf.int32.
```
which is a type mismatch from size_op and the gradient values. This PR fixes this issue.
3. If any member of the technical …

Fix data type in PartialDistributedGradientTape

---

examples/mxnet/mxnet2_mnist.py
examples/mxnet/mxnet_mnist.py

The MNIST download url provided by MXNet is dead, added zip file to Horovod datasets S3 and use that.

Fix MXNet MNIST download url

---

.github/gen-workflow-ci.py
.github/workflows/ci-results.yaml
.github/workflows/ci.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/upload-pypi.yml

CI: Resolve deprecation & warning messages in workflows 
Enable DependaBot for GitHub actions
Node16 has been out of support since [September 2023](https://github.com/nodejs/Release/#end-of-life-releases). - more info in the [post](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)

CI: Fix warnings & deprecation messages in the workflows

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Installing pytorch lightning pre 1.8.4 fails for pip>23.2.1 due to
invalid metadata: .* suffix can only be used with == or != operators
See: https://github.com/pypa/pipx/issues/998

Build: Use pip==23.2.1 for pytorch-lightning<1.8.4

---

Dockerfile.test.cpu
Dockerfile.test.gpu

Recently, there have been a lot of GPG errors building our test docker images:
"Error: retrieving gpg key timed out"
Using a different keyserver should mitigate this.

CI: Use specific GPG keyserver to avoid GPG timeout

---

Dockerfile.test.cpu
Dockerfile.test.gpu
setup.py

With pytest>=8, test class decoration `pytest.mark.skipif` is ignored. Using pytest<8 in CI.
Includes #4059

CI: Constraint pytest to <8 to make skipif work for test classes

---

horovod/spark/common/params.py
horovod/spark/keras/datamodule.py
horovod/spark/keras/estimator.py
horovod/spark/keras/remote.py
horovod/spark/keras/util.py
test/integration/test_spark_keras.py

Add support for disabling autotune parameter for batch prefetch as it results into memory leak with ray.
tf.data.autotune prefetches more than one batch which cause a spiky increase in the memory. Adding an option to disable it will help configure the models which are OOMing because of high memory usage
Added additional param to disable the autotune batch prefetch behavior at the time of data loading such that models which can OOM due to high memory usage can configure it to disable. 
Many models in Uber are facing this issue.
OOM due to memory leak in Keras + horovod training.
3. If …

Add support for disabling autotune parameter for batch prefetch
